<?php
/**
 * Braintree Payments Extension
 *
 * This source file is subject to the Braintree Payment System Agreement (https://www.braintreepayments.com/legal)
 *
 * DISCLAIMER
 * This file will not be supported if it is modified.
 *
 * @copyright   Copyright (c) 2015 Braintree. (https://www.braintreepayments.com/)
 */
?>
<?php
$_form = $this;
$_code = $_form->getMethodCode();
$_model = Mage::getModel('braintree_payments/creditcard');
$_storedCards = Mage::helper('braintree_payments/createorder')->getCustomerCards();
$_useVault = $_model->useVault();
?>
<input id="<?php echo $_code ?>_payment_method" type="hidden" name="payment[method]" value="<?php echo $_code ?>"/>
<ul id="payment_form_<?php echo $_code ?>" class="form-list" style="display:none;">
    <?php if ($_storedCards): ?>
        <li id="<?php echo $_code ?>_token_selector">
            <label for="<?php echo $_code ?>_cc_token"><?php echo $this->__('Payment Information') ?></label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_cc_token" name="payment[cc_token]">
                    <?php foreach ($_storedCards as $creditCard): ?>
                        <option
                            value="<?php echo $this->escapeHtml($creditCard->token) ?>" <?php echo $creditCard->default ? 'selected="selected"' : '' ?>>
                            <?php echo $this->escapeHtml($creditCard->maskedNumber) . ' - ' . $this->escapeHtml($creditCard->cardType) ?>
                        </option>
                    <?php endforeach; ?>
                    <option value=''><?php echo $this->__('Add new card') ?></option>
                </select>
            </div>
        </li>
    <?php endif; ?>
    <li class="hide_if_token_selected">
        <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?><span
                class="required">*</span></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" class="required-entry validate-cc-type-select"
                    name="payment[cc_type]">
                <option value="">--<?php echo $this->__('Please Select') ?>--</option>
                <?php $_ccType = $_form->getInfoData('cc_type') ?>
                <?php foreach ($_form->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option
                        value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <li class="hide_if_token_selected">
        <label for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?><span class="required">*</span></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" data-braintree-name="number"
                   title="<?php echo $this->__('Credit Card Number') ?>"
                   class="input-text validate-cc-number validate-cc-type" value=""/>
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div" class="hide_if_token_selected">
        <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?><span
                class="required">*</span></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_expiration" data-braintree-name="expiration_month"
                    class="month validate-cc-exp required-entry">
                <?php $_ccExpMonth = $_form->getInfoData('cc_exp_month') ?>
                <?php foreach ($_form->getCcMonths() as $k => $v): ?>
                    <option
                        value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
            </select>
            <?php $_ccExpYear = $_form->getInfoData('cc_exp_year') ?>
            <select id="<?php echo $_code ?>_expiration_yr" data-braintree-name="expiration_year"
                    class="year required-entry">
                <?php foreach ($_form->getCcYears() as $k => $v): ?>
                    <option
                        value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php echo $_form->getChildHtml() ?>
    <?php if ($_form->hasVerification()): ?>
        <li id="<?php echo $_code ?>_cc_type_cvv_div" class="hide_if_token_selected">
            <label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?><span
                    class="required">*</span></label>
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" autocomplete="off" title="<?php echo $this->__('Card Verification Number') ?>"
                           class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid"
                           data-braintree-name="cvv" value=""/>
                </div>
            </div>
        </li>
    <?php endif; ?>
    <?php if ($_useVault): ?>
        <li id="<?php echo $_code ?>_store_in_vault_div" style="text-align:left;" class="hide_if_token_selected">
            <input type="checkbox" title="<?php echo $this->__('Save this card for future use') ?>"
                   class="input-checkbox" id="<?php echo $_code ?>_store_in_vault" name="payment[store_in_vault]"
                   value="1"/>
            <label for="<?php echo $_code ?>_store_in_vault"
                   style="float:none;"><?php echo $this->__('Save this card for future use') ?></label>
        </li>
    <?php endif; ?>

</ul>
<script type="text/javascript">
    //<![CDATA[
    <?php if ($_storedCards): ?>
    var enableDisableFields = function (disabled) {
        var code = "<?php echo $_code ?>";
        var fields = ["_cc_type", "_cc_number", "_expiration", "_expiration_yr", "_cc_cid", "_store_in_vault"];
        var id;
        for (id = 0; id < fields.length; id++) {
            if ($(code + fields[id])) {
                $(code + fields[id]).disabled = disabled;
            }
        }
    }

    var showHideFields = function () {
        var selectBox = $('<?php echo $_code ?>_cc_token');
        if (typeof selectBox !== 'undefined') {
            var initToken = selectBox.getValue();
        } else {
            var initToken = false;
        }

        if (initToken) {
            $('<?php echo $_code ?>_cc_type').value = "";
            $$('.hide_if_token_selected').invoke('hide');
            enableDisableFields("disabled");
        }

        $('<?php echo $_code ?>_cc_token').observe('change', function (e) {
            var selectBox = $(this);
            var token = selectBox.getValue();

            if (token) {
                $('<?php echo $_code ?>_cc_type').value = "";
                $$('.hide_if_token_selected').invoke('hide');
                enableDisableFields("disabled");
            } else {
                $$('.hide_if_token_selected').invoke('show');
                enableDisableFields(false);
            }
        });
    }
    <?php endif ?>
    var braintreeUtils;
    var formId = 'iwd_payment_edit_form';
    var save_payment_button = $ji('#iwd_payment_edit_form button[onclick="IWD.OrderManager.Payment.editPaymentSubmit()"]');
    var save_payment_func = save_payment_button.attr('onclick');
    var setupBraintree = function () {
        if (typeof braintreeUtils !== 'object') {
            var braintreeUtils = new BraintreeUtils();
        }
        braintreeUtils.setup("<?php echo Mage::helper('braintree_payments')->getToken() ?>", formId);
        <?php if (Mage::helper('braintree_payments')->isAdvancedFraudProtectionEnabled()): ?>
        braintreeUtils.setupDataJS(
            '<?php echo Mage::helper('braintree_payments')->getKountEnvironment()?>',
            '<?php echo Mage::helper('braintree_payments')->getKountId()?>',
            '<?php echo Mage::helper('braintree_payments/createorder')->getMerchantId() ?>',
            formId
        );
        <?php endif; ?>
    };

    var submitOrder = function () {
        save_payment_button.attr('id', 'iwd_ordermanager_update_payment_button').removeAttr('onclick');
        $ji(document).on('click', '#iwd_ordermanager_update_payment_button', function(){
            <?php if ($_storedCards): ?>
            showHideFields();
            <?php endif;?>
            if (order.paymentMethod === '<?php echo $_code?>' &&
                (($('<?php echo $_code ?>_cc_token') && $('<?php echo $_code ?>_cc_token').value === '') || !$('<?php echo $_code ?>_cc_token'))) {

                $('loading-mask').show();

                var onSuccess = function () {
                    eval(save_payment_func);
                };
                if (typeof braintreeUtils !== 'object') {
                    var braintreeUtils = new BraintreeUtils();
                    braintreeUtils.setup("<?php echo Mage::helper('braintree_payments')->getToken() ?>", formId);
                }

                braintreeUtils.createHiddenInput(
                    {
                        name: "payment[nonce]",
                        id: '<?php echo Mage::helper('braintree_payments')->getNonceInputId() ?>'
                    },
                    formId
                );
                braintreeUtils.getPaymentNonce(
                    '<?php echo $_code ?>',
                    '<?php echo Mage::helper('braintree_payments')->getCardholderName() ?>',
                    onSuccess,
                    "<?php echo Mage::helper('braintree_payments')->getToken() ?>"
                );
            }else{
                eval(save_payment_func);
            }
        });
        $$('.save').each(function (element) {
            element.writeAttribute('onclick', '');
            Event.observe(element.id, 'click', function (event) {
                event.stop;
                <?php if ($_storedCards): ?>
                showHideFields();
                <?php endif;?>
                if (order.paymentMethod === '<?php echo $_code?>' &&
                    (($('<?php echo $_code ?>_cc_token') && $('<?php echo $_code ?>_cc_token').value === '') || !$('<?php echo $_code ?>_cc_token'))) {

                    $('loading-mask').show();

                    var onSuccess = function () {
                        $('loading-mask').hide();
                        order.submit();
                    };
                    if (typeof braintreeUtils !== 'object') {
                        var braintreeUtils = new BraintreeUtils();
                        braintreeUtils.setup("<?php echo Mage::helper('braintree_payments')->getToken() ?>", formId);
                    }

                    braintreeUtils.createHiddenInput(
                        {
                            name: "payment[nonce]",
                            id: '<?php echo Mage::helper('braintree_payments')->getNonceInputId() ?>'
                        },
                        formId
                    );
                    braintreeUtils.getPaymentNonce(
                        '<?php echo $_code ?>',
                        '<?php echo Mage::helper('braintree_payments')->getCardholderName() ?>',
                        onSuccess,
                        "<?php echo Mage::helper('braintree_payments')->getToken() ?>"
                    );
                } else {
                    order.submit();
                }
            });
        });
    };

    // if the editForm isn't available, wait for the page to finish loading
    // (this occurs when a user manually refreshes the admin order form page)
//    if (typeof editForm !== 'undefined') {
//        setupBraintree();
//        submitOrder();
//        <?php //if ($_storedCards): ?>
//        showHideFields();
//        <?php //endif ?>
//    } else {
//        document.observe('dom:loaded', setupBraintree);
//        document.observe('dom:loaded', submitOrder);
//        <?php //if ($_storedCards): ?>
//        document.observe('dom:loaded', showHideFields);
//        <?php //endif ?>
//    }
    setupBraintree();
    submitOrder();
    <?php if ($_storedCards): ?>
    showHideFields();
    <?php endif ?>
    Validation.creditCartTypes = $H({
        'VI': [new RegExp('^4[0-9]{12}([0-9]{3})?$'), new RegExp('^[0-9]{3}$'), true],
        'MC': [new RegExp('^5[1-5][0-9]{14}$'), new RegExp('^[0-9]{3}$'), true],
        'AE': [new RegExp('^3[47][0-9]{13}$'), new RegExp('^[0-9]{4}$'), true],
        'DI': [new RegExp('^6011[0-9]{12}$'), new RegExp('^[0-9]{3}$'), true],
        'JCB': [new RegExp('^(3[0-9]{15}|(2131|1800)[0-9]{11})$'), new RegExp('^[0-9]{3,4}$'), true],
        'OT': [false, new RegExp('^([0-9]{3}|[0-9]{4})?$'), false]
    });
    //]]>
</script>
