    <link href="<?php echo $this->getSkinUrl("css/zozo.accordion.min.css")?>" rel="stylesheet">
    <script src="<?php echo $this->getSkinUrl("js/jquery.easing.min.js")?>"></script>
    <script src="<?php echo $this->getSkinUrl("js/zozo.accordion.min.js")?>"></script>
     <div id="accordion1" style="width: 99%; padding: 0;">
             <div id="demo-accordion">
                <section>
                    <h3>CARAT </h3>
                    <div>
                       <div class="slide_content carat">
			<h3>Carat</h3>
			<p>Diamonds and other gemstones are weighed in metric carats: one carat is equal to 0.2 grams, about the same weight as a paperclip. (Don’t confuse carat with karat, as in “18K gold,” which refers to gold purity.)</p>
			<img src="http://www.jewelrydemo.com/media/images/carat_img.jpg"><p>Just as a dollar is divided into 100 pennies, a carat is divided into 100 points. For example, a 50-point diamond weighs 0.50 carats. But two diamonds of equal weight can have very different values depending on the other members of the Four C’s: clarity, color and cut. The majority of diamonds used in fine jewelry weigh one carat or less.</p>
			<p>Because even a fraction of a carat can make a considerable difference in cost, precision is crucial. In the diamond industry, weight is often measured to the hundred thousandths of a carat, and rounded to a  hundredth of a carat.  Diamond weights greater than one carat are expressed in carats and decimals. (For instance, a 1.08 ct. stone would be described as “one point oh eight carats,” or “one oh eight.”)</p>
			<h4>HOW DID THE CARAT SYSTEM START?</h4>
			<p class="half">The carat, the standard unit of weight for diamonds and other gemstones, takes its name from the carob seed. Because these small seeds had a fairly uniform weight, early gem traders used them as counterweights in their balance scales. The modern metric carat, equal to 0.2 grams, was adopted by the United States in 1913 and other countries soon after. Today, a carat weighs exactly the same in every corner of the world.</p>

		</div>
                    </div>
                </section>
                <section>
                    <h3>COLOR </h3>
                    <div>
                     <div class="slide_content color">
			<h3>Color</h3>
			<p>Diamond color is all about what you can’t see. Diamonds are valued by how closely they approach colorlessness &ndash; the less color, the higher their value. (The exception to this is fancy-color diamonds, such as pinks and blues, which lie outside this color range.)</p>
			<img src="http://www.jewelrydemo.com/media/images/color_img1.jpg"><p>Most diamonds found in jewelry stores run from colorless to near-colorless, with slight hints of yellow or brown.</p>
			<p>GIA’s color-grading scale for diamonds is the industry standard. The scale begins with the letter D, representing colorless, and continues with increasing presence of color to the letter Z, or near-colorless. Each letter grade has a clearly defined range of color appearance. Diamonds are color-graded by comparing them to stones of known color under controlled lighting and precise viewing conditions.</p>
			<p>Many of these color distinctions are so subtle as to be invisible to the untrained eye. But these slight differences make a very big difference in diamond quality and price.</p>
                        <img src="http://www.jewelrydemo.com/media/images/color_img2.jpg">
			<h4>WHY DOES THE GIA COLOR GRADING SYSTEM START AT D?</h4>
			<p>Before GIA developed the D-Z Color Grading Scale, a variety of other systems were loosely applied. These included letters of the alphabet (A, B and C, with multiple A’s for the best stones), Arabic (0, 1, 2, 3) and Roman (I, II, III) numerals, and descriptions such as “gem blue” or “blue white.” The result of all these grading systems was inconsistency and inaccuracy. Because the creators of the GIA Color Scale wanted to start fresh, without any association with earlier systems, they chose to start with the letter D&mdash;a letter grade normally not associated with top quality.</p>
		</div>
                    </div>
                </section>
                <section>
                    <h3>CLARITY </h3>
                    <div>
                    <div class="left">
		    <img src="http://www.jewelrydemo.com/skin/frontend/evolved/default/images/clarity_left_bg.jpg" style="margin: 0px;">
		  </div>
                    <div class="slide_content clarity">
			<h3>Clarity</h3>
                         <img class="right" src="http://www.jewelrydemo.com/media/images/clarity_img.jpg">
			<p>Because diamonds formed deep within the earth, under extreme heat and pressure, they often contain unique birthmarks, either internal (inclusions) or external (blemishes).</p>
			<p>Diamond clarity refers to the absence of these inclusions and blemishes. Diamonds without these birthmarks are rare, and rarity affects a diamond’s value. Using the GIA International Diamond Grading System&trade;, diamonds are assigned a clarity grade that ranges from flawless (FL) to diamonds with obvious  inclusions (I3).</p>
			<p>Every diamond is unique. None is absolutely perfect under 10× magnification, though some come close. Known as Flawless diamonds, these are exceptionally rare. Most jewelers have never even seen one.</p>
			<p>The GIA Clarity Scale contains 11 grades, with most diamonds falling into the VS (very slightly included) or SI (slightly included) categories. In determining a clarity grade, the GIA system considers the size, nature, position, color or relief, and quantity of clarity characteristics visible under 10× magnification.</p>
			<p>Flawless (FL) - No inclusions or blemishes are visible to a skilled grader using 10× magnification<br>
Internally Flawless (IF) - No inclusions and only blemishes are visible to a skilled grader using 10× magnification<br>
Very, Very Slightly Included (VVS1 and VVS2) - Inclusions are difficult for a skilled grader to see under 10× magnification<br>
Very Slightly Included (VS1 and VS2) - Inclusions are clearly visible under 10× magnification but can be characterized as minor<br>
Slightly Included (SI1 and SI2) - Inclusions are noticeable to a skilled grader using 10× magnification<br>
Included (I1, I2, and I3) - Inclusions are obvious under 10× magnification and may affect transparency and brilliance</p>
			<h4>HOW DID THE GIA CLARITY SCALE COME ABOUT?</h4>
			<p>Like the color scale, GIA’s clarity grading system developed because jewelers were using terms that were easily misinterpreted, such as "loupe clean," or "piqué." Today, even if you buy a diamond in another part of the world, the jeweler will likely use terms such as VVS1 or SI2, even if her language is French or Japanese instead of English.</p>
		</div>
                    </div>
                </section>
                <section>
                    <h3>CUT </h3>
                    <div>
                        <div class="slide_content cut">
			<h3>Cut</h3>
			<p>Cut is the factor that fuels a diamond’s fire, sparkle and brilliance.</p>
			<p>The traditional 58 facets in a round brilliant diamond, each precisely cut and defined, are as small as two millimeters in diameter. But without this precision, a diamond wouldn’t be nearly as beautiful. The allure of a particular diamond depends more on cut than anything else.</p>
			<p>Though extremely difficult to analyze or quantify, the cut of any diamond has three attributes: brilliance (the total light reflected from a diamond), fire (the dispersion of light into the colors of the spectrum), and scintillation (the flashes of light, or sparkle, when a diamond is moved).</p>
			<p>An understanding of diamond cut begins with the shape of a diamond. The standard round brilliant is the shape used in most diamond jewelry. All others are known as fancy shapes. Traditional fancy shapes include the marquise, pear, oval and emerald cuts. Hearts, cushions, triangles and a variety of others are also gaining popularity in diamond jewelry.</p>
			<img src="http://www.jewelrydemo.com/media/images/cut_img.jpg">
                        <p>As a value factor, though, cut refers to a diamond’s proportions, symmetry and polish. For example, look at a side view of the standard round brilliant. The major components, from top to bottom, are the crown, girdle and pavilion. A round brilliant cut diamond has 57 or 58 facets, the 58th being a tiny flat facet at the bottom of the pavilion that’s known as the culet. The large, flat facet on the top is the table. The proportions of a diamond refer to the relationships between table size, crown angle and pavilion depth. A wide range of proportion combinations are possible, and these ultimately affect the stone’s interaction with light.</p>
			<p>In early 2005, GIA unveiled a diamond cut grading system for standard round brilliants in the D-to-Z color range. This system, the product of more than 15 years of intensive research and testing, assigns an overall diamond cut grade ranging from Excellent to Poor.</p>
			<h4>HOW DOES PAVILION DEPTH AFFECT A DIAMOND'S CUT?</h4>
			<p>The distance from the bottom of the girdle to the culet is the pavilion depth. A pavilion depth that’s too shallow or too deep will allow light to escape through the sides or the bottom of the stone. A well-cut diamond will direct more light through the crown.</p>
		</div>
                    </div>
                </section>
                <section>
                    <h3>SHAPE </h3>
                    <div>
                       <div class="slide_content shape">
			<h3>Shape</h3>
			<p>The shape that most people will be familiar with is the round diamond.  This represents the classic diamond, the example of brilliance and shine.  However, there are actually several other shapes in addition to the standard round.  It takes a careful and precise hand to cut these various shapes flawlessly.  Below, you will find examples of the different shapes that you might find in our store.</p>
                         <ul>
	                        <li><img src="http://www.jewelrydemo.com/media/images/shape_1.jpg"></li>
	                        <li><img src="http://www.jewelrydemo.com/media/images/shape_2.jpg"></li>
	                        <li><img src="http://www.jewelrydemo.com/media/images/shape_3.jpg"></li>
	                        <li><img src="http://www.jewelrydemo.com/media/images/shape_4.jpg"></li>
	                        <li><img src="http://www.jewelrydemo.com/media/images/shape_5.jpg"></li>
	                        <li><img src="http://www.jewelrydemo.com/media/images/shape_6.jpg"></li>
	                        <li><img src="http://www.jewelrydemo.com/media/images/shape_7.jpg"></li>
	                        <li><img src="http://www.jewelrydemo.com/media/images/shape_8.jpg"></li>
	                        <li>&nbsp;</li>
	                        <li><img src="http://www.jewelrydemo.com/media/images/shape_9.jpg"></li>
	                        <li><img src="http://www.jewelrydemo.com/media/images/shape_10.jpg"></li>
	                        <li>&nbsp;</li>
	                 </ul>
		</div>
                    </div>
                </section>
            </div>
        </div>
 

    <style>
        #page
        {
            height: 100%;            
            margin: 0 auto;
            padding: 0px;
            width: 98%;
        }

        .z-accordion > section > h3{text-transform: uppercase;}        
    </style>

    <!--
    comment to test html5 data attributes.-->
 <script>
        jQuery(document).ready(function () {
        	jQuery("#demo-accordion").zozoAccordion({
                theme: "black",
                orientation: "horizontal",
                active: 0,
                width: 1100,
                height: 535,
                sectionSpacing: 0,
                headerSize: 30,
                headerFontSize: 2.2,
                slider: true,                
                showIcons: false,
                responsive: true,
                shadows: false,
                dotNav:false,
                bordered: true,
                responsiveDelay: 0,
                animation: {
                    easing: "easeOutQuart",
                    duration: 1000
                } 
            });
        });       
    </script>
    
</body>
</html>
 
