<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div class="product-view related-product-view">
    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="rel_product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            </div>
			<?php //echo "<pre>"; print_r($_product); echo "</pre>";?>
			<?php if( $_product->getTypeId() == 'grouped' ): ?>
				<div class="main_grouped_product_detail">
					<h1>
						<?php 
						$printerType = $_product->getAttributeText('printer_type');
						if($printerType == 'Toner') {
							$inkText = 'laser';
						} else { // if type = Inkjet
							$inkText = 'ink';
						}

						$printerBrand = $_product->getAttributeText('printer_brand');
						$groupTitle = $_product->getName();
						if( strpos( $_product->getName(), '/' ) !== false ) {
							$explodeName = explode('/',$groupTitle);
							$groupTitle = $explodeName[count($explodeName)-1]; // get name after last slash
						}
						$groupNameFinal = $printerBrand . " " . $groupTitle . " ". $printerType;
						?>
						<?php echo $groupNameFinal; ?>
						<?php //echo $_product->getResource()->getAttribute('printer_brand')->getFrontend()->getValue($_product); ?>
						<?php //echo $_product->getResource()->getAttribute('printer_model')->getFrontend()->getValue($_product); ?>
					</h1>
					<?php //Add dynamic text to grid page Task: http://production.idealbrandmarketing.com/task_detail.php?ti=13179 ?>
					<div class="short-description groupeddesc">
						The <?php echo $printerBrand ?> <?php echo $groupTitle; ?> <?php echo $printerType ?> Printer can accept OEM <?php echo $inkText; ?> cartridges or remanufactured / compatible <?php echo $inkText; ?> cartridges. 
						Our replacement <?php echo $printerBrand ?> <?php echo $groupTitle; ?> <?php echo $inkText; ?> cartridges and <?php echo $inkText; ?> refills are made to the highest quality standards, with attention focused on both print quality and print yield.
					</div>
					 
					<div class="tooltipmain">
							<!--<h3>Add to My Printers</h3>-->
							<h3><img src="<?php echo $this->getSkinUrl('images/setmyprinterbtn.jpg'); ?>"></h3>
							<p class="i">i</p>
							
							<div class="selectprinter-topmenu_detail"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('part-finder-header-product')->toHtml();?></div>
							
							
							<p class="tooltip">Save this printer to "My Printers" which is an accessible tab from the top of the page to allow you to quickly find items for orders and re-orders.</p>
						</div>
					
					<?php /* ?>
					<div class="short-description">
						<div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?></div>
					</div>
					<?php */ ?>
				</div>				
				<?php /********************  For Group Product  ****** *************  ************/?>
			
				<div class="only_group_product">
					<?php echo $this->getChildHtml('product_type_data') ?>
				</div>
				
				<?php /********************  End Group Product  ****** *************  ************/?>
				
			<?php else: ?>

            <div class="product-img-box">
                <div class="product-name">
                    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                </div>
                <?php echo $this->getChildHtml('media') ?>
				<?php /*<div class="short-description">
					<?php echo $_product->getDescription(); ?>
				</div>	 */ ?>
            </div>
			<div class="product-right">
	            <div class="product-shop">
	                <div class="product-name">
	                    <span class="h1"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
	                </div>
	                <!--<div class="product-sku">
	                    <span class="h1"><?php //echo $_helper->productAttribute($_product, $_product->getSku(), 'sku') ?></span>
	                </div>-->
	                
					<div class="stock_check">
							<?php // Check to see if the item is in stock 
							if($_product->stock_item->is_in_stock == 1): 
								echo $this->__('In Stock'); ?>

							<?php else:?>
								
									<?php echo $this->__('Out Of stock'); ?>
							<?php endif; ?>
					</div> 
					<div class="reviewdata">   
					<?php echo $this->getReviewsSummaryHtml($_product, 'default', true) ?>
					</div>
					<?php $clr= $_product->getResource()->getAttribute('product_color')->getFrontend()->getValue($_product); ?>
			
				<?php if($clr == "Cyan"){ ?>
					<style>	
					.product_four_part .<?php echo $clr ; ?>::before {
							background: #00aeef;
							border-radius: 16px;
							content: "";
							height: 0; 
							margin-right: 5px;
							padding-left: 25px;
							width: 0;
						}
				</style>		
				<?php } else { ?>
				<style>	
						.product_four_part .<?php echo $clr ; ?>::before {
							background: <?php echo $clr ; ?>;
							border-radius: 16px;
							content: "";
							height: 0;
							margin-right: 5px;
							padding-left: 25px;
							width: 0;
						}
				</style>		
				
				<?php } ?>
					
					</div>
					
					<div class="product_four_part">
				
				
					<?php $pageyielddata = $_helper->productAttribute($_product, $_product->getYield(), 'yield');
					      $optical = $_product->getResource()->getAttribute('shelflife')->getFrontend()->getValue($_product);
					 ?>
					 <div class="page_yield">
					<?php if($pageyielddata){ ?>
					<h1><?php echo $pageyielddata; ?></h1><?php echo $this->__('Page Yield'); ?>
					<?php } ?>
					</div>
					
					<div class="color">
					<?php if($clr){ ?>
					<h1 class="round_color  <?php echo $clr ; ?> "><?php echo $clr; ?></h1>
					<?php } ?>
					</div>
					
					<div class="shelf_life">
					<?php if($optical=='No'){}else{ ?>
					<?php echo $this->__('Shelf Life'); ?><h1><?php echo $optical;  ?></h1>
					<?php } ?>
					</div>
					
				<!--	<div class="line"></div> -->

	            </div>
	            
	            <div class="product_left_part">	            
	            
	                <div class="price-info">
	                    <?php echo $this->getPriceHtml($_product); ?> 
	                    <?php echo $this->getChildHtml('bundle_prices') ?>
	                    <?php echo $this->getTierPriceHtml() ?>
	                </div>
						
	                <div class="extra-info">
	                </div>
	
	                <?php echo $this->getChildHtml('alert_urls') ?>
	                
	                
	
					<div class="add-to-cart-wrapper">
						<?php echo $this->getChildHtml('extrahint') ?>
		
						<?php //if (!$_product->hasOptions()):?>
						<?php if (!$_product['has_options']): ?>
							<div class="add-to-box">
								<?php if($_product->isSaleable()): ?>
									<?php echo $this->getChildHtml('addtocart') ?>
									
									<script type="text/javascript" src="<?php echo $this->getBaseUrl().'js/calendar/calendar.js'; ?>"></script>
									<script type="text/javascript" src="<?php echo $this->getBaseUrl().'js/calendar/calendar-setup.js'; ?>"></script>
									<link type="text/css" href="<?php echo $this->getBaseUrl().'js/calendar/calendar-win2k-1.css'; ?>" rel="stylesheet" >
									<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/customcontactnew/customcontactnew.css" type="text/css">
							</div>
							<?php echo $this->getChildHtml('extra_buttons') ?>
						<?php elseif (!$_product->isSaleable()): ?>
							<div class="add-to-box">
								<?php //echo $this->getChildHtml('addto') ?>
								<?php //echo $this->getChildHtml('sharing') ?>
							</div>
						<?php endif; ?> 
						<?php if($theme['productdetails_tab_attribute_option'] == 'outside'): ?>
							<div class="pro_attribute">
								 <?php echo $this->getChildHtml('additional') ?>
							</div>
						<?php endif; ?>
					</div>
					<?php $DiscountPrice=$_product->getFinalPrice()*95/100; ?>
					<?php $priceDiscount = Mage::getModel('sales/order')->formatPricePrecision($DiscountPrice, 2); ?>	
					<?php $discount = $_product->getFinalPrice()-$DiscountPrice; ?>
					<?php $discount = Mage::getModel('sales/order')->formatPricePrecision($discount, 2); ?>
					<?php if( !(strpos(strtolower($_product->getName()), 'oem') !== false) ): ?>
						<p class="disscount">Buy 3 or more for <?php echo $priceDiscount?> each (save an extra <?php echo $discount ?> each)</p>
					<?php endif; ?> 
				</div>
	

	            <?php //echo $this->getChildHtml('related_products') ?>
	            
	            <div class="product_right_part">
	            <?php
                echo $this->getLayout()->createBlock('cms/block')->setBlockId('product_detail')->toHtml();
                ?>
	            </div>
	
	            <div class="clearer"></div>

	        </div>

			<?php endif; ?>
        <?php endif; ?>
		</form>

        <?php if( $_product->getTypeId() !== 'grouped' ): ?>
        <?php
        $compatiblePrinters = explode("," , $_product->getCompatiblePrinters());
        $compatibleCartridges = explode("," , $_product->getCompatibleCartridges());

        $compatibleArray = array_merge($compatiblePrinters,$compatibleCartridges);
        //echo "<pre>"; print_r($compatibleArray); echo "</pre>";
        $compatibleValues = array();
        foreach ($compatibleArray as $compatibleModel) {
            $attribute = Mage::getSingleton('catalog/product')->getResource()->getAttribute("printer_model");
            if ($attribute->usesSource()) {
                $valueId = $attribute->getSource()->getOptionId($compatibleModel);
                $compatibleValues[] = array('attribute'=>'printer_model', 'finset'=>$valueId);
            }
        }

        //echo "<pre>"; print_r($compatibleValues); echo "</pre>";
        $compatibleCollection = Mage::getModel('catalog/product')
            ->getCollection()
            ->addAttributeToSelect('*')
            ->addAttributeToFilter('type_id','grouped')
            ->addAttributeToFilter($compatibleValues)->load();

        //echo $compatibleCollection->getSelect();
        //echo "<pre>"; print_r($compatibleCollection->getData()); echo "</pre>";
        $compatibleGroupsUrl = array();
        foreach ($compatibleCollection as $compatible) {
            $printerModel = Mage::helper('brandfilter')->getProductAttributeValue($compatible, 'printer_model');
            $compatibleGroupsUrl[$printerModel] = Mage::getBaseUrl().$compatible->getUrlKey();
        }
        //echo "<pre>"; print_r($compatibleGroupsUrl);  echo "</pre>";
        ?>
        <div class="description-compatible-printer-container">
            <div class="product_last_part">
                <h1>Description</h1>
                <div class="short-description">
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?></div>
                </div>
                <div class="sku">
                    <span>Item #:<?php echo $_product->getSku(); ?></span>
                </div>
            </div>

            <div class="product_last_part compatible_printers">

                <div class="contain_part11">
                    <h1><?php echo $this->__('Compatible Printers'); ?></h1>
                    <?php if(count($compatiblePrinters) > 0): ?>
                        <ul>
                            <?php foreach ($compatiblePrinters as $printerModel): ?>
                                <li><a href="<?php echo $compatibleGroupsUrl[$printerModel] ?>"><?php echo $printerModel ?></a></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php else: ?>
                        <?php echo $this->__('No Compatible Printers Found.'); ?>
                    <?php endif; ?>
                </div>

                <div class="contain_part11">
                    <h1><?php echo $this->__('Compatible Cartridges'); ?></h1>
                    <?php if(count($compatibleCartridges) > 0): ?>
                        <ul>
                            <?php foreach ($compatibleCartridges as $printerModel): ?>
                                <li><a><?php echo $printerModel ?></a></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php else: ?>
                        <?php echo $this->__('No Compatible Cartridges Found.'); ?>
                    <?php endif; ?>
                </div>

            </div>
            <?php endif; ?>
		 
		 
	        <script type="text/javascript">

	            var relProductAddToCartForm = new VarienForm('rel_product_addtocart_form');
            relProductAddToCartForm.submit = function(button, url) {

            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;
 
                if (url) {
                   form.action = url;
                }
                var e = null;
//Start of our new ajax code
                if(!url){
                    url = jQuery('#rel_product_addtocart_form').attr('action');
                }

                var data = jQuery('#rel_product_addtocart_form').serialize();
                data += '&isAjax=1';   
                jQuery('#loading-image').css('display','block');
                try {
                    jQuery.ajax({
                          url: url,
                          dataType: 'json',
                          type : 'post',
                          data: data,
                          success: function(data){
                                jQuery('#loading-image').css('display','none');
                              //alert("dd");
							jQuery('html, body').animate({scrollTop:jQuery('.col-main').offset().top-80},'slow');    
                           //jQuery('.add-to-cart').prepend('<div class="messages error">Product has been added to your shopping cart.</div>');
//                            jQuery(".add-to-cart ul").remove();
                            
                            if(data.status == 'SUCCESS')
                            {   
								jQuery('.shoppingcart .cartgo').html(data.countqty);
								//jQuery('.cartminislider').html(data.sidebar);
							    jQuery('.col-main .messages').remove();
                            	jQuery('.col-main').prepend('<ul class="messages"><li class="success-msg"><ul><li><span>' + data.message + '</span></li></ul></li></ul>');
                            	jQuery('.header-minicart .skip-cart').remove();	
                            	if(jQuery('.block-cart')){
                                    jQuery('.block-cart').replaceWith(data.sidebar);
                                }
                                if(jQuery('.header .links')){
                                    jQuery('.header .links').replaceWith(data.toplink);
                                }
                                
								
                            }
    						if(data.status == 'ERROR')
							    jQuery('.col-main .messages').remove();
                            	jQuery('.main_grouped_product_detail').after('<ul class="messages"><li class="error-msg"><ul><li><span>' + data.message + '</span></li></ul></li></ul>');
					            //alert(data.status + ": " + data.message);
                          }
                    });
                } catch (e) {
                }
//End of our new ajax code
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }
            }
        }.bind(relProductAddToCartForm);
            //]]>
	        </script>
    </div>

</div>