<?php 
$evolvedmethod = new Ideal_Evolved_Block_Evolved();
if(method_exists($evolvedmethod, 'getBlockConfig'))
{
	if($evolvedmethod->getBlockConfig('evolved_homepage_testimonials'))
	{
		$theme = $evolvedmethod->getBlockConfig('evolved_homepage_testimonials');
	}
	else 
	{
		$theme = Mage::helper('evolved')->getThemeConfig();
	}
}
else
{
	$theme = Mage::helper('evolved')->getThemeConfig();
}
if(count($theme) == 0){ $theme = Mage::helper('evolved')->getThemeConfig(); }
?>
<?php //echo "<pre>"; print_r($theme); echo "</pre>"; ?>
<?php //echo $theme['testimonials_page_upload_banner']; ?>
<?php $testimonial=$this->getTestimonial(); ?>
<div class="customer-testimonials <?php if($theme['testimonials_element_style']=="testimonials_element_style_two_two_column_with_50_by_50"): ?> two-columns <?php else: ?> one-column <?php endif; ?>">
	<div <?php if($theme['testimonials_page_upload_banner']): ?> style="background: url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>./media/<?php echo $theme['testimonials_page_upload_banner']; ?>') no-repeat scroll center top / cover  rgba(0, 0, 0, 0);" <?php endif; ?> class="testimonialstitle">
   		<h1><?php echo $theme['testimonials_page_title']; ?></h1>
   		<h6><span><?php echo $theme['testimonials_page_sub_title']; ?></span></h6>
	</div>
	<div class="testimonial-main-content">
		<div class="page-title">
		<h1><?php echo $this->__('Customer Testimonials');?></h1>
        <?php if(Mage::getStoreConfig('testimonial/testimonial_options/allow_customers_write_testimonial') == 1):?>
		<div class="submit-testimonial">
				<button class="button" onclick="setLocation('<?php echo $this->getFormUrl(); ?>')">
					<span>
						<span>
							<?php echo $this->__('Submit Your Testimonial');?>					
						</span>
					</span>
				</button>
		</div>
        <?php endif ?>
    </div>
	<?php echo $this->getPagerHtml();?>
	<?php if ($testimonial->getSize()): ?>
		<?php $i==0; foreach ($testimonial as $obj):?>
			<?php if($obj->getStatus()==1): ?>
			<div class="customer-testimonials-content<?php if($i==0):?> first<?php endif;?> <?php if($i==(count($testimonial)-1)):?> last<?php endif;?> <?php if(($i%2)==0):?> <?php if($i==(count($testimonial)-1)):?> last-odd <?php endif;?> odd <? else: ?> <?php if($i==(count($testimonial)-2)):?> last-even <?php endif;?> even <?php endif; ?>" name="<?php echo $obj->getName(); ?>" id="<?php echo $obj->getName(); ?>">
			<div class="testimonial-content">
					<i class="fa fa-quote-left"></i>
                    <div class="testimonial-content-avatar">
                        <?php
                            if($obj->getAvatarName() != ''){
                                $avatarLink = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'magebuzz/avatar/'.$obj->getAvatarName();
                                ?><img src="<?php echo $avatarLink ?>" alt="test" height="120" width="120" /><?php
                            }
                        ?>
                    </div>
					<?php echo $obj->getTestimonial();?>
				</div>
				<div class="testimonial-source">
					<div class="testimonial-author"><?php echo $obj->getName(); ?></div>
					<div class="testimonial-address"><?php echo $obj->getAddress(); ?></div>
					<?php /* ?>
					<span class="testimonial-date">
						<?php echo date('F d, Y', Mage::getModel('core/date')->gmtTimestamp($obj->getCreatedTime())); ?>
					</span>
					<?php */ ?>
				</div>
			</div>
			<?php endif ?>
			<?php $i++; ?>
		<?php endforeach;?>
		<?php echo $this->getPagerHtml(); ?>
	<?php else: ?>
		<p class="note-msg"><?php echo $this->__('There is no testimonial submitted.'); ?></p>
	<?php endif ?>
	</div>
</div>

