<style type="text/css">
.custombuttons td { padding: 5px 2px; }
</style>
<table class="custombuttons">
	<tr>
		<td>
			<button onclick="setLocation('<?php echo $this->getUrl('adminhtml/jewelryshare/getImportCSV', array('_current'=>true)); ?>')" class="scalable save" type="button" title="Get Import CSV">
				<span><span><span>Get Import CSV</span></span></span>
			</button>
		</td>
		<td>
			<button onclick="setLocation('<?php echo $this->getUrl('adminhtml/jewelryshare/getImages', array('_current'=>true)); ?>')" class="scalable save" type="button" title="Get Images">
				<span><span><span>Get Images</span></span></span>
			</button>
		</td>
		<td>
			<button onclick="window.open('<?php echo $this->getUrl('adminhtml/jewelryshare/importJewelry', array('_current'=>true)); ?>')" class="scalable save" type="button" title="Import Products">
				<span><span><span>Import Products</span></span></span>
			</button>
		</td>
		<td>
			<button onclick="setLocation('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'var/import/jewelerslink_import.csv'; ?>')" class="scalable save" type="button" title="Download Update CSV">
				<span><span><span>Download Import CSV</span></span></span>
			</button>
		</td>
	</tr>
</table>