<?php $user = Mage::getSingleton('admin/session')->getUser(); ?>
<?php 
$created_at = Mage::getStoreConfig('general/livechatadmin/created_at');
$epoch = strtotime($created_at);
$companyName = Mage::getStoreConfig('general/store_information/name');
$companyID = Mage::getStoreConfig('general/livechatadmin/company_id');
//echo $epoch; exit; 
?>
<script>
  window.intercomSettings = {
    app_id: "luy97a73",
    name: "<?php echo $user->getFirstname() . ' ' .$user->getLastname() ?>", // Full name
    email: "<?php echo $user->getEmail() ?>", // Email address
    created_at: <?php echo $epoch; ?>, // Signup date as a Unix timestamp
    company: {
        id: '<?php echo $companyID; ?>',
        name: '<?php echo $companyName; ?>',
        created_at: '<?php echo $epoch; ?>', 
      }
  };
</script>
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/luy97a73';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script>