<?php $_order = $this->getOrder(); ?>
<?php if ($_order != null && $_order->getId() != null) : ?>
<script type="text/javascript">
    var ORDER_ID = <?php echo $_order->getId(); ?>;
</script>

<?php
$orderAdminDate = $this->formatDate($_order->getCreatedAtDate(), 'medium', true);
$orderStoreDate = $this->formatDate($_order->getCreatedAtStoreDate(), 'medium', true);


$invoice_id = Mage::app()->getRequest()->getParam('invoice_id', null);
$shipment_id = Mage::app()->getRequest()->getParam('shipment_id', null);
$creditmemo_id = Mage::app()->getRequest()->getParam('creditmemo_id', null);
?>


<div class="box-left order-info">
    <!--Order Information-->
    <div class="entry-edit">
        <?php if ($_order->getEmailSent()):
            $_email = Mage::helper('sales')->__('the order confirmation email was sent');
        else:
            $_email = Mage::helper('sales')->__('the order confirmation email is not sent');
        endif; ?>
        <div class="entry-edit-head order-edit">
            <?php if ($this->getNoUseOrderLink()): ?>
                <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Order #%s', $_order->getRealOrderId()) ?>
                    (<?php echo $_email ?>)</h4>
            <?php else: ?>
                <a href="<?php echo $this->getViewUrl($_order->getId()) ?>"><?php echo Mage::helper('sales')->__('Order #%s', $_order->getRealOrderId()) ?></a>
                <strong>(<?php echo $_email ?>)</strong>
            <?php endif; ?>

            <div class="tools" style="float:right">
                <?php $is_allow = Mage::getSingleton('admin/session')->isAllowed('iwd_ordermanager/order/actions/edit_order_information'); ?>
                <?php if($is_allow): ?>
                    <a id="order_information_edit_<?php echo $_order->getEntityId(); ?>"
                       class="order_information_edit" href="#"
                       <?php if(!empty($invoice_id)): ?>data-invoice-id="<?php echo $invoice_id; ?>"<?php endif; ?>
                       <?php if(!empty($shipment_id)): ?>data-shipping-id="<?php echo $shipment_id; ?>"<?php endif; ?>
                       <?php if(!empty($creditmemo_id)): ?>data-creditmemo-id="<?php echo $creditmemo_id; ?>"<?php endif; ?>
                       title="<?php echo Mage::helper('sales')->__('Edit order information'); ?>">
                        <?php echo Mage::helper('sales')->__('Edit'); ?></a>
                <?php endif; ?>
            </div>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list" id="order_information">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date') ?></label></td>
                    <td class="value"><strong><?php echo $orderAdminDate ?></strong></td>
                </tr>
                <?php if ($orderAdminDate != $orderStoreDate): ?>
                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('sales')->__('Order Date (%s)', $_order->getCreatedAtStoreDate()->getTimezone()) ?></label>
                        </td>
                        <td class="value"><strong><?php echo $orderStoreDate ?></strong></td>
                    </tr>
                <?php endif; ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Order Status') ?></label></td>
                    <td class="value"><strong><span
                                    id="order_status"><?php echo $_order->getStatusLabel() ?></span></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Purchased From') ?></label></td>
                    <td class="value"><strong><?php echo $this->getOrderStoreName() ?></strong></td>
                </tr>
                <?php if ($_order->getRelationChildId()): ?>
                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('sales')->__('Link to the New Order') ?></label></td>
                        <td class="value"><a href="<?php echo $this->getViewUrl($_order->getRelationChildId()) ?>">
                                <?php echo $_order->getRelationChildRealId() ?>
                            </a></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRelationParentId()): ?>
                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('sales')->__('Link to the Previous Order') ?></label></td>
                        <td class="value"><a href="<?php echo $this->getViewUrl($_order->getRelationParentId()) ?>">
                                <?php echo $_order->getRelationParentRealId() ?>
                            </a></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRemoteIp()): /*&& $this->shouldDisplayCustomerIp()):*/ ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('sales')->__('Placed from IP') ?></label></td>
                        <td class="value"><strong><?php echo $_order->getRemoteIp();
                                echo ($_order->getXForwardedFor()) ? ' (' . $this->escapeHtml($_order->getXForwardedFor()) . ')' : ''; ?></strong>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getGlobalCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label>
                        </td>
                        <td class="value"><strong><?php echo $_order->getBaseToGlobalRate() ?></strong></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getOrderCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label>
                        </td>
                        <td class="value"><strong><?php echo $_order->getBaseToOrderRate() ?></strong></td>
                    </tr>
                <?php endif; ?>

                <?php if (Mage::helper('iwd_ordermanager')->isAllowHideOrders() && $_order->getIwdOmStatus() == 1): ?>
                    <tr>
                        <td class="label">
                            <label><strong style="color:#e22b00!important"><?php echo Mage::helper('sales')->__('Hide On Front') ?></strong></label>
                        </td>
                        <td class="value">
                            <strong style="color:#e22b00!important">
                                <?php echo Mage::helper('sales')->__('This order is hidden in customer account on front') ?><br>
                                <a id="order_information_edit_<?php echo $_order->getEntityId(); ?>"
                                   class="order_information_edit" href="#"
                                   <?php if(!empty($invoice_id)): ?>data-invoice-id="<?php echo $invoice_id; ?>"<?php endif; ?>
                                   <?php if(!empty($shipment_id)): ?>data-shipping-id="<?php echo $shipment_id; ?>"<?php endif; ?>
                                   <?php if(!empty($creditmemo_id)): ?>data-creditmemo-id="<?php echo $creditmemo_id; ?>"<?php endif; ?>
                                   title="<?php echo Mage::helper('sales')->__('Enable this order '); ?>">
                                    <?php echo Mage::helper('sales')->__('Enable this order '); ?></a>
                            </strong>
                        </td>
                    </tr>
                <?php endif; ?>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Account Information-->
    <div class="entry-edit">

        <div class="entry-edit-head order-account">
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Account Information') ?></h4>

            <div class="tools" style="float:right">
                <?php $is_allow = Mage::getSingleton('admin/session')->isAllowed('iwd_ordermanager/order/actions/edit_account_information'); ?>
                <?php if ($is_allow): ?>
                    <a id="account_information_edit_<?php echo $_order->getEntityId(); ?>"
                       class="account_information_edit" href="#"
                       title="<?php echo Mage::helper('sales')->__('Edit account information for order only'); ?>">
                        <?php echo Mage::helper('sales')->__('Edit'); ?></a>
                <?php endif; ?>
            </div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <div class="hor-scroll" id="account_information_<?php echo $_order->getEntityId(); ?>">
                    <table cellspacing="0" class="form-list">
                        <tr>
                            <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Name') ?></label></td>
                            <td class="value">
                                <?php if ($_customerUrl = $this->getCustomerViewUrl()) : ?>
                                    <a href="<?php echo $_customerUrl ?>"
                                       target="_blank"><strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong></a>
                                <?php else: ?>
                                    <strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label><?php echo Mage::helper('sales')->__('Email') ?></label></td>
                            <td class="value"><a
                                        href="mailto:<?php echo $_order->getCustomerEmail() ?>"><strong><?php echo $_order->getCustomerEmail() ?></strong></a>
                            </td>
                        </tr>
                        <?php if ($_groupName = $this->getCustomerGroupName()) : ?>
                            <tr>
                                <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Group') ?></label>
                                </td>
                                <td class="value"><strong><?php echo $_groupName ?></strong></td>
                            </tr>
                        <?php endif; ?>
                        <?php foreach ($this->getCustomerAccountData() as $data): ?>
                            <tr>
                                <td class="label"><label><?php echo $data['label'] ?></label></td>
                                <td class="value"><strong><?php echo $data['value'] ?></strong></td>
                            </tr>
                        <?php endforeach; ?>

                        <?php if(Mage::app()->getRequest()->getActionName() == 'view'): ?>
                            <?php if(Mage::getConfig()->getModuleConfig('IWD_OnepageCheckoutSignature')->is('active', 'true')): ?>
                                <tr class="signature_block">
                                    <?php echo $this->getChildHtml('opcsignature.signature');?>
                                </tr>
                            <?php endif; ?>
                        <?php endif; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>

<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <div class="hor-scroll">
            <div class="entry-edit-head billing-address">
                <h4 class="icon-head head-billing-address"><?php echo Mage::helper('sales')->__('Billing Address') ?></h4>

                <div class="tools" style="float:right">
                    <?php $is_allow = Mage::getModel('iwd_ordermanager/address')->isAllowEditAddress(); ?>
                    <?php if ($is_allow): ?>
                        <a id="billing_address_edit_<?php echo $_order->getBillingAddress()->getId() ?>"
                           class="order_address_edit" href="#"
                           title="<?php echo Mage::helper('sales')->__('Edit billing address for order only'); ?>">
                            <?php echo Mage::helper('sales')->__('Edit'); ?></a>
                    <?php endif; ?>
                </div>
            </div>
            <fieldset>
                <address id="order_address_<?php echo $_order->getBillingAddress()->getId() ?>"><?php echo $_order->getBillingAddress()->getFormated(true) ?></address>
            </fieldset>
        </div>
    </div>
</div>
<?php if (!$this->getOrder()->getIsVirtual()): ?>
    <div class="box-right">
        <!--Shipping Address-->
        <div class="hor-scroll">
            <div class="entry-edit">
                <div class="entry-edit-head order-shipping">
                    <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('sales')->__('Shipping Address') ?></h4>
                    <div class="tools" style="float:right">
                        <?php if ($is_allow): ?>
                            <a id="shipping_address_edit_<?php echo $_order->getShippingAddress()->getId() ?>"
                               class="order_address_edit" href="#"
                               title="<?php echo Mage::helper('sales')->__('Edit shipping address for order only') ?>">
                                <?php echo Mage::helper('sales')->__('Edit'); ?>
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
                <fieldset>
                    <address id="order_address_<?php echo $_order->getShippingAddress()->getId() ?>"><?php echo $_order->getShippingAddress()->getFormated(true) ?></address>
                </fieldset>
            </div>
        </div>
    </div>
    <div class="clear"></div>
<?php endif; ?>
<?php endif; ?>