<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('videogallery'); ?>/css/stickyfooter.css" />
<div id="trainingstickyfooter">
	<div class="title">
		<span>show me how</span>
	</div>
	<div class="content" style="display:none; ">
		<div class="contentdescription">
			<p id="welcome" class="description">
				<strong>Welcome!!</strong>
				<span class="sub-description">to be successful its important you make the most of your websites tools, we have created some handy tutorials to get you started...</span>
			</p>
			<p id="invoice" class="description">
				<a href="javascript:" class="footerticket">
					<span class="sub-description"><span class="updata">create a</span><span class="downdata">ticket</span></span>
				</a>
			</p>
			<p id="user" class="description">
				<a href="<?php echo Mage::getBaseUrl()?>knowledgebase/adminhtml_knowledgebase/knowledgebase/">
					<span class="sub-description"><span class="updata">read an article in the</span><span class="downdata">knowledge base</span></span>
				</a>
			</p>
			<!-- <p id="payment" class="description">
				<span class="sub-description">receive payments</span>
			</p> -->
			<p id="media" class="description">
				<a href="<?php echo Mage::getBaseUrl()?>videogallery/adminhtml_videogallery">
					<span class="sub-description"><span class="updata">watch a quick</span><span class="downdata">training video</span></span>
					<!-- <span class="sub-description">centers <br />and lists<span class="time">2:20</span></span>  -->
				</a>
			</p>
		</div>
	</div>
</div>
<script>
jQuery(window).load(function(){
	jQuery("#trainingstickyfooter .title").click(function(){
		jQuery("#trainingstickyfooter .content").slideToggle();
	});
	jQuery(".footerticket").click(function(){
		jQuery(".inline2").click();
	});
});
</script>