<?php /* ?> $menuContent = Mage::helper('custommenu')->getMenuContent(); ?>
<script type="text/javascript">
//<![CDATA[
$('custommenu').update(<?php echo Zend_Json::encode($menuContent); ?>);
//]]>
</script>
<?php $mobileMenuContent = Mage::helper('custommenu')->getMobileMenuContent(); ?>
<script type="text/javascript">
//<![CDATA[
$('menu-content').update(<?php echo Zend_Json::encode($mobileMenuContent); ?>);
//]]>
</script>
<?php */ ?>