<?php
$bannerCollection = $this->getBrandCollection();
?>
<table width="100%" border="0" cellpadding="0" cellspacing="0" class="clientlist">

<?php $i = 0; foreach ($bannerCollection as $banner): ?>
<?php if(($i==0) || ($i%4 == 0)){ ?>
<tr class="<?php echo ($i==0)? "first" : ""; ?>">
<?php } ?>
<td valign="middle" width="25%" align="center" class="<?php if(($i==0) || ($i%4 == 0)){ echo "first"; } ?>">
	<a target="_blank" href="<?php echo $banner['weblink'];?>">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>" title="<?php echo $banner['title']?>" alt="<?php echo $banner['title']?>" align="middle"/>
	</a>
</td>	
<?php $i++ ;?>
<?php if(($i==0) || ($i%4 == 0)){ ?>
</tr>
<?php } ?>
<?php endforeach; ?>
</table>
