<script type="text/javascript">
    var order = new AdminOrder(<?php echo $this->getOrderDataJson() ?>);
    order.setLoadBaseUrl('<?php echo $this->getLoadBlockUrl() ?>');
    var payment = {};
    payment.switchMethod = order.switchPaymentMethod.bind(order);

    Event.observe(window, "load", function(){
        order.addCancelButtonToCustomerGrid();
        order.setDefaultStoreView(<?php echo $this->getDefaultStoreView() ?>);
    });
</script>
<form id="edit_form" action="<?php echo $this->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey')?>
    <div id="order-message">
        <?php echo $this->getChildHtml('message') ?>
    </div>

    <div id="order-top-actions">
        <?php echo $this->getChildHtml('top_actions', false) ?>
    </div>

    <div id="order-customer-selector" style="display:none">
        <?php echo $this->getChildHtml('customer') ?>
    </div>

    <div id="order-data">
        <?php echo $this->getChildHtml('data') ?>
    </div>
</form>
