<div class="top-actions switcher">
    <label for="currency_switcher"><?php echo Mage::helper('sales')->__('Order Currency:') ?></label>
    <select id="currency_switcher" name="order[currency]" onchange="order.setCurrencyId(this.value); order.setCurrencySymbol(this.options[this.selectedIndex].getAttribute('symbol'));">
        <?php foreach ($this->getAvailableCurrencies() as $_code): ?>
            <option value="<?php echo $_code ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?> symbol="<?php echo $this->getCurrencySymbol($_code) ?>"><?php echo $this->getCurrencyName($_code) ?></option>
        <?php endforeach; ?>
    </select>

    <?php echo $this->getChildHtml('store.switcher') ?>

    <div class="top-actions-buttons">
        <button class="scalable add show-customer-grid" type="button" onclick="order.showCustomersGrid()"><span><?php echo Mage::helper('iwd_ordermanager')->__('Add Customer') ?></span></button>
    </div>
</div>
<script type="text/javascript">
    order.setCurrencySymbol('<?php echo $this->getCurrencySymbol($this->getCurrentCurrencyCode()) ?>');
    if(order.customerId != false){
        $$('button.show-customer-grid span')[0].update('Change Customer');
    }
</script>