<?php

$rule = $this->getRuleModel();

?>

<div class="coupon_container">
    <div class="coupon_name">
        <span><?php echo $rule->getName(); ?></span>
    </div>
    <div class="coupon_description">
        <span><?php echo $rule->getDescription(); ?></span>
    </div>
    <div class="coupon_code">
        <span class="coupon_code_prefix">Use Code: </span><span class="coupon_code_value"><?php echo $rule->getCouponCode(); ?></span>
    </div>
</div>

<script>
    jQuery('.coupon_container').insertAfter('#header');
    jQuery('.coupon_container').css('display', 'block');
</script>

<style>
    .coupon_container {
        color: #000000;
        margin: 30px auto 0 auto;
        background-color: #fff5fd;
        border: 2px solid #e82e94;
        display: none;
        font-size: 28px;
        font-weight: 300;
        max-width: 1230px;
        width: 100%;
        height: 68px;
        vertical-align: middle;
    }
    .coupon_container .coupon_name {
        height: 100%;
        float: left;
        width: 30%;
        text-align: center;
        font-size: 24px;
    }
    .coupon_container .coupon_name span {
        line-height: 65px;
    }
    .coupon_container .coupon_description {
        height: 100%;
        float: left;
        width: 40%;
        text-align: center;
        font-size: 18px;
    }
    .coupon_container .coupon_description span {
        line-height: 65px;
    }
    .coupon_container .coupon_code {
        font-size: 18px;
        line-height: 65px;
        height: 100%;
        float: right;
        text-align: center;
    }
    .coupon_container .coupon_code:before {
        content: '';
        background-image: url('<?php echo $this->getSkinUrl('images/idealcoupon/header_scissors.png') ?>');
        display: block;
        width: 14px;
        height: 68px;
        background-repeat: no-repeat;
        float: left;
        margin-right: 25px;
    }
    .coupon_container .coupon_code .coupon_code_value {
        margin-right: 40px;
        font-weight: 600;
    }
</style>