hiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
<style type="text/css">
#certother{display:none;}
</style>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery("#certif").change(function(){
		var v=jQuery("#certif").val();
		if(v=='Yes')
		{
			
			jQuery("#certother").hide();
			jQuery("#certiftype").show();
		}
		else
		{
			
			jQuery("#certiftype").hide();;
			jQuery("#certother").show();
		}
		});
	});
jQuery(function() {
	jQuery('#defaultReal').realperson();
});
</script>

<div class="page-title">
<h1>SELL YOUR DIAMOND</h1>
</div>
<div class="std">
<p class="ldt">If you are looking to sell your diamonds, we can help. Please describe the stone you are currently selling, and we will contact you. Please try to answer the questions below as best as you can.</p>
<form id="simple_contact_form" name="simple_contact_form" action="<?php echo Mage::getBaseUrl();?>selldiamond/index/sendemail/" method="post">
    <div class="fieldset">
       <ul class="form-list">
       <div class="find_diamond_left">
         <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('NAME') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                </li>
                <li>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('EMAIL') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>
            
            <li>
                <label for="telephone" class="required"><?php echo Mage::helper('contacts')->__('PRIMARY PHONE NUMBER') ?></label>
                <div class="input-box">
                    <input name="phone1" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text required-entry" type="text" />
                </div>
            </li>
            <li>
                <label for="telephone"><?php echo Mage::helper('contacts')->__('SECONDARY PHONE NUMBER') ?></label>
                <div class="input-box">
                    <input name="phone2" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
                </div>
            </li>
            <li>
                <label for="contacttime"><?php echo Mage::helper('contacts')->__('BEST TIME OF DAY TO CONTACT YOU') ?></label>
                <div class="input-box">
                    <input name="contact_time" id="contact_time" title="<?php echo Mage::helper('contacts')->__('contact_time') ?>" value="" class="input-text" type="text" />
                </div>
            </li>
            </div>
            <div class="find_diamond_right">
           <!-- <li><h2 style="margin-bottom:0px;">Diamond Details</h2></li>-->
            <li class="fields">
                <div class="field">
            	<label class="label">SHAPE</label>
                <div class="input-box">
            	<select class="shape" name="shape" id="shape">
                	<option value="ALL">ALL</option>
                    <option value="Round Brilliant">Round Brilliant</option>
                    <option value="Princess">Princess</option>
                    <option value="Emerald">Emerald</option>
                    <option value="Radiant">Radiant</option>
                    <option value="Pear">Pear</option>
                    <option value="Marquise">Marquise</option>
                    <option value="Heart">Heart</option>
                    <option value="Oval">Oval</option>
                    <option value="Trillion">Trillion</option>
                    <option value="Cushion">Cushion</option>                    
                </select>
                </div>
            </div>
            </li>
            <li class="fields">
                <div class="field">
            	<label class="label">WEIGHT</label>        
            	<div class="input-box">
                    <div style="float:left;width:245px;"><input name="weight" id="weight" title="<?php echo Mage::helper('contacts')->__('weight') ?>" value="" class="input-text required-entry" type="text" /></div>
                </div>        
               
            </div>
            </li>
            <li class="fields">
                <div class="field">
            	<label class="label">ASKING PRICE</label>
                <div class="input-box">
                    <div style="float:left;width:10px;">$</div><div style="float:left;width:245px;"><input name="price" id="price" title="<?php echo Mage::helper('contacts')->__('price') ?>" value="" class="input-text required-entry" type="text" /></div>
                </div>
           </li>     <li class="fields">
                <div class="field">
            	<label class="label">CERTIFICATION</label>
                
                <div class="input-box"> 
                <select class="shape tofrom" name="certification" id="certif">
                	<option value="Not Sure">Not Sure</option>
                    <option value="Yes" selected="selected">Yes</option>
                    <option value="No">No</option> 
                    </select>
                    </div>
                    </div>
                    </li>
                    
                    <li class="fields" style="float: left;margin-bottom: 40px;margin-top: 18px;">
                		<div class="field">
                    <label class="label">TYPE</label>
                     <div class="input-box"> 
                    <select class="shape tofrom" name="certificationtype" id="certiftype">
                	<option value="GIA">GIA</option>
                    <option value="EGL">EGL</option>
                    <option value="Other">Others</option> 
                    </select> <input name="certificationtype1" id="certother" title="" value="" class="input-text"  type="text" />
                 </div>
            </div>
            </li>
           <!--<li class="fields">
                <div class="field">
                <label class="label">COLOR</label>
                <div class="input-box">
            	<select name="color" class="shape" id="color">
                	<option selected="selected" value="no choice">Choose one</option><option selected="selected" value="1">D</option>
                    <option value="E">E</option>
                    <option value="F">F</option>
                    <option value="G">G</option>
                    <option value="H">H</option>
                    <option value="I">I</option>
                    <option value="J">J</option>
                    <option value="K">K</option>
                    <option value="L">L</option>
                    <option value="M">M</option>
                    <option value="N">N</option>
                    <option value="O">O</option>
                    <option value="P">P</option>
                </select>
                </div>
            </div>
            </li>
            <li class="fields">
                <div class="field">
                <label class="label">CLARITY</label>
                <div class="input-box">
                <label class="label">From:</label>
            	<select name="clarity_max" class="shape tofrom" id="clarity_max">
                	<option selected="selected" value="no choice">Choose one</option>
                    <option value="VS1">VS1</option>
                    <option value="VS2">VS2</option>
                    <option value="SI1">SI1</option>
                    <option value="SI2">SI2</option>
                    <option value="SI3">SI3</option>
                    <option value="I1">I1</option>  
                    <option value="I2">I2</option>
                </select>
                <label class="to">To:</label>
                <select name="clarity_min" class="shape" id="clarity_min">
                	<option selected="selected" value="no choice">Choose one</option>
                    <option value="VS1">VS1</option>
                    <option value="VS2">VS2</option>
                    <option value="SI1">SI1</option>
                    <option value="SI2">SI2</option>
                    <option value="SI3">SI3</option>
                    <option value="I1">I1</option>
                    <option value="I2">I2</option>
                </select>
                
                </div>
            </div>
            </li>-->
            <li class="wide">
                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('ADDITIONAL INFORMATION- <span>Please give us any additional information that will help us determine the value of your diamond. If you have a certificate, feel free to scan and email it to info@losangelesdiamondseller.com.<span>') ?></label>
                <div class="input-box">
                    <textarea name="content" id="content" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
            </div>
                </ul>
   
    <div class="buttons-set">
    <input type="text" id="defaultReal" name="defaultReal"></p>
        <p class="required">* Required Fields</p>
        <button class="button" type="submit"title="Submit" ><span><span>Submit</span></span></button>
    </div>
    </div>
</form>

</div>

<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('simple_contact_form', true);
//]]>
</script>