<?php
/**
 * LiteMage
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see https://opensource.org/licenses/GPL-3.0 .
 *
 * @package   LiteSpeed_LiteMage
 * @copyright  Copyright (c) 2016 LiteSpeed Technologies, Inc. (https://www.litespeedtech.com)
 * @license     https://opensource.org/licenses/GPL-3.0
 */

if ($this->canShowButton()):
	if ($catsaveurl = $this->getCategoryPurgeUrl()) :
	//$lmhelper = Mage::helper('litemage/data');
?>
<br/>
<script type="text/javascript">
//<![CDATA[	
function lmcategoryPurge(useoption) {
	updateContent("<?php echo $catsaveurl; ?>", {'useoption':useoption}, false);
}
function lmcategorySaveOption(sel) {
	updateContent("<?php echo $catsaveurl; ?>", {'saveoption':sel.value}, false);
}
//]]>
</script>
<div class="entry-edit">
	<ul class="messages">
<li class="notice-msg">
	LiteMage Cache: Clicking the "Save Category" Button Will 
<select name="litemage_catsaveoption" onchange="lmcategorySaveOption(this)">
	<?php echo $this->getCurrentCatSaveOptions(); ?>
</select>
<div class="form-buttons">
 <input type="button" onclick="lmcategoryPurge(1)" class="form-button" name="litemage_purgecat" value="Purge This Category" id="litemage_purgecat" /> 
 <input type="button" onclick="lmcategoryPurge(2)" class="form-button" name="litemage_purgecats" value="Purge with Selected Options" id="litemage_purgepcats" />
</div>	
</li>
</ul></div>

<?php 
endif;
endif;
?>
