<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.16
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php foreach ($posts as $post): ?>
	<?php //echo "<pre>";print_r($post);echo "</pre>";?>
    <div class="postWrapper">
        <div class="postTitle">
            <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
            <div class="postBy">
				<?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?>
                <?php $postCats = $post->getCats(); ?>
				<?php if (!empty($postCats)): ?>
                    <?php echo Mage::helper('blog')->__('Posted in'); ?>
                    <?php foreach ($postCats as $data): ?>
                        <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a> 
                    <?php endforeach; ?>
                <?php else: ?>
                    <?php echo Mage::helper('blog')->__('Posted'); ?>
                <?php endif; ?>                	            	          
            </div>
            <div class="date"><?php echo date("F d, Y", strtotime($post->getCreatedTime()));?></div>
        </div>
        <?php if( $post->getFeaturedImage()): ?>
        	<div class="featuredimage"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$post->getFeaturedImage();?>"></div>
		<?php endif; ?>
		<div class="postcontantpart">
			<div class="post-right-bar">
				<div class="post-date">
					<div class="day"><?php echo date("d", strtotime($post->getCreatedTime()));?></div>
					<div class="month"><?php echo date("M", strtotime($post->getCreatedTime()));?></div>
				</div>
				<div class="post-buttons">
					<a class="button-continue-read" href="<?php echo $post->getAddress(); ?>">Continue reading</a>
                    <?php if ($this->getCommentsEnabled()): ?>
					<a class="button-read-comments" href="<?php echo $post->getAddress(); ?>#commentBox"><?php echo $post->getComments();?> Comments</a>
                    <?php endif; ?>
				</div>
			</div>
			<div class="shortcontent std"><?php echo $post->getShortContent(); ?>
				<a class="read-more" href="<?php echo $post->getAddress(); ?>">Read More</a>
			</div>
		</div>
        <?php echo $this->getBookmarkHtml($post) ?>
        <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
        <div class="clear bottom-border"></div>
    </div>
<?php endforeach; ?>
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>