<?php $theme = Ideal_Evolved_Block_Evolved::getConfig(); ?>
<p class="newp"><span class="title">Contacting us:</span><br/>If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us at:</p>
<?php echo $theme['cms_address_website_name']; ?><br />
<?php echo $theme['cms_address_website_url']; ?>
</p>
<p class="newp">
<?php echo $theme['cms_address_address_line_one']; ?>
 <br/>
<?php echo $theme['cms_address_address_line_two']; ?>
</p>
<p class="newp">
<?php echo $theme['cms_address_phone_no']; ?>
<br/>
<?php echo $theme['cms_address_email']; ?>
</p>