<!-- <script src="http://houstongoldexchange.com/catalog/view/javascript/bossthemes/jquery.smoothscroll.js" type="javascript"></script>
<script src="http://houstongoldexchange.com/catalog/view/javascript/bossthemes/getwidthbrowser.js" type="text/javascript"></script>
<script src="http://houstongoldexchange.com/catalog/view/javascript/bossthemes/jquery.appear.js" type="text/javascript"></script>
<script src="http://houstongoldexchange.com/catalog/view/javascript/bossthemes/jquery.jgrowl.js" type="text/javascript"></script>
<script src="http://houstongoldexchange.com/catalog/view/javascript/bossthemes/jquery.smoothscroll.js" type="text/javascript"></script>
<script src="http://houstongoldexchange.com/catalog/view/javascript/bossthemes/bootstrap-select.js" type="text/javascript"></script>
<link media="screen" rel="stylesheet" type="text/css" href="http://houstongoldexchange.com/catalog/view/javascript/jquery/owl-carousel/owl.transitions.css" />
 -->
<script type="text/javascript">
// Popup window code
function newPopup(url) {
	popupWindow = window.open(
		url,'popUpWindow','height=' + window.screen.availHeight + ',width=' + window.screen.availWidth + ',left=10,top=10,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no,status=yes')
}
</script>
<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2014 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php 
$theme = Mage::helper('evolved')->getThemeConfig();
$helper = Mage::helper('cms');
$processor = $helper->getPageTemplateProcessor();
$sortincreement = 1;
if($theme['footer_sort_column_1'])
{ 
	if($theme['footer_enabled_column_1'] == 1)
	{
		$html_arr[$theme['footer_sort_column_1']] = array(1=>$processor->filter($theme['footer_content_column_1']));
	}
}
else
{ 
	if($theme['footer_enabled_column_1'] == 1)
	{
		$empty_arr[$theme['footer_sort_column_1']] = array(1=>$processor->filter($theme['footer_content_column_1']));
	}
}

if($theme['footer_sort_column_2'])
{ 
	if($theme['footer_enabled_column_2'] == 1)
	{
		if($html_arr[$theme['footer_sort_column_2']])
		{
			$html_arr[$theme['footer_sort_column_2'].".".$sortincreement] = array(2=>$processor->filter($theme['footer_content_column_2']));
			$sortincreement++;
		}
		else
		{
			$html_arr[$theme['footer_sort_column_2']] = array(2=>$processor->filter($theme['footer_content_column_2']));
		}
	}
}
else
{ 
	if($theme['footer_enabled_column_2'] == 1)
	{
		$empty_arr[] = array(2=>$processor->filter($theme['footer_content_column_2']));
	}
}

if($theme['footer_sort_column_3'])
{ 
	if($theme['footer_enabled_column_3'] == 1)
	{	
		if($html_arr[$theme['footer_sort_column_3']])
		{
			$html_arr[$theme['footer_sort_column_3'].".".$sortincreement] = array(3=>$processor->filter($theme['footer_content_column_3']));
			$sortincreement++;
		}
		else
		{
			$html_arr[$theme['footer_sort_column_3']] = array(3=>$processor->filter($theme['footer_content_column_3']));
		}
	}
}
else
{ 
	if($theme['footer_enabled_column_3'] == 1)
	{
		$empty_arr[$theme['footer_sort_column_3']] = array(3=>$processor->filter($theme['footer_content_column_3']));
	}
}

if($theme['footer_sort_column_4'])
{ 
	if($theme['footer_enabled_column_4'] == 1)
	{
		if($html_arr[$theme['footer_sort_column_4']])
		{
			$html_arr[$theme['footer_sort_column_4'].".".$sortincreement] = array(4=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_social.phtml')->toHtml());
			$sortincreement++;
		}
		else
		{
			$html_arr[$theme['footer_sort_column_4']] = array(4=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_social.phtml')->toHtml());
		}
	}
	elseif($theme['footer_enabled_column_4'] == 2)
	{
		if($html_arr[$theme['footer_sort_column_4']])
		{
			$html_arr[$theme['footer_sort_column_4'].".".$sortincreement] = array(4=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_social_with_newsletter.phtml')->toHtml());
			$sortincreement++;
		}
		else
		{
			$html_arr[$theme['footer_sort_column_4']] = array(4=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_social_with_newsletter.phtml')->toHtml());
		}
	}
}
else
{ 
	if($theme['footer_enabled_column_4'] == 1)
	{
		$empty_arr[$theme['footer_sort_column_4']] = array(4=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_social.phtml')->toHtml());
	}
	elseif($theme['footer_enabled_column_4'] == 2)
	{
		$empty_arr[$theme['footer_sort_column_4']] = array(4=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_social_with_newsletter.phtml')->toHtml());
	}
}

if($theme['footer_sort_column_5'])
{ 
	if($theme['footer_enabled_column_5'] == 1)
	{
		//$html_arr[$theme['footer_sort_column_5']] = array(5=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_newsletter.phtml')->toHtml());
		if($html_arr[$theme['footer_sort_column_5']])
		{
			$html_arr[$theme['footer_sort_column_5'].".".$sortincreement] = array(5=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_newsletter.phtml')->toHtml());
			$sortincreement++;
		}
		else
		{
			$html_arr[$theme['footer_sort_column_5']] = array(5=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_newsletter.phtml')->toHtml());
		}
	}
	elseif($theme['footer_enabled_column_5'] == 2)
	{
		//$html_arr[$theme['footer_sort_column_5']] = array(5=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_newsletter.phtml')->toHtml());
		if($html_arr[$theme['footer_sort_column_5']])
		{
			$html_arr[$theme['footer_sort_column_5'].".".$sortincreement] = array(5=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_newsletter_with_social.phtml')->toHtml());
			$sortincreement++;
		}
		else
		{
			$html_arr[$theme['footer_sort_column_5']] = array(5=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_newsletter_with_social.phtml')->toHtml());
		}
	}
}
else
{ 
	if($theme['footer_enabled_column_5'] == 1)
	{
		$empty_arr[] = array(5=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_newsletter.phtml')->toHtml());
	}
	elseif($theme['footer_enabled_column_5'] == 2)
	{
		$empty_arr[] = array(5=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_newsletter_with_social.phtml')->toHtml());
	}
}

if($theme['footer_sort_column_6'])
{ 
	if($theme['footer_enabled_column_6'] == 1)
	{
		//$html_arr[$theme['footer_sort_column_6']] = array(6=>$processor->filter($theme['footer_content_column_6']));
		if($html_arr[$theme['footer_sort_column_6']])
		{
			$html_arr[$theme['footer_sort_column_6'].".".$sortincreement] = array(3=>$processor->filter($theme['footer_content_column_6']));
			$sortincreement++;
		}
		else
		{
			$html_arr[$theme['footer_sort_column_6']] = array(3=>$processor->filter($theme['footer_content_column_6']));
		}
	}
}
else
{ 
	if($theme['footer_enabled_column_6'] == 1)
	{
		$empty_arr[$theme['footer_sort_column_6']] = array(6=>$processor->filter($theme['footer_content_column_6']));
	}
}
/*
if($theme['footer_enabled_column_1'] == 1){$html_arr[$theme['footer_sort_column_1']] = array(1=>$processor->filter($theme['footer_content_column_1']));}
if($theme['footer_enabled_column_2'] == 1){$html_arr[$theme['footer_sort_column_2']] = array(2=>$processor->filter($theme['footer_content_column_2']));}
if($theme['footer_enabled_column_3'] == 1){$html_arr[$theme['footer_sort_column_3']] = array(3=>$processor->filter($theme['footer_content_column_3']));}
if($theme['footer_enabled_column_4'] == 1){$html_arr[$theme['footer_sort_column_4']] = array(4=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_social.phtml')->toHtml());}
if($theme['footer_enabled_column_5'] == 1){$html_arr[$theme['footer_sort_column_5']] = array(5=>Mage::app()->getLayout()->createBlock('core/template')->setTemplate('page/html/footer_newsletter.phtml')->toHtml());}
if($theme['footer_enabled_column_6'] == 1){$html_arr[$theme['footer_sort_column_6']] = array(6=>$processor->filter($theme['footer_content_column_6']));}
*/
/*
foreach($html_arr as $html_arr_key => $html_arr_value)
{
	echo "<br />".$html_arr_key;
	foreach($html_arr_value as $html_arr_value_key => $html_arr_value_value)
	{
		echo "<br />sort => ".$html_arr_key."   column => ".$html_arr_value_key;
		print_r($html_arr_value_value);
	}

}
exit;*/
ksort($html_arr);
/*xif(sizeof($empty_arr)!=0)
{
	$html_arr = array_merge($html_arr,$empty_arr);
}*/
if((sizeof($html_arr) != 0) && (sizeof($empty_arr) == 0))
{
	$html_arr = $html_arr;
}
else if((sizeof($html_arr) != 0) && (sizeof($empty_arr) != 0))
{
	$html_arr = array_merge($html_arr,$empty_arr);
}
else
{
	$html_arr = $empty_arr;
}

if($theme['footer_style_column'] && $theme['footer_style_column'] != "") {
	$footerClass = "footer_".$theme['footer_style_column']."_column";
} else {
	$footerClass = "footer_1_column";
}
//echo sizeof($empty_arr);
/*if(sizeof($empty_arr)!=0)
{
	$html_arr = array_merge($html_arr,$empty_arr);
}*/
//$html_arr = array_merge($html_arr,$empty_arr);
?>
<div class="footer-container notouch">
    <div class="footer <?php echo $footerClass; ?>">
    <?php $footercounter = 1;?>
	<?php foreach($html_arr as $html_arr_key=>$html_arr_value):	?>
			<?php foreach($html_arr_value as $html_arr_value_key => $html_arr_value_value): ?>
					<?php if($theme['footer_enabled_column_'.$html_arr_value_key] && $theme['footer_enabled_column_'.$html_arr_value_key] == 1): ?>
						<?php //echo $html_arr_value_key."<br />"; ?>
						<?php echo $html_arr_value_value; ?>
					<?php elseif($theme['footer_enabled_column_'.$html_arr_value_key] && $theme['footer_enabled_column_'.$html_arr_value_key] == 2): ?>
						<?php echo $html_arr_value_value; ?>
					<?php endif; ?>
			<?php endforeach; ?>
			
		<?php $footercounter++; ?>
	<?php endforeach; ?>
 	</div>
	  <div class="copyrights">
	    	<div class="copy_logo">
		        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('paymentlogo')->toHtml();?>
		        <address class="copyright">
		        	<?php 
		        		$copyright = str_replace('<YEAR>', date("Y"), $this->getCopyright());
		        		$copyright = str_replace('<STORE_NAME>', Mage::getStoreConfig('trans_email/ident_general/name'), $copyright); 
		        		echo $copyright;
		        	?>
		        </address>
		    </div>
	    </div>
 </div>
<!--  http://www.wix.com/support/html5/ugc/325e7df4-c917-45c4-98f1-5691a0d53b6d/305110ab-583f-454a-8b24-e72207f962c5  -->
 <!--Start of Zopim Live Chat Script-->
 <?php if($theme['livechat_enable'] == 1):?>
 		<?php //echo $processor->filter($theme['livechat_script']); ?>
 		 <?php echo $theme['livechat_script']; ?>
 <?php endif; ?>

<!--End of Zopim Live Chat Script-->