<?php 
//$theme = Mage::helper('evolved')->getThemeConfig();
$evolvedmethod = new Ideal_Evolved_Block_Evolved();
if(method_exists($evolvedmethod, 'getBlockConfig'))
{
	$evolved_form_contacts = $evolvedmethod->getBlockConfig('evolved_form_contacts');
	$evolved_form_contacts_schedule_an_appointment = $evolvedmethod->getBlockConfig('evolved_form_contacts_schedule_an_appointment');
	$theme = array_merge($evolved_form_contacts, $evolved_form_contacts_schedule_an_appointment);
}
if(count($theme) == 0){ $theme = Mage::helper('evolved')->getThemeConfig(); }

$helper = Mage::helper('cms');
$processor = $helper->getPageTemplateProcessor();
?>
<script type="text/javascript" src="<?php echo $this->getBaseUrl().'js/calendar/calendar.js'; ?>"></script>
	<script type="text/javascript" src="<?php echo $this->getBaseUrl().'js/calendar/calendar-setup.js'; ?>"></script>
	<link type="text/css" href="<?php echo $this->getBaseUrl().'js/calendar/calendar-win2k-1.css'; ?>" rel="stylesheet" ></link>
	<?php  $isenablecustomcontact = Mage::getStoreConfig('customcontactnew/contacts/enabled',Mage::app()->getStore()); ?>
	<div class="Contact_Main">
		<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
	<div class="Contact_map">
		<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact_map')->toHtml()?>
		<?php //echo $theme['contacts_content_address_map']; ?>
		<?php echo $processor->filter($theme['contacts_content_address_map']); ?>
	</div>	
		<?php /* ?><div class="page-title">    <h1><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1></div><?php */?>
	
		
		
		<div class="Contact_frm">
			<div class="contitlef">
				<span class="title">Contact Us</span>
				<p class="desccon"></p>
			</div>
			<?php /* <div class="contact_form_fields">
				<form action="<?php echo Mage::getBaseUrl().'contacts/index/post'; ?>" id="contactForm" method="post">
				
				     <div class="fieldset">
				        <div class="legended">
				        <h2 class="legend"><?php //echo Mage::helper('contacts')->__('Contact Ghost') ?>
				        <?php echo $theme['contacts_title']; ?></h2>
				        <!-- <img src="<?php //echo $this->getSkinUrl('images/text.jpg'); ?>" alt="motorsports" />  -->
				        </div>
						<div class="leftcontent">
				        <ul class="form-list">
				            <li>
				            		<div class="field">
				                    <label for="name" class="required name"><?php echo Mage::helper('contacts')->__('Name') ?></label>
				                    <div class="input-box">
				                        <input name="cname" id="cname" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
				                    </div>
				                </div>
				            </li>
							<li>
				            	<div class="field">
									<label for="telephone" class="make required"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
									<div class="input-box">
										<input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text required-entry" type="text" />
									</div>
				            	</div>
				            </li>
				            <li>
				            	<div class="field">
				                    <label for="email" class="required email"><?php echo Mage::helper('contacts')->__('Email') ?></label>
				                    <div class="input-box">
				                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
				                    </div>
				                </div>
				            </li>
							</ul>
				            <?php /* <li>
				            	<div class="field">
				                <label for="telephone" class="model"><?php echo Mage::helper('contacts')->__('Zip Code') ?></label>
				                <div class="input-box">
				                    <input name="zipcode" id="zipcode" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
				                </div>
				                </div>
				            </li> 
							</div>
				            <div class="rightcontent">
				            <div class="field">
				                <label for="comment" class="required"><?php echo Mage::helper('contacts')->__('Comments') ?></label>
				                <div class="input-box">
				                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="6"></textarea>
				                </div>
				                </div>
				            </div>
				            
							<div class="buttons-set">
								<!--<div class="input-box">
									<input type="text" id="defaultReal" name="defaultReal">
								</div>  -->
								<?php /*?><p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p><?php 
								<input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
								<button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
							</div>
				    </div> 
				    
				</form>
		 	</div> */ ?>
		 	<div class="Contct_Addrress">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('customcontact_new')->toHtml() ?> 
			</div>
			
		 	<?php /* <div class="Contct_Addrress  <?php if(!$isenablecustomcontact):?><?php echo "withoutshedule"; ?><?php endif;?>">
	            <?php if($isenablecustomcontact):?>
							<?php if($theme['schedule_an_appointment_enable']==1): ?>
								<div class="make-apointment">
									<a class='inline2' href="#inline_content2" >SCHEDULE AN APPOINTMENT</a>
								</div>
								<div style="display:none;">
								<div class="apoinmt-form" id="inline_content2" >
									<?php echo $this->getLayout()->createBlock('customcontactnew/customcontactnew')->setTemplate('customcontactnew/customcontactnew.phtml')->toHtml(); ?>
									<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('customcontact_new')->toHtml() ?> 
									</div>
								</div>
							<?php endif; ?>
		   		<?php endif;?>
		 		<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact_add')->toHtml(); ?>
		 		<?php //echo $theme['contacts_content_address']; ?>
		 		<?php //echo $processor->filter($theme['contacts_content_address']); ?>
		 	</div> */
			?>
		</div> 
		
	</div>
	<script type="text/javascript">
	//<![CDATA[
	    var contactForm = new VarienForm('contactForm', true);
	//]]>
	</script>
	<?php /*?><link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/calendar/default.css');  ?>" type="text/css">
	<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/colorbox.css');  ?>" />
	<script src="<?php echo $this->getSkinUrl('js/jquery.colorbox.js'); ?>"></script>
	<script type="text/javascript">
		<!--jQuery.noConflict()-->
		jQuery(document).ready(function(){
			jQuery(".inline2").colorbox({inline:true, width:"784", height:"381",scrolling:false});
		});
	</script><?php */?>
	<?php /*?><?php 
	  echo $this->getLayout()->createBlock('core/html_calendar')->setTemplate('page/js/calendar.phtml')->toHtml();
	?>
	<input type="text" name="date_to" id="date_to" value="" /> 
	<input type="text" name="date_from" id="date_from" value="" />
	<a href="#" id="yag">link</a>
	<a href="#" id="calender_id"><img src="<?php echo $this->getSkinUrl('images/calendar.jpg');?>" width="18" height="17"   alt=""/></a>
	<script type="text/javascript">// <![CDATA[
	Calendar.setup({
	    inputField : 'date_from',
	    ifFormat : '%m/%e/%y',
	    button : 'calender_id',
	    align : 'Bl',
	    singleClick : true
	});
	
	// ]]></script><?php */?>
	<style>
	.withoutshedule{ margin-top: 122px;}
	@media only screen and (max-width: 841px){.withoutshedule{ margin-top: 0;}}
	</style>
