<?php //$theme = $this->getConfig(); ?>
<?php 



$SQL="SELECT * FROM `evolved` WHERE `value` IS NOT NULL AND `type` IN ('homepage_element_5_show_textrow')";
$write = Mage::getSingleton('core/resource')->getConnection('core_write');
$results = $write->fetchAll($SQL);
$theme = array();

foreach($results as $row){
	$theme[$row['field']] = $row['value'];
}

if(count($theme) == 0) {
	$theme = Ideal_Evolved_Block_Evolved::getConfig();
}
/* if(Ideal_Evolved_Block_Evolved::getBlockConfig('evolved_homepage_element_five')['homepage_element_five_style'])
{
	$evolved_homepage_element_five_content = Ideal_Evolved_Block_Evolved::getBlockConfig(Ideal_Evolved_Block_Evolved::getBlockConfig('evolved_homepage_element_five')['homepage_element_five_style']);
	$theme = array_merge($evolved_homepage_element_five_content);	
}
else 
{
	$theme = $this->getConfig();
} */
?>
<?php 
$helper = Mage::helper('cms');
$processor = $helper->getPageTemplateProcessor();
?>

<?php if($theme['homepage_element_5_textrow_enabled'] == 1): ?>
	<div class="home-info homepage_element_5_textrow homepage_textrow" <?php if($theme['homepage_element_five_style_margintop']): ?> style="margin-top: <?php echo $theme['homepage_element_five_style_margintop']."px"; ?>" <?php endif; ?>>
    	<div class="textrow" id="homepage_element_5_textrow">
		<?php $html = $processor->filter($theme['homepage_element_5_textrow_style_image']); ?>
		<?php echo nl2br($html); ?>
        </div>
	</div>
<?php endif; ?>