<link rel="stylesheet" href="<?php echo $this->getSkinUrl('colorbox/colorbox.css') ?>" type="text/css" media="all"/>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('colorbox/jquery.colorbox.js') ?>" ></script>
<script>
			jQuery(document).ready(function(){
				jQuery(".iframe").colorbox({iframe:true, width:"700px", height:"450px"});
			});
</script>

<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/magiczoomplus.css'); ?>" type="text/css" media="screen"/>                
<script src="<?php echo $this->getSkinUrl('js/magiczoomplus.js') ?>" type="text/javascript"></script>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
		
	$_product->getImageLink();	

?>
<div class="product-image product-image-zoom">
    <div class="product-image-gallery">
        <?php
        
		$evolvedmethod = new Ideal_Evolved_Block_Evolved();
		if(method_exists($evolvedmethod, 'getBlockConfig'))
		{
	        $evolved_form_productdetails_zoom = $evolvedmethod->getBlockConfig('evolved_form_productdetails_zoom');
    	    $theme = array_merge($evolved_form_productdetails_zoom);
		}
		if(count($theme) == 0){ $theme = Mage::helper('evolved')->getThemeConfig(); }
		
		$disablezoom = $theme['productdetails_zoom_disabled'];
        $disableMobilezoom = $theme['productdetails_mobile_zoom_disabled'];
        $disableexpand = $theme['productdetails_zoom_expand_disabled'];
        $zoomwidth = $theme['productdetails_zoom_width'];
        $zoomheight = $theme['productdetails_zoom_height'];
        $zoomposition = $theme['productdetails_zoom_position'];
        $zoomalign = $theme['productdetails_zoom_align'];
        ?>
         <div class="desktopp">
		<?php
		
		$_img = '<a data-options="rightClick:true;" class="MagicZoomPlus MagicZoom desktop" id="Zoomer" rel="disable-zoom:'.$disablezoom.';show-title:'.'false'.';disable-expand:'.$disableexpand.';zoom-width:'.$zoomwidth.';zoom-height:'.$zoomheight.';disable-zoom:'.$disablezoom.';disable-align:'.$disablealign.';zoom-position:'.$zoomposition.'; selectors-effect: pounce; selectors-effect-speed: 600;" href="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'"><img  src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(800,800).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" /></a>';
		
		echo $_helper->productAttribute($_product, $_img, 'image');
		?>
        </div>
       <?php /*?> <div class="mobile">
        <?php
		$_img = '<a class="mobile" id="" href="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'"><img  src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(800,800).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" /></a>';
        echo $_helper->productAttribute($_product, $_img, 'image');  
    ?>
    </div><?php */?>
    </div>
</div>

<div class="more-views">
    <ul class="product-image-thumbs">
    <?php if (count($this->getGalleryImages()) > 1): ?>
    <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
        <?php
        if (($filterClass = $this->getGalleryFilterHelper()) && ($filterMethod = $this->getGalleryFilterMethod()) && !Mage::helper($filterClass)->$filterMethod($_product, $_image)):
            continue;
        endif;
        ?>
        <li>
           <?php /*?> <a class="thumb-link" href="#" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>" data-image-index="<?php echo $i; ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(80,89); ?>"
                     width="80" height="89" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
            </a><?php */?>
            <a rel="zoom-id: Zoomer;" rev="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize();?>" href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" title="<?php echo $_product->getName();?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(90); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"  width="90" height="90" /></a>
        </li>
    <?php $i++; endforeach; ?>
    <?php endif; ?>
    
    <?php if($_product->getVideo() != ""){?>
	    	  <?php 
	    	  	$url = parse_url(Mage::helper('core/url')->getCurrentUrl()); 
	    	  	$videourl = $_product->getVideo();
		     	if($url['scheme'] == 'https'){
		     		$videourl = str_replace("http://","https://",$videourl);
		     	}     		
     		  ?>
	   		  <li><a class='iframe' href="https://www.youtube.com/embed/<?php echo $videourl ?>"><img src="<?php echo $this->getSkinUrl('images/video-btn.png')?>" /></a></li> 
	 <?php } ?>
	 
    </ul>
</div>


<?php echo $this->getChildHtml('after'); ?>
<script type="text/javascript">
jQuery(document).ready(function() {

	if(jQuery(window).width() <= 770) {	
		
 		jQuery( "#Zoomer" ).attr({
				'rel':'disable-expand: true ;disable-zoom:true;disable-align:<?php echo $disablealign; ?>; selectors-effect: pounce; selectors-effect-speed: 600;',
		 });
			
			 MagicZoomPlus.refresh();		
	}
	
	jQuery(window).resize();
});        
</script>
