<?php
/**
 * @var $this Mage_Adminhtml_Block_Sales_Order_View_Items_Renderer_Default
 */
?>
<?php $item = $this->getItem() ?>
<?php $this->setPriceDataObject($item) ?>
<tr <?php if (!$this->canDisplayGiftmessage()): ?> class="border"<?php endif; ?>>
    <td>
        <?php
            if (Mage::helper('iwd_ordermanager')->isShowItemImage()) {
                try {
                    $image = (string)Mage::helper('iwd_ordermanager/image')->init($item->getProduct(), 'image')->resize(75);
                } catch (Exception $e) {
                    $image = Mage::getDesign()->getSkinUrl(Mage::helper('iwd_ordermanager/image')->getPlaceholder(), array('_area' => 'frontend'));
                }
            }
        ?>
        <img src="<?php echo $image ?>" class="order_item_image" />

        <?php if ($this->canDisplayContainer()): ?>
            <div id="<?php echo $this->getHtmlId() ?>" class="item-container">
        <?php endif; ?>
            <div class="item-text">
                <?php echo $this->getColumnHtml($item, 'name') ?>
            </div>
        <?php if ($this->canDisplayContainer()): ?>
            </div>
        <?php endif ?>
    </td>
    <?php if (Mage::helper('iwd_ordermanager')->isMultiInventoryEnable()): ?>
        <td class="a-left">
            <?php echo Mage::getBlockSingleton('iwd_ordermanager/adminhtml_sales_order_grid_renderer_inventory')->getStockMessageForOrderItem($item); ?>
        </td>
    <?php endif; ?>
    <td class="a-center"><?php echo $item->getStatus() ?></td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('original_price') ?></td>
    <td class="a-right">
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
            <span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales', $item->getStoreId())): ?>
                    <?php
                    echo $this->displayPrices(
                        $item->getBasePrice() + $item->getBaseWeeeTaxAppliedAmount() + $item->getBaseWeeeTaxDisposition(),
                        $item->getPrice() + $item->getWeeeTaxAppliedAmount() + $item->getWeeeTaxDisposition()
                    );
                    ?>
                <?php else: ?>
                    <?php echo $this->displayPrices($item->getBasePrice(), $item->getPrice()) ?>
                <?php endif; ?>


                <?php if (Mage::helper('weee')->getApplied($item)): ?>
                    <br/>
                    <?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales', $item->getStoreId())): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>
                                    : <?php echo $this->displayPrices($tax['base_amount'], $tax['amount']); ?></span>
                            <?php endforeach; ?>
                        </small>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales', $item->getStoreId())): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                            <span class="nobr"><small><?php echo $tax['title']; ?>
                                    : <?php echo $this->displayPrices($tax['base_amount_incl_tax'], $tax['amount_incl_tax']); ?></small></span>
                        <?php endforeach; ?>
                        <?php
                    elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales', $item->getStoreId())): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>
                                    : <?php echo $this->displayPrices($tax['base_amount_incl_tax'], $tax['amount_incl_tax']); ?></span>
                            <?php endforeach; ?>
                        </small>
                    <?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales', $item->getStoreId())): ?>
                        <br/>
                        <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br/>
                            <?php
                            echo $this->displayPrices(
                                $item->getBasePrice() + $item->getBaseWeeeTaxAppliedAmount() + $item->getBaseWeeeTaxDisposition(),
                                $item->getPrice() + $item->getWeeeTaxAppliedAmount() + $item->getWeeeTaxDisposition()
                            );
                            ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
            <br/>
        <?php endif; ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
            <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                <?php endif; ?>
                <?php $_incl = $this->helper('checkout')->getPriceInclTax($item); ?>
                <?php $_baseIncl = $this->helper('checkout')->getBasePriceInclTax($item); ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales', $item->getStoreId())): ?>
                    <?php echo $this->displayPrices($_baseIncl + $item->getBaseWeeeTaxAppliedAmount(), $_incl + $item->getWeeeTaxAppliedAmount()); ?>
                <?php else: ?>
                    <?php echo $this->displayPrices($_baseIncl - $item->getBaseWeeeTaxDisposition(), $_incl - $item->getWeeeTaxDisposition()) ?>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->getApplied($item)): ?>
                    <br/>
                    <?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales', $item->getStoreId())): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>
                                    : <?php echo $this->displayPrices($tax['base_amount'], $tax['amount']); ?></span>
                            <?php endforeach; ?>
                        </small>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales', $item->getStoreId())): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                            <span class="nobr"><small><?php echo $tax['title']; ?>
                                    : <?php echo $this->displayPrices($tax['base_amount_incl_tax'], $tax['amount_incl_tax']); ?></small></span>
                        <?php endforeach; ?>
                        <?php
                    elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales', $item->getStoreId())): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>
                                    : <?php echo $this->displayPrices($tax['base_amount_incl_tax'], $tax['amount_incl_tax']); ?></span>
                            <?php endforeach; ?>
                        </small>
                    <?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales', $item->getStoreId())): ?>
                        <br/>
                        <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>
                            :<br/> <?php echo $this->displayPrices($_baseIncl + $item->getBaseWeeeTaxAppliedAmount(), $_incl + $item->getWeeeTaxAppliedAmount()); ?></span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
        <?php endif; ?>

    </td>
    <td><?php echo $this->getColumnHtml($item, 'qty') ?></td>
    <td class="a-right">
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
            <span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales', $item->getStoreId())): ?>
                    <?php
                    echo $this->displayPrices(
                        $item->getBaseRowTotal() + $item->getBaseWeeeTaxAppliedRowAmount() + $item->getBaseWeeeTaxRowDisposition(),
                        $item->getRowTotal() + $item->getWeeeTaxAppliedRowAmount() + $item->getWeeeTaxRowDisposition()
                    );
                    ?>
                <?php else: ?>
                    <?php echo $this->displayPrices($item->getBaseRowTotal(), $item->getRowTotal()) ?>
                <?php endif; ?>


                <?php if (Mage::helper('weee')->getApplied($item)): ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales', $item->getStoreId())): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>
                                    : <?php echo $this->displayPrices($tax['base_row_amount'], $tax['row_amount']); ?></span>
                            <?php endforeach; ?>
                        </small>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales', $item->getStoreId())): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                            <span class="nobr"><small><?php echo $tax['title']; ?>
                                    : <?php echo $this->displayPrices($tax['base_row_amount_incl_tax'], $tax['row_amount_incl_tax']); ?></small></span>
                        <?php endforeach; ?>
                        <?php
                    elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales', $item->getStoreId())): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>
                                    : <?php echo $this->displayPrices($tax['base_row_amount_incl_tax'], $tax['row_amount_incl_tax']); ?></span>
                            <?php endforeach; ?>
                        </small>
                    <?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales', $item->getStoreId())): ?>
                        <br/>
                        <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br/>
                            <?php
                            echo $this->displayPrices(
                                $item->getBaseRowTotal() + $item->getBaseWeeeTaxAppliedRowAmount() + $item->getBaseWeeeTaxRowDisposition(),
                                $item->getRowTotal() + $item->getWeeeTaxAppliedRowAmount() + $item->getWeeeTaxRowDisposition()
                            );
                            ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
            <br/>
        <?php endif; ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
            <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                <?php endif; ?>
                <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($item); ?>
                <?php $_baseIncl = $this->helper('checkout')->getBaseSubtotalInclTax($item); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales', $item->getStoreId())): ?>
                    <?php echo $this->displayPrices($_baseIncl + $item->getBaseWeeeTaxAppliedRowAmount(), $_incl + $item->getWeeeTaxAppliedRowAmount()); ?>
                <?php else: ?>
                    <?php echo $this->displayPrices($_baseIncl - $item->getBaseWeeeTaxRowDisposition(), $_incl - $item->getWeeeTaxRowDisposition()) ?>
                <?php endif; ?>


                <?php if (Mage::helper('weee')->getApplied($item)): ?>

                    <br/>
                    <?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales', $item->getStoreId())): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>
                                    : <?php echo $this->displayPrices($tax['base_row_amount'], $tax['row_amount']); ?></span>
                            <?php endforeach; ?>
                        </small>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales', $item->getStoreId())): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                            <span class="nobr"><small><?php echo $tax['title']; ?>
                                    : <?php echo $this->displayPrices($tax['base_row_amount_incl_tax'], $tax['row_amount_incl_tax']); ?></small></span>
                        <?php endforeach; ?>
                        <?php
                    elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales', $item->getStoreId())): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>
                                    : <?php echo $this->displayPrices($tax['base_row_amount_incl_tax'], $tax['row_amount_incl_tax']); ?></span>
                            <?php endforeach; ?>
                        </small>
                    <?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales', $item->getStoreId())): ?>
                        <br/><span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>
                            :<br/> <?php echo $this->displayPrices($_baseIncl + $item->getBaseWeeeTaxAppliedRowAmount(), $_incl + $item->getWeeeTaxAppliedRowAmount()); ?></span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
        <?php endif; ?>
    </td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('tax_amount') ?></td>
    <td class="a-right"><?php echo $this->displayTaxPercent($item) ?></td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
    <td class="a-right">
        <?php echo $this->displayPrices(
            $item->getBaseRowTotal() + $item->getBaseTaxAmount() + $item->getBaseHiddenTaxAmount() + $item->getBaseWeeeTaxAppliedRowAmount() - $item->getBaseDiscountAmount(),
            $item->getRowTotal() + $item->getTaxAmount() + $item->getHiddenTaxAmount() + $item->getWeeeTaxAppliedRowAmount() - $item->getDiscountAmount()
        ); ?>
    </td>

    <?php if(Mage::getConfig()->getModuleConfig('IWD_Downloadable')->is('active', 'true')): ?>
        <td class="a-right"> <?php echo Mage::helper("iwd_ordermanager/downloadable")->getSupportPeriod($item); ?> </td>
        <td class="a-right last"> <?php echo Mage::helper("iwd_ordermanager/downloadable")->getCountOfDownloads($item); ?> </td>
    <?php endif; ?>
</tr>