<?php
    /**
     * @var $helper IWD_OrderManager_Helper_Data
     */
    $helper = Mage::helper("iwd_ordermanager");
    $buttonOnclickUpdate = $this->getData('button_onclick_update');
    $buttonOnclickCancel = $this->getData('button_onclick_cancel');
    $block = $this->getData('block');
    $recalculate = $this->getData('recalculate');
    $reauthorize = false;//$this->getData('reauthorize');
?>

<div class="iwd_om_control">
    <?php if(!empty($buttonOnclickCancel)): ?>
        <button class="scalable" type="button"
                onclick="<?php echo $buttonOnclickCancel; ?>"
                title="<?php echo Mage::helper('customer')->__("Cancel"); ?>">
            <?php echo Mage::helper('customer')->__("Cancel"); ?>
        </button>
    <?php endif; ?>
    <?php if(!empty($buttonOnclickUpdate)): ?>
        <button class="scalable right" type="button"
                onclick="<?php echo $buttonOnclickUpdate; ?>"
                title="<?php echo Mage::helper('customer')->__("Update"); ?>">
            <?php echo Mage::helper('customer')->__("Update"); ?>
        </button>
    <?php endif; ?>

    <div class="control_checkboxes">
        <label class="iwd_om_confirm">
            <input type="checkbox" name="confirm_edit" <?php echo $helper->isConfirmEditChecked(); ?>/>
            <span class="iwd_om_tooltip" title="<?php echo $helper->__('Select this option if you would like the customer to approve the order changes. Instead of applying changes immediately, customer will receive an email to confirm or cancel the changes.'); ?>">
                <span title=""><?php echo $helper->__('Confirm Edit'); ?></span>
            </span>
        </label>

        <span class="iwd_om_notify">
            <label>
                <input type="checkbox" name="notify" <?php echo $helper->isNotifyCustomerChecked(); ?>/>
                <span class="iwd_om_tooltip" title="<?php echo $helper->__('Select this option if you would like the customer to receive an email notifying them of changes made to their order.'); ?>">
                    <span title=""><?php echo $helper->__('Notify Customer'); ?></span>
                </span>
            </label>
            <span class="iwd_om_tooltip" title="<?php echo $helper->__('Customize email list and message.'); ?>">
                <span class="notify_customize" <?php if(!$helper->isNotifyCustomerCheckedDefault()): ?>style="display:none"<?php endif; ?> onclick="IWD.OrderManager.NotifyPopup.showModal('<?php echo $block; ?>');" title="">
                    [<?php echo Mage::helper('customer')->__("customize"); ?>]
                </span>
            </span>
        </span>

        <?php if($recalculate): ?>
            <label class="iwd_om_recalculate">
                <input type="checkbox" name="recalculate_amount" <?php echo $helper->isRecalculateOrderAmountChecked(); ?>/>
                <span class="iwd_om_tooltip" title="<?php echo $helper->__('Select this option to recalculate the order\'s total amount if edits increased or decreased the total amount.'); ?>">
                    <span title=""><?php echo $helper->__('Recalculate Order Amount'); ?></span>
                </span>
            </label>
        <?php endif; ?>

        <?php if($reauthorize): ?>
            <label class="iwd_om_reauthorize">
                <input type="checkbox" name="reauthorize_amount" <?php echo $helper->isRecalculateOrderAmountChecked(); ?>/>
                <span class="iwd_om_tooltip" title="<?php echo $helper->__('Select this option to reauthorize the order\'s total amount.'); ?>">
                    <span title=""><?php echo $helper->__('Re-authorize'); ?></span>
                </span>
            </label>
        <?php endif; ?>

        <div class="clear"></div>
    </div>

    <div style="display:none !important;" id="control_form_<?php echo $block; ?>"></div>

    <script type="text/javascript">
        //<![CDATA[
        $ji('input[name="notify"]').on('change', function(){
            if($ji(this).is(':checked')){$ji(this).closest(".iwd_om_notify").find('.notify_customize').show();}
            else{$ji(this).closest(".iwd_om_notify").find('.notify_customize').hide();}
        });
        //]]>
    </script>
</div>
<div class="clear"></div>
