<?php $theme = Ideal_Evolved_Block_Evolved::getConfig(); ?>
<?php //echo $theme['homepage_banner_enabled']; ?>
<?php if($theme['homepage_featured_enabled'] == 1): ?>
<div class="home-main feature_main">
<div class="sldr_blck">
 <div class="left">
  <a href="<?php echo $theme['homepage_featured_image_link']; ?>" >
 <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$theme['homepage_featured_image'] ?>" />
 </a>
 </div>
 <div class="right">

<?php
$theme = Ideal_Evolved_Block_Evolved::getConfig();
//echo "category : ".$theme['homepage_featured_category'];
$categoryId = $theme['homepage_featured_category']; // a category id that you can get from admin
$category = Mage::getModel('catalog/category')->load($categoryId);
$products = Mage::getModel('catalog/product')
    ->getCollection()
    ->addCategoryFilter($category)
    ->load();
?>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>fslider/demo.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>fslider/flexslider.css" type="text/css" media="screen" />
	 <!-- Syntax Highlighter -->
    <!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.min.js">\x3C/script>')</script>  -->
  <!-- FlexSlider -->
  <script defer src="<?php echo $this->getSkinUrl(); ?>fslider/jquery.flexslider.js"></script>
  <script defer src="<?php echo $this->getSkinUrl(); ?>fslider/demo.js"></script>
  
 <section class="slider">
    <div class="flexslider">
    	<h2 class="featuretitle">featured products</h2>
        <ul class="slides">
		<?php foreach($products as $products): ?>
		<?php $products = Mage::getModel('catalog/product')->load($products->getId()); ?>
            <li>
                <a class="product-image" title="<?php echo $products->getName(); ?>" href="<?php echo $products->getProductUrl(); ?>">
                                       
                                        <img src="<?php echo $this->helper('catalog/image')->init($products, 'small_image')->resize(365,335) ?>"
                </a>
                <div class="product-info" style="min-height: 138px;">
                    <h2 class="product-name"><a title="<?php echo $products->getName(); ?>" href="<?php echo $products->getProductUrl(); ?>"><?php echo $products->getName(); ?></a></h2>
					<div class="product-desc"><?php echo $products->getShortDescription(); ?></div>
				</div>
            </li>
			<?php endforeach; ?>
        </ul>
    </div>
</section>
<script type="text/javascript">
	/*jQuery(function(){
      SyntaxHighlighter.all();
    });*/
	jQuery(window).load(function(){
		jQuery('.flexslider').flexslider({
        animation: "slide",
        start: function(slider){
        	jQuery('body').removeClass('loading');
        }
      });
    });
  </script>
   </div>
</div>
</div>
<?php endif; ?>