<?php $theme = $this->getConfig(); ?>
<?php 
$helper = Mage::helper('cms');
$processor = $helper->getPageTemplateProcessor();
?>

<?php if($theme['homepage_element_1_textrow_enabled'] == 1): ?>
	<div class="home-info">
    	<div class="textrow">
		<?php $html = $processor->filter($theme['homepage_element_1_textrow_style_image']); ?>
		<?php echo nl2br($html); ?>
        </div>
	</div>
<?php endif; ?>