<?php $theme = Ideal_Evolved_Block_Evolved::getConfig(); 
$helper = Mage::helper('cms');
$processor = $helper->getPageTemplateProcessor();
?>

<?php $html_img_one = $processor->filter($theme['homepage_element_thirteen_style_image_one']); ?>

<div class="home-main">
<div class="page_element_thirteen">
	<div class="center">
		<a href="<?php echo $theme['homepage_element_thirteen_style_link_one']; ?>" title="<?php echo $theme['homepage_element_thirteen_style_title_one']; ?>" >	
			<?php echo nl2br($html_img_one); ?>
		</a>
	</div>
</div>
</div>
<?php //echo "<br />homepage_element_two_style_sortorder"; ?>
<?php //echo "<br />homepage_element_three_style_sortorder"; ?>
<?php //echo "<br />homepage_element_four_style_sortorder"; ?>