
<?php
 $theme = $this->getConfig();
// print_r($theme);
//exit;
?>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_main']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_title']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_price']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_footer_title']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_navigation']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_block_title']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_product_title']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_productdetails_price']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_product_name']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['contacts_title_font']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['contacts_content_font']) ?>' rel='stylesheet' type='text/css'>
<style>
.wrapper
{
	
	
	background-color:<?php echo $theme['general_main_color'] ?>;
}
.page-header
{
	
	height: <?php echo $theme['header_height']."px" ?>;	
	<?php if($theme['header_underline_color']): ?> border-bottom: 1px solid <?php echo $theme['header_underline_color'] ?>; <?php endif; ?>
	<?php if($theme['sticky_header_options'] == 'enable'): ?> 
		position: fixed; 
	<?php else: ?>
		position: relative;
	<?php endif; ?>
}
.main-container
{
	<?php if($theme['sticky_header_options'] == 'enable'): ?> 
		margin-top:<?php echo ($theme['header_height']-2)."px" ?>;
	<?php endif; ?>
}
.page-header-container
{
	height:<?php echo $theme['header_height']."px" ?>;
}
.product-name .h1,
{
	color:<?php echo $theme['general_title_color'] ?> !important;
	font-family:<?php echo "'".$theme['fonts_product_title']."'" ?> !important;
}
.product-name h1
{
	color:<?php //echo $theme['general_title_color'] ?> !important;
	font-family:<?php //echo "'".$theme['fonts_product_name']."'" ?> !important;
}
	
h1,
h2,
h3,
h4,
h5,
h6,
.page-title h1,
.page-title h2
{
	color:<?php //echo $theme['general_title_color'] ?>;
	font-family:<?php echo "'".$theme['fonts_title']."'" ?>;
}
.price-box .price, .price
{
	font-family:<?php echo "'".$theme['fonts_price']."'" ?> !important;
}
.product-view .price-box .price,.product-view .price
{
	font-family:<?php echo "'".$theme['fonts_productdetails_price']."'" ?> !important;
}
.price-box .regular-price .price
{
	color:<?php //echo $theme['general_price_color'] ?>;
}
.price-box .old-price .price
{
	color:<?php //echo $theme['general_oldprice_color'] ?>;
}
.price-box .old-price .price-label, .price-box .special-price .price-label
{
	color:<?php //echo $theme['general_pricetext_color'] ?>;
}
.price-box .special-price .price
{
	color:<?php //echo $theme['general_onsaleprice_color'] ?>;
}
.main-container .buttons-set a,
.main-container .buttons-set a span,
.main-container .buttons-set button span,
button span span
{
	color:<?php echo $theme['buttons_text_color'] ?>;
}
.skip-cart,
.skip-account
{
	background-color:<?php echo $theme['header_topbar_background_color'] ?>;
	color:<?php echo $theme['header_topbar_text_color'] ?>;
}
.skip-search .label,
.skip-search:hover .label
{
	color:<?php echo $theme['header_topbar_text_color'] ?>;
}
.skip-cart:hover,
.skip-account:hover
{
	color:<?php echo $theme['header_topbar_texthover_color'] ?>;
	background-color:<?php echo $theme['header_topbar_texthover_background_color'] ?>;
}
.main-container .buttons-set a,
.main-container .buttons-set button,
button
{
	background-color:<?php echo $theme['buttons_background_color'] ?>;
}
.main-container .buttons-set a:hover,
button:hover span span,
.main-container .buttons-set a:hover span,
.main-container .buttons-set button:hover span
{
	color:<?php echo $theme['buttons_texthover_color'] ?>;
}
.main-container .buttons-set a:hover,
.main-container .buttons-set button:hover,
button:hover
{
	background-color:<?php echo $theme['buttons_bghover_color'] ?>;
}
.button.btn-cart span span,
.btn-checkout span span,
.button2 span,
.button2 span span
{
	color:<?php echo $theme['buttons_addto_text_color'] ?> !important;
}
.button.btn-cart:hover span span,.btn-checkout:hover span span
{
	color:<?php echo $theme['buttons_addto_texthover_color'] ?>;
}
.catalog-product-view .button.btn-cart,.btn-checkout
{
	background-color:<?php echo $theme['buttons_addto_background_color'] ?>;
}
.button.btn-cart:hover
{
	background-color:<?php echo $theme['buttons_addto_bghover_color'] ?>;
}
.checkout-cart-index .btn-proceed-checkout,
.checkout-cart-index button.button2,
.checkout-cart-index .btn-continue,
.checkout-cart-index .btn-update,
.checkout-cart-index .btn-empty{
 background-color:<?php echo $theme['buttons_shopping_background_color'] ?>;
 }
.checkout-cart-index .btn-proceed-checkout:hover,
.checkout-cart-index button.button2:hover,
.checkout-cart-index .btn-continue:hover,
.checkout-cart-index .btn-update:hover,
.checkout-cart-index .btn-empty:hover{
 background-color:<?php echo $theme['buttons_shopping_bghover_color'] ?>;
 }
.checkout-cart-index .main-container .main span, .main-container .main label, th, td
{
 color:<?php echo $theme['shopping_content_text_color'] ?>; 
}
.cart .page-title h1, .shipping h2
{
 color:<?php echo $theme['shopping_product_text_color'] ?>; 
}
.checkout-cart-index h2.product-name a,
.checkout-cart-index h3.product-name a,
.checkout-cart-index h4.product-name a,
.checkout-cart-index h5.product-name a,
.checkout-cart-index p.product-name a
{
 color:<?php echo $theme['shopping_product_name_color'] ?>; 
}
.cart-totals, .cart-forms .discount, .cart-forms .giftcard, .cart-forms .shipping
{
 background-color:<?php echo $theme['shopping_right_background_color'] ?>;
}
header
{
	background-color:<?php echo $theme['header_background_color'] ?>;
	<?php if($theme['header_background_image']['value']): ?>
	background-image: url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/bg.png'; ?>');
	background-repeat: <?php echo $theme['header_background_image_repeat'] ?>;
	background-position: <?php echo $theme['header_background_image_position'] ?>;
	<?php endif; ?>
}
.logo
{
	background-color:<?php echo $theme['header_logo_background_color'] ?>;
}
.skip-search
{
	background-color:<?php echo $theme['header_search_background'] ?>;
}
#search
{
	color:<?php echo $theme['header_search_text_color'] ?>;
}
#search::-webkit-input-placeholder {
   color: <?php echo $theme['header_search_text_color'] ?>;
}
#search:-moz-placeholder {
   color: <?php echo $theme['header_search_text_color'] ?>;
}
#search::-moz-placeholder {
   color: <?php echo $theme['header_search_text_color'] ?>;
}
#search:-ms-input-placeholder {
   color: <?php echo $theme['header_search_text_color'] ?>;
}
.dropdowntoplink {
  margin-top: <?php echo $theme['header_dropdown_toplink_margintop']."px"; ?>;
  background: <?php echo $theme['header_topbar_background_color']; ?>;
}
.dropdowntoplink .links
{
	text-align: <?php echo $theme['header_dropdown_toplink_alignment']; ?>;
}
.dropdowntoplink .links li a
 {
  color: <?php echo $theme['header_topbar_text_color']; ?>;
  font-size: <?php echo $theme['header_dropdown_toplink_fontsize']."px"; ?>;
 }
 .dropdowntoplink .links li a:hover
 {
  color: <?php echo $theme['header_topbar_texthover_color']; ?>;
   background: <?php echo $theme['header_topbar_texthover_background_color']; ?>;
 }
<?php if($theme['header_dropdown_toplink_option']=="simple"): ?>
.search_main,
.button.search-button
{
	display: block !important;
}
#header-search
{
	top: 40px;
}
<?php endif; ?>
.header-minicart .skip-link .icon,
.skip-account .icon,
.skip-search .icon,
.skip-nav .icon
{
		background: url('<?php echo $this->getSkinUrl('images/icon_sprite_back_blue.png'); ?>');
}
.skip-nav .icon
{
	<?php if($theme['header_icon_color'] == "black"): ?>
		background-position: 0 5px;
	<?php else: ?> 
		background-position: 51px 5px;
	<?php endif; ?>
}
.header-minicart .skip-link .icon
{
	<?php if($theme['header_icon_color'] == "black"): ?>
		background-position: 0 -95px;
	<?php else: ?> 
		background-position: -51px -95px;
	<?php endif; ?>
}
.skip-account .icon
{
	<?php if($theme['header_icon_color'] == "black"): ?>
		background-position: 4px -44px;
	<?php else: ?> 
		background-position: -45px -44px;
	<?php endif; ?>
}
.skip-search .icon
{
	<?php if($theme['header_icon_color'] == "black"): ?>
		background-position: 4px -146px;
	<?php else: ?> 
		background-position: -45px -146px;
	<?php endif; ?>
}
.minicart-wrapper,.header-minicart .subtotal,#header-account.skip-active
{
	background-color:<?php echo $theme['header_dropdown_background_color'] ?>;
}
.minicart-wrapper:hover,
.minicart-wrapper:hover .subtotal,
#header-account.skip-active:hover
{
	background-color:<?php echo $theme['header_dropdown_background_hover'] ?>;
}	
.minicart-wrapper #cart-sidebar .item
{
	background-color:<?php echo $theme['header_dropdown_item_background_color'] ?>;
}
.minicart-wrapper #cart-sidebar .item .btn-edit,.minicart-wrapper #cart-sidebar .item .remove
{
	background-color:<?php echo $theme['header_dropdown_editremove_background'] ?>;
}
.minicart-wrapper #cart-sidebar span,
.minicart-wrapper #cart-sidebar label,
.minicart-wrapper #cart-sidebar th,
.minicart-wrapper #cart-sidebar td,
.minicart-wrapper #cart-sidebar a,
.header-minicart .subtotal .label,
.header-minicart .minicart-actions .cart-link,
.header-minicart #header-cart .block-subtitle,
.header-minicart #header-cart p,
#header-account.skip-active a
{
	color:<?php echo $theme['header_dropdown_text_color'] ?>;
}
#header-cart:hover .block-subtitle,
#header-cart:hover p,
#header-cart:hover .subtotal .label
{
	color:<?php echo $theme['header_dropdown_background_hover_text_color'] ?> !important;
}	
.minicart-wrapper #cart-sidebar a:hover,
#header-cart:hover .minicart-actions .cart-link:hover,	
#header-account.skip-active a:hover
{
	color:<?php echo $theme['header_dropdown_texthover_color'] ?>;
}
.nav-primary
{
	text-align: <?php echo $theme['navigation_menu_alignment'] ?>;
}	
.nav-primary li.level0 li.parent > a:after
{
	border-color:transparent -moz-use-text-color transparent <?php echo $theme['navigation_sub_icon_color'] ?>;
	border-left: 4px solid <?php echo $theme['navigation_sub_icon_color'] ?>;
}
<?php /* ?>
<?php if($theme['navigation_menu_spacing']): ?>
.nav-primary li.level0
{
	margin: 0 <?php echo $theme['navigation_menu_spacing']."px"; ?>;
}
.nav-primary li.level0:last-child
{
	margin-right: 0;
}
.nav-primary li.level0:first-child
{
	margin-left: 0;
}
<?php endif; ?>
<?php */ ?>
.nav-primary a.level0
{
	color:<?php echo $theme['navigation_top_color'] ?>;
	font-size:<?php echo $theme['navigation_top_font_size'].'px' ?>;
	font-family:<?php echo "'".$theme['fonts_navigation']."'" ?>;
}
.nav-primary a.level0:hover
{
		color:<?php echo $theme['navigation_top_hover_color'] ?>;
}
#header-nav
{
	background-color:<?php echo $theme['navigation_top_background_color'] ?>;
}
.nav-primary li.level0 ul
{
	background-color:<?php echo $theme['navigation_sub_container_background'] ?>;
	<?php if($theme['navigation_megamenu_border_color']): ?>
	border:1px solid <?php echo $theme['navigation_megamenu_border_color'] ?>;
	<?php endif; ?>
}
.nav-primary ul.level0 li.parent a
{
		color:<?php echo $theme['navigation_sub_text_color'] ?>;
		font-size: <?php echo $theme['navigation_menu_font_size']."px"; ?>;	
}
.nav-primary ul.level0 li:not(.parent) a
{
	font-size: <?php echo $theme['navigation_menu_font_size']."px"; ?>;
	color:<?php echo $theme['navigation_sub_link_color'] ?>;
}
.nav-primary ul.level0 li:hover
{
	background-color:<?php echo $theme['navigation_sub_link_hover_background'] ?>;
}
.nav-primary ul.level0 li a:hover
{
			color:<?php echo $theme['navigation_sub_link_hover_color'] ?>;
}
<?php if($theme['header_dropdown_toplink_option'] == "simple"): ?>
.skip-links
{
	display: none;
}
<?php else: ?>
.dropdowntoplink
{
	display: block
}
<?php endif; ?>
.footer-container
{
	background-color:<?php echo $theme['footer_background_color'] ?>;
}
.block-title
{
	font-family:<?php echo "'".$theme['fonts_block_title']."'" ?>;
}
.footer-container,.footer p, .footer ul li a,.footer .form-subscribe-header label
{
	color:<?php echo $theme['footer_text_color'] ?>;
}
.footer-container .footer .block-title
{
	border-bottom: 2px solid <?php echo $theme['footer_border_color'] ?>;
    border-top: 2px solid <?php echo $theme['footer_border_color'] ?>;
}
.footer .block-title strong
{
	color:<?php echo $theme['footer_title_color'] ?>;
	font-family:<?php echo "'".$theme['fonts_footer_title']."'" ?>;
}
.footer .links a
{
	color:<?php echo $theme['footer_link_color'] ?>;
}
.footer .links a:hover
{
	color:<?php echo $theme['footer_linkhover_color'] ?>;
	background-color:<?php echo $theme['footer_linkhover_background'] ?>;
}
.footer .lin-k
{
	background-color:<?php echo $theme['footer_newsletter_background'] ?>;
}
.footer button span span
{
	color:<?php echo $theme['footer_button_text_color'] ?>;
}
.footer button
{
	background-color:<?php echo $theme['footer_button_background'] ?> !important;	
}
.footer button:hover span span
{
	color:<?php echo $theme['footer_button_text_hover'] ?>;
}
.footer button:hover
{
	background-color:<?php echo $theme['footer_button_hover_background'] ?> !important;	
}
.footer-container .copyrights
{
	background-color:<?php echo $theme['footer_copyright_background_color'] ?>;
}
.footer-container .copyrights address
{
	color:<?php echo $theme['footer_copyright_text_color'] ?>;
}
.footer-container .copyrights address a
{
	color:<?php echo $theme['footer_copyright_link_color'] ?>;
}
.footer-container .copyrights address a:hover
{
	background-color:<?php echo $theme['footer_copyright_linkhover_background'] ?>;
	color:<?php echo $theme['footer_copyright_linkhover_color'] ?>;
}
.main-container .main
{
	background-color:<?php echo $theme['content_background_color'] ?>;
	border: 1px solid <?php echo $theme['content_border_color'] ?>;
} 
.main-container .main span,.main-container .main label,th,td
{
	color:<?php echo $theme['content_text_color'] ?>;
	font-family:<?php echo "'".$theme['fonts_main']."'" ?>;
}
.main-container .main a
{
	background-color:<?php echo $theme['content_link_background'] ?>;
	color:<?php echo $theme['content_link_col or'] ?>;
}
.main-container .main a:hover
{
	background-color:<?php echo $theme['content_linkhover_background'] ?>;
	color:<?php echo $theme['content_linkhover_color'] ?>;
}
.account-login 
{
	background-color:<?php echo $theme['login_background_color'] ?>;
	background-color:url(<?php echo $this->getSkinUrl('images/'.$theme['login_background_image']); ?>);
}
.home-info
{
	color:<?php echo $theme['homepage_textrow_fontcolor'] ?>;
	background-color:<?php echo $theme['homepage_textrow_background'] ?>;
	font-family:<?php echo "'".$theme['homepage_textrow_font']."'" ?>;
}
.std #accordion1 .slide_handle
{
	background: <?php echo $theme['de_tab_bg_color'] ?>;
	 border: 1px solid <?php echo $theme['de_tab_border_color'] ?>;
}
.std #accordion1 .slide_handle div
{
	color:<?php echo $theme['de_tab_title_color'] ?>;
}
.std #accordion1 .slide_content h3,.std #accordion1 .slide_content h4
{
	color:<?php echo $theme['de_tab_content_title_color'] ?>;
}	
.std #accordion1 .slide_content p
{
	color:<?php echo $theme['de_tab_content_color'] ?>;
}
.toolbar
{
	background-color:<?php echo $theme['toolbar_background_color'] ?>;
}
.toolbar, .pager,.sort-by label
{
	color:<?php echo $theme['toolbar_text_color'] ?> !important;
}
.sort-by > select {
  background-color:<?php echo $theme['toolbar_dropdown_background'] ?>;
  color:<?php echo $theme['toolbar_dropdown_textcolor'] ?>;
}
.pager .limiter > label {
	color:<?php echo $theme['toolbar_text_color'] ?> !important;
}
.pages ol li
{
	background-color:<?php echo $theme['toolbar_pages_links_background'] ?>;
}
.pages ol li:hover
{
	background-color:<?php echo $theme['toolbar_pages_links_hover_background'] ?>;
}
.pages ol li a
{
	color:<?php echo $theme['toolbar_pages_links_textcolor'] ?> !important;
}
.pages ol li a:hover
{
	color:<?php echo $theme['toolbar_pages_links_hover_text'] ?> !important;
}
.limiter select
{
	background-color:<?php echo $theme['toolbar_dropdown_background'] ?>;
	color:<?php echo $theme['toolbar_dropdown_textcolor'] ?>;
}
.wrapper .breadcrumbs
{
	background:<?php echo $theme['breadcrumbs_background_color'] ?>;	
}
.wrapper .breadcrumbs ul li
{
	line-height:<?php echo $theme['breadcrumbs_text_size']."px"; ?>; 
	font-size:<?php echo $theme['breadcrumbs_text_size']."px"; ?>;
}
.wrapper .breadcrumbs ul li a,
.wrapper .breadcrumbs ul li span
{
	color:<?php echo $theme['breadcrumbs_link_color'] ?>;
	font-size:<?php echo $theme['breadcrumbs_text_size']."px"; ?>;
}
.wrapper .breadcrumbs ul li a:hover
{
	color:<?php echo $theme['breadcrumbs_link_hover_color'] ?>;
}
.wrapper .breadcrumbs ul li strong
{
	color:<?php echo $theme['breadcrumbs_link_color'] ?>;
	font-size:<?php echo $theme['breadcrumbs_text_size']."px"; ?>;
}
.catalog-category-view .col-left
{
	<?php if($theme['productlist_block_topborder_color']): ?>
		border-top: 1px solid <?php echo $theme['productlist_block_topborder_color'] ?>;
	<?php endif; ?>
}
.catalog-category-view .col-left .block
{
	<?php if($theme['productlist_block_itemsborder_color']): ?>
		border: 1px solid <?php echo $theme['productlist_block_itemsborder_color'] ?>;
	<?php endif; ?>
	background:<?php echo $theme['productlist_block_background_color'] ?>;
}
.catalog-category-view .col-left .block .block-title span
{
	font-size: <?php echo $theme['productlist_block_title_fontsize']."px"; ?>;
	color:<?php echo $theme['productlist_block_title_color'] ?>;	
}
.catalog-category-view .col-left .block .block-content dt .filter-name
{
	color:<?php echo $theme['productlist_block_text_color'] ?>;
}
.catalog-category-view .col-left .block .block-content dd ol li a,
.catalog-category-view .col-left .block .block-content dd ol li .count,
.catalog-category-view .col-left .block .block-content dd ol li .price
{
	color:<?php echo $theme['productlist_block_link_color'] ?>;	
}
.catalog-category-view .col-left .block .block-content dd ol li a:hover,
.catalog-category-view .col-left .block .block-content dd ol li:hover .count,
.catalog-category-view .col-left .block .block-content dd ol li:hover .price
{
	color:<?php echo $theme['productlist_block_linkhover_color'] ?>;
	background-color:<?php echo $theme['productlist_block_linkhover_background'] ?> !important; 
}
.catalog-category-view .col-left .block .block-content .button span
{
	background: <?php echo $theme['productlist_block_button_background'] ?>;
	color:<?php echo $theme['productlist_block_button_textcolor'] ?>;
}
.catalog-category-view .col-left .block .block-content .button:hover span
{
	background: <?php echo $theme['productlist_block_button_background_hovercolor'] ?>;
	color:<?php echo $theme['productlist_block_button_text_hovercolor'] ?>;
}
.category-products h2.product-name a
{
	color:<?php echo $theme['productlist_product_name_color'] ?>;
	font-size: <?php echo $theme['productlist_product_name_fontsize']."px" ?>; 
}
.category-products .product-name a:hover
{
	color:<?php echo $theme['productlist_producttitle_hover_color'] ?>;
	background-color:<?php echo $theme['productlist_producttitle_hover_background'] ?>;
}
.category-products .price-box .price:hover
{
	color:<?php echo $theme['productlist_productprice_hover_color'] ?>;
}
.category-products .button,
.category-products .add-to-links a
{
	background-color:<?php echo $theme['productlist_grid_addto_background'] ?>;
		color:<?php echo $theme['productlist_addto_textcolor'] ?>;
}
.category-products .products-grid .add-to-links a:hover,
.category-products .products-grid .button:hover
{
	background-color:<?php echo $theme['productlist_grid_addto_hover_background'] ?>;
}
.category-products .button:hover span
{
	color:<?php echo $theme['productlist_addto_texthover'] ?> !important;
}
.category-products .products-list .button:hover
{
	background-color:<?php echo $theme['productlist_list_addto_hover_background'] ?>;
}
.products-list .desc.std:hover
{
	color:<?php echo $theme['productlist_description_texthover'] ?>;
}
.category-products .add-to-links a:hover
{
	color:<?php echo $theme['productlist_addto_texthover'] ?>;
}
.product-view .product-name .h1
{	
	color:<?php echo $theme['productdetails_title_color'] ?>;
}
.product-view .short-description .std,
.product-view .sharing-links li
{
	color:<?php echo $theme['productdetails_text_color'] ?>;
}
.product-view a,.product-view a.link-wishlist
{
	background-color:<?php echo $theme['productdetails_link_background_color'] ?> !important;
	color:<?php echo $theme['productdetails_link_color'] ?> !important;
}
.product-view a.link-wishlist
{
	background: url("<?php echo $this->getSkinUrl(); ?>images/wishlist.jpg") no-repeat scroll left rgba(0, 0, 0, 0);
}a
.product-view a:hover,
.product-view a.link-wishlist:hover
{
		background-color:<?php echo $theme['productdetails_linkhover_background'] ?> !important;
		color:<?php echo $theme['productdetails_linkhover_color'] ?> !important;
}
.product-view .price-box .price, .product-view .price
{
	color:<?php echo $theme['productdetails_price_color'] ?>;
}
.product-view .price-box .old-price .price, .product-view .old-price .price
{
	color:<?php echo $theme['productdetails_oldprice_color'] ?>;
}
.product-view .price-label
{
	color:<?php echo $theme['productdetails_price_textcolor'] ?> !important;
}	
#product-attribute-specs-table tbody th
{
	<?php if($theme['productdetails_attribute_border_color']): ?>
		border-bottom: 1px solid <?php echo $theme['productdetails_attribute_border_color']; ?>;
    	border-right: 1px solid <?php echo $theme['productdetails_attribute_border_color']; ?>;
	<?php endif; ?>
}
#product-attribute-specs-table tbody td
{
	<?php if($theme['productdetails_attribute_border_color']): ?>
		border-bottom: 1px solid <?php echo $theme['productdetails_attribute_border_color']; ?>;
	<?php endif; ?>
}
#product-attribute-specs-table tbody th,
#product-attribute-specs-table tbody td
{
	font-size: <?php echo $theme['productdetails_attribute_fontsize']."px"; ?>;
}
#product-attribute-specs-table tbody tr.odd th,
#product-attribute-specs-table tbody tr.odd td
{
	background: <?php echo $theme['productdetails_attribute_odd_background_color']; ?>;
	color: <?php echo $theme['productdetails_attribute_odd_text_color']; ?>;	
}
#product-attribute-specs-table tbody tr.even th,
#product-attribute-specs-table tbody tr.even td
{
	background: <?php echo $theme['productdetails_attribute_even_background_color']; ?>;
	color: <?php echo $theme['productdetails_attribute_even_text_color']; ?>;	
}
.catalog-product-view .product-collateral .toggle-tabs
{
	background-color:<?php //echo $theme['productdetails_tabhead_background'] ?>;
}
#collateral-tabs .tab-content .std,
#collateral-tabs .tab-content .data-table th,
#collateral-tabs .tab-content .data-table td,
#collateral-tabs .data-table tbody td,
#collateral-tabs .data-table tfoot td
{
	font-family: <?php echo $theme['fonts_main'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li
{
	<?php if($theme['productdetails_tabhead_border_color']): ?>
		border: 1px solid <?php echo $theme['productdetails_tabhead_border_color']; ?>;
	<?php endif; ?>
	background-color:<?php echo $theme['productdetails_tabhead_background'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li:first-child
{
	<?php if($theme['productdetails_tabhead_border_color']): ?>
		border: 1px solid <?php echo $theme['productdetails_tabhead_border_color']; ?>;
	<?php endif; ?>
}
.catalog-product-view .product-collateral .toggle-tabs li:last-child
{
	<?php if($theme['productdetails_tabhead_border_color']): ?>
		border: 1px solid <?php echo $theme['productdetails_tabhead_border_color']; ?>;
	<?php endif; ?>
}
.catalog-product-view #collateral-tabs
{
	border: 1px solid <?php echo $theme['productdetails_tabcontent_border_color']; ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li
{
	background-color:<?php echo $theme['productdetails_tabhead_background'] ?>;	
}
.catalog-product-view .product-collateral .toggle-tabs li:hover
{
	background-color:<?php echo $theme['productdetails_tabhead_hover_background'] ?>;
}	
.catalog-product-view .product-collateral .toggle-tabs li > span
{
	color:<?php echo $theme['productdetails_tabhead_textcolor'] ?>;
	/*background: none;*/
}
.catalog-product-view .product-collateral .toggle-tabs li:hover span
{
	color:<?php echo $theme['productdetails_tabhead_texthover_color'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li:hover
{
	background-color:<?php echo $theme['productdetails_tab_hover_background'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li.current
{
	background-color:<?php echo $theme['productdetails_active_tabhead_background'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li.current span
{
	color:<?php echo $theme['productdetails_active_tabhead_text_color'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li.current:hover
{
	background-color:<?php echo $theme['productdetails_active_tabhead_hover_background'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li.current:hover span
{
	color:<?php echo $theme['productdetails_active_tabhead_hover_text_color'] ?>;
}
.collateral-tabs,.collateral-tabs .data-table td,.collateral-tabs .data-table th
{
	background-color:<?php echo $theme['productdetails_tabcontent_background'] ?>;
	color:<?php echo $theme['productdetails_tabcontent_textcolor'] ?> !important;
}
.catalog-product-view .tab-content .data-table th
{
	background-color:<?php echo $theme['productdetails_attribute_table_heading_background'] ?>;
}
.catalog-product-view .tab-content a
{
	background-color:<?php echo $theme['productdetails_tabcontent_link_background'] ?> !important;
	color:<?php echo $theme['productdetails_tabcontent_link_color'] ?> !important;
}
.catalog-product-view .tab-content a:hover
{
	background-color:<?php echo $theme['productdetails_tabcontent_linkhover_background'] ?> !important;
	color:<?php echo $theme['productdetails_tabcontent_linkhover_color'] ?> !important;
}
.social_icons_theme1 .facebook
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll left top rgba(0, 0, 0, 0);
}
.social_icons_theme1 .twitter
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -41px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .pinterest
{
	background:  url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -82px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .instagram
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -244px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .foursquare
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll 0 -82px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .fancy
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -81px -123px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .polyvore
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -325px -82px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .yelp
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -243px -163px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .youtube
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll right top rgba(0, 0, 0, 0);
}
.social_icons_theme1 .gplus
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -123px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .linkedin
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -203px 0 rgba(0, 0, 0, 0);
}
.social_icons_theme1 .tumbler
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -123px -41px rgba(0, 0, 0, 0);
}

.social_icons_theme2 .facebook
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll left top rgba(0, 0, 0, 0);
}
.social_icons_theme2 .twitter
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -41px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .pinterest
{
	background:  url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -82px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .instagram
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -244px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .foursquare
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll 0 -82px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .fancy
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -81px -123px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .polyvore
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -325px -82px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .yelp
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -243px -163px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .youtube
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll right top rgba(0, 0, 0, 0);
}
.social_icons_theme2 .gplus
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -123px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .linkedin
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -203px 0 rgba(0, 0, 0, 0);
}
.social_icons_theme2 .tumbler
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -123px -41px rgba(0, 0, 0, 0);
}

.social_icons_theme3 .facebook
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -6px -8px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .twitter
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -56px -59px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .pinterest
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -259px -8px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .instagram
{
	background:url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -208px -8px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .foursquare
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .fancy
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .polyvore
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .yelp
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -208px -109px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .youtube
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -455px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .gplus
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?> ") no-repeat scroll -157px -8px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .linkedin
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -455px -103px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .tumbler
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -189px -103px rgba(0, 0, 0, 0);
}
	
.social_icons_theme4 .facebook
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll 0 -1px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .twitter
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -44px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .pinterest
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -88px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .instagram
{
	background:url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -221px -91px rgba(0, 0, 0, 0)
}
.social_icons_theme4 .foursquare
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -266px -45px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .fancy
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .polyvore
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .yelp
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -221px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .youtube
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -133px -46px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .gplus
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -133px -1px rgba(0, 0, 0, 0)
}
.social_icons_theme4 .linkedin
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -177px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .tumbler
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll right top rgba(0, 0, 0, 0);
}
	
.social_icons_theme5 .facebook
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll 0 -1px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .twitter
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -51px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .pinterest
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -103px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .instagram
{
	background:url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -258px -104px rgba(0, 0, 0, 0)
}
.social_icons_theme5 .foursquare
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -309px -53px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .fancy
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .polyvore
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .yelp
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -258px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .youtube
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -154px -53px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .gplus
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -154px -1px rgba(0, 0, 0, 0)
}
.social_icons_theme5 .linkedin
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -206px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .tumbler
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll right top rgba(0, 0, 0, 0);
}

.social_icons_theme6 .facebook
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -55px -13px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .twitter
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -8px -13px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .pinterest
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -55px -129px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .instagram
{
	background:url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -9px -246px rgba(0, 0, 0, 0)
}
.social_icons_theme6 .foursquare
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -242px -244px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .fancy
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -102px -203px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .polyvore
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -100px -285px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .yelp
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -101px -51px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .youtube
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -147px -50px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .gplus
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -7px -130px rgba(0, 0, 0, 0)
}
.social_icons_theme6 .linkedin
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -101px -166px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .tumbler
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -100px -129px rgba(0, 0, 0, 0);
}
<?php /* ?>
.sidebar .block
{
	border-top:1px solid <?php echo $theme['sidebar_block_topborder_color'] ?>;
	background-color:<?php echo $theme['sidebar_block_background_color'] ?>;
}
.sidebar .block .block-title span
{
	color:<?php echo $theme['sidebar_block_title_color'] ?>;
	font-size:<?php echo $theme['sidebar_block_title_fontsize']."px" ?>;
}
.sidebar .block .item
{
	border:1px solid <?php echo $theme['sidebar_block_itemsborder_color'] ?>;
}
.sidebar .block a
{
	color:<?php echo $theme['sidebar_block_link_color'] ?>;
}
.sidebar .block a:hover,
.gan-list-checkbox a:hover span
{
	color:<?php echo $theme['sidebar_block_linkhover_color'] ?>;
	background-color:<?php echo $theme['sidebar_block_linkhover_background'] ?>;
}
.sidebar .block button.button
{
	background-color:<?php echo $theme['sidebar_button_background'] ?> !important;
}
.sidebar .block button.button span
{
		color:<?php echo $theme['sidebar_button_textcolor'] ?>;
}
.sidebar .block button.button:hover
{
	background-color:<?php echo $theme['sidebar_button_background_hovercolor'] ?> !important;
}
.sidebar .block button.button:hover span
{
	color:<?php echo $theme['sidebar_button_text_hovercolor'] ?>;
}
.sidebar .block #pollForm .block-subtitle
{
	background-color:<?php echo $theme['sidebar_poll_question_background'] ?>;
	color:<?php echo $theme['sidebar_poll_question_textcolor'] ?>;
}
<?php */ ?>
#contactForm h2.legend
{
	font-family:<?php echo "'".$theme['contacts_title_font']."'" ?>;
	color:<?php echo $theme['contacts_title_fontcolor'] ?>;
}
.Contct_Addrress .cnt-addrs .cnt-adres-text,
.Contct_Addrress .cnt-addrs .cnt-title,
#contactForm .fieldset .fields label
{
		font-family:<?php echo "'".$theme['contacts_content_font']."'" ?>;
		color:<?php echo $theme['contacts_content_fontcolor'] ?>;
}
.inline2.cboxElement {
	background-color:<?php echo $theme['contacts_appointment_background'] ?>;
	font-family:<?php echo "'".$theme['contacts_appointment_font']."'" ?>;
    color: <?php echo $theme['contacts_appointment_fontcolor'] ?>;
}
.home-main.featured-tabs .toggle-tabs
{
	background: <?php echo $theme['general_main_color']; ?>
}
.logo {
	/*width: auto;
	min-height: 0;
	max-width: 100%;*/
	/*max-width: 170px;
    min-height: 0px;*/
	/*margin:<?php //if($theme['header_logo_placement']=="center"){ echo "0 38%"; } else { echo "8px 0 0 0"; } ?>*/
	margin-left:<?php if($theme['header_logo_placement']=="center"){ echo "36%"; } else { echo "0"; } ?>;
	margin-right:<?php if($theme['header_logo_placement']=="center"){ echo "38%"; } else { echo "0"; } ?>;
	margin-top:<?php echo $theme['margin_above_logo']."px" ?>;
}
.logo img {
	/*max-width: 100%;
    min-height: 65px;
    min-width: 170px;
    opacity: 1;
    width: 170px;*/
	float:<?php if($theme['header_logo_placement']=="center"){ echo "none"; } else { echo "left"; } ?>;
}
@media only screen and (max-width: 900px) and (min-width: 771px)
{
	.logo{
	/*	margin-left:32%;
		margin-right:22%;*/
		margin-top:<?php echo $theme['margin_above_logo']?>;
		margin-right: <?php if($theme['header_logo_placement']=="center"){ echo "22%"; } ?>
		margin-left: <?php if($theme['header_logo_placement']=="center"){ echo "32%"; } ?>
		
	}
}
@media only screen and (max-width: 770px)
{
	#nav .nav-primary li.parent.sub-menu-active > a:after, .nav-primary li.parent.menu-active > a:after
	{
		border-color: <?php echo $theme['navigation_sub_icon_color'] ?> transparent -moz-use-text-color;
		border-top: 5px solid <?php echo $theme['navigation_sub_icon_color'] ?>;
		border-left: 5px solid Transparent;
	}
	#nav .nav-primary li.level0.parent.sub-menu-active > a:after, .nav-primary li.level0.parent.menu-active > a:after
	{
		content: none;
	}	
	<?php if($theme['header_responsive_logo_placement'] == "center"): ?>
	.logo img
	{
		float:none;
	}
	<?php else: ?>
	.logo img
	{
		float:left;
	}
	<?php endif; ?>
	.nav-primary ul.level0 li a:hover
	{
		background: <?php echo $theme['navigation_sub_link_hover_background']; ?>;
	}
	.skip-search
	{
		background: <?php echo $theme['header_topbar_background_color']; ?>;
	}
	.skip-search:hover
	{
		background: <?php echo $theme['header_topbar_texthover_background_color']; ?>;
	}
	<?php /* ?>
	<?php if($theme['header_dropdown_toplink_option'] == "simple"): ?>
	.skip-links
	{
		display: block;
	}
	.skip-account,
	.skip-cart
	{
		display: none;
	}
	.skip-nav {
		width: 75%;
		text-align: left;
		padding-left: 22px;
	}
	.dropdowntoplink
	{
		z-index: 1111;
		display: block;
		position: fixed;
	}
	.cms-index-index header
	{
		margin-top: 37px;
	}
	#header-search
	{
		z-index: 1111;
	}
	<?php else: ?>
	.dropdowntoplink
	{
		display: none;
	}
	<?php endif; ?>
	<?php */ ?>
	.dropdowntoplink
	{
		display: none;
	}
	.skip-links
	{
		display: block;
	}
}
@media only screen and (max-width: 499px)
{
	<?php /* ?>
	<?php if($theme['header_dropdown_toplink_option'] == "simple"): ?>
	.skip-links
	{
		display: block;
	}
	.skip-account,
	.skip-cart
	{
		display: none;
	}
	.skip-nav {
		width: 80%;
	}
	<?php else: ?>
	.dropdowntoplink
	{
		display: none;
	}
	<?php endif; ?>
	<?php */ ?>
}

.product-view .product-right .product-shop .product-name span.h1
{
	font-size:<?php echo $theme['productdetails_title_font_size']."px"; ?>;
}
.product-view .product-right .product-shop .product-sku span.h1
{
	color: <?php echo $theme['productdetails_sku_color'] ?> !important;
}
.product-view .product-right .product-shop .product-sku span.h1,
.product-view .sharing-links li,
.product-view .add-to-cart-wrapper span.or
{
	font-size:<?php echo $theme['productdetails_sku_font_size']."px"; ?>;
	font-family:'<?php echo $theme['fonts_productpage'] ?>';
}
.product-view .make-apointment .inline_2,
.product-view .make-apointment .inline_2:hover
{
	font-size:<?php echo $theme['productdetails_Inquire_font_size']."px"; ?>;
	font-family:'<?php echo $theme['fonts_productpage'] ?>';
	background-color: <?php echo $theme['productdetails_Inquire_background_color']; ?>;
	color: <?php echo $theme['productdetails_Inquire_color']; ?> !important;
}
.catalog-product-view  .block-title-recent span,.catalog-product-view  #recently-viewed-items .product-name a
{
	font-size:<?php echo $theme['productdetails_recently_product_font_size']."px"; ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li > span,
#collateral-tabs .tab-content .std, #collateral-tabs .tab-content .data-table th, #collateral-tabs .tab-content .data-table td, #collateral-tabs .data-table tbody td, #collateral-tabs .data-table tfoot td
{
	font-family:'<?php echo $theme['fonts_productpage'] ?>';
}
.catalog-product-view .product-collateral .toggle-tabs li > span,
.catalog-product-view #product-attribute-specs-table tbody th,
.catalog-product-view #product-attribute-specs-table tbody td
{
	font-size: <?php echo $theme['productdetails_attribute_fontsize']."px"; ?>;
}
</style>