<!--<link href='http://fonts.googleapis.com/css?family=ABeeZee' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Abril+Fatface' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Aclonica' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Acme' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Actor' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Adamina' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Advent+Pro' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Aguafina+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Akronim' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Aladin' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Aldrich' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Alegreya' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Alegreya+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Alex+Brush' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Alfa+Slab+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Alice' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Alike' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Alike+Angular' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Allan' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Allerta' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Allerta+Stencil' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Allura' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Almendra' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Almendra+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Amarante' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Amatic+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Amethysta' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Anaheim' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Andada' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Andika' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Angkor' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Annie+Use+Your+Telescope' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Anonymous+Pro' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Antic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Antic+Didone' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Antic+Slab' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Anton' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Arapey' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Arbutus' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Arbutus+Slab' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Archivo+Black' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Archivo+Narrow' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Arizonia' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Armata' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Artifika' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Asap' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Asset' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Astloch' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Asul' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Atomic+Age' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Aubrey' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Audiowide' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Autour+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Average' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Average+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Averia+Gruesa+Libre' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Averia+Libre' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Averia+Sans+Libre' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Averia+Serif+Libre' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bad+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Balthazar' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Basic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Battambang' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Baumans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bayon' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Belgrano' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Belleza' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=BenchNine' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bentham' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Berkshire+Swash' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bevan' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bigshot+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bilbo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bilbo+Swash+Caps' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bitter' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Black+Ops+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bokor' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bonbon' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Boogaloo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bowlby+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bowlby+One+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Brawler' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bree+Serif' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bubblegum+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bubbler+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Buda' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Buenard' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Butcherman' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Butterfly+Kids' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cabin+Condensed' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cabin+Sketch' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Caesar+Dressing' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cagliostro' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Calligraffitti' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cambo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Candal' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cantarell' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cantata+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cantora+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Capriola' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cardo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Carme' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Carrois+Gothic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Carrois+Gothic+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Carter+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Caudex' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cedarville+Cursive' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ceviche+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Changa+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Chango' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Chau+Philomene+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Chela+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Chelsea+Market' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Chenla' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cherry+Cream+Soda' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cherry+Swash' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Chewy' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Chicle' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Chivo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cinzel+Decorative' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Coda' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Coda+Caption' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Codystar' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Combo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Coming+Soon' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Concert+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Condiment' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Content' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Contrail+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Convergence' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Copse' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Corben' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Courgette' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Coustard' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Covered+By+Your+Grace' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Crafty+Girls' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Creepster' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Crete+Round' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Crimson+Text' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Crushed' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cuprum' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cutive' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cutive+Mono' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Damion' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Dangrek' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Dawning+of+a+New+Day' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Days+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Delius' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Delius+Swash+Caps' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Delius+Unicase' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Della+Respira' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Devonshire' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Didact+Gothic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Diplomata' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Diplomata+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Doppio+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Dorsa' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Dosis' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Dr+Sugiyama' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans+Mono' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Duru+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Dynalight' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Eagle+Lake' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Eater' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Economica' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Electrolize' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Emblema+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Emilys+Candy' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Engagement' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Enriqueta' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Erica+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Esteban' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Euphoria+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ewert' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Exo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Expletus+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Fanwood+Text' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Fascinate' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Fascinate+Inline' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Faster+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Fasthand' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Federant' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Federo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Felipa' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Fenix' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Finger+Paint' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Fjord+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Flamenco' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Flavors' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Fondamento' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Fontdiner+Swanky' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Forum' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Francois+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Fredericka+the+Great' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Freehand' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Fresca' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Frijole' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Fugaz+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=GFS+Didot' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=GFS+Neohellenic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Galdeano' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Galindo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Gentium+Basic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Gentium+Book+Basic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Geo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Geostar' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Geostar+Fill' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Germania+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Give+You+Glory' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Glass+Antiqua' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Glegoo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Goblin+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Gochi+Hand' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Gorditas' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Goudy+Bookletter+1911' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Graduate' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Gravitas+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Griffy' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Gruppo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Gudea' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Habibi' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Hammersmith+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Handlee' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Hanuman' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Happy+Monkey' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Headland+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Henny+Penny' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Herr+Von+Muellerhoff' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Holtwood+One+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Homemade+Apple' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Homenaje' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=IM+Fell+DW+Pica' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=IM+Fell+DW+Pica+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=IM+Fell+Double+Pica' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=IM+Fell+Double+Pica+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=IM+Fell+English' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=IM+Fell+English+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=IM+Fell+French+Canon' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=IM+Fell+French+Canon+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=IM+Fell+Great+Primer' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=IM+Fell+Great+Primer+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Iceberg' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Iceland' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Imprima' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Inconsolata' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Inder' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Inika' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Irish+Grover' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Istok+Web' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Italiana' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Italianno' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Jacques+Francois' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Jacques+Francois+Shadow' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Jim+Nightshade' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Jockey+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Jolly+Lodger' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Josefin+Slab' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Judson' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Julee' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Junge' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Jura' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Just+Another+Hand' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Just+Me+Again+Down+Here' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Kameron' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Karla' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Kelly+Slab' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Kenia' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Khmer' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Kite+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Knewave' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Kotta+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Koulen' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Kranky' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Kreon' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Kristi' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Krona+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=La+Belle+Aurore' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lancelot' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=League+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Leckerli+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ledger' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lekton' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lemon' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Life+Savers' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lilita+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Limelight' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Linden+Hill' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lobster+Two' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Londrina+Outline' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Londrina+Shadow' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Londrina+Sketch' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Londrina+Solid' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Loved+by+the+King' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lovers+Quarrel' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Luckiest+Guy' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lusitana' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lustria' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Macondo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Macondo+Swash+Caps' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Magra' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Maiden+Orange' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Mako' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Marcellus' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Marcellus+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Marck+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Marko+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Marmelad' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Marvel' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Mate' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Mate+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Maven+Pro' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=McLaren' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Meddon' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=MedievalSharp' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Medula+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Megrim' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Meie+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Merienda+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Metal' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Metal+Mania' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Metamorphous' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Metrophobic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Michroma' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Miltonian' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Miltonian+Tattoo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Miniver' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Miss+Fajardose' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Modern+Antiqua' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Molengo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Molle' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Monofett' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Monoton' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Monsieur+La+Doulaise' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Montaga' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Montez' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Montserrat+Alternates' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Montserrat+Subrayada' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Moul' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Moulpali' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Mountains+of+Christmas' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Mr+Bedfort' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Mr+Dafoe' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Mr+De+Haviland' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Mrs+Saint+Delafield' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Mrs+Sheppards' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Muli' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Mystery+Quest' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Neucha' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Neuton' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=News+Cycle' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Niconne' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nixie+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nobile' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nokora' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Norican' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nosifer' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nothing+You+Could+Do' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Noticia+Text' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nova+Cut' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nova+Flat' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nova+Mono' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nova+Oval' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nova+Round' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nova+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nova+Slim' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nova+Square' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Numans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Nunito' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Odor+Mean+Chey' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Offside' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Old+Standard+TT' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Oldenburg' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Oranienbaum' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Oregano' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Orienta' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Original+Surfer' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Over+the+Rainbow' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Overlock' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Overlock+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ovo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Oxygen+Mono' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=PT+Mono' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=PT+Sans+Caption' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=PT+Serif+Caption' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Paprika' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Parisienne' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Passero+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Patrick+Hand' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Patua+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Paytone+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Peralta' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Petit+Formal+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Petrona' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Philosopher' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Piedra' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Pinyon+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Plaster' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Play' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Playball' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Playfair+Display+SC' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Podkova' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Poller+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Poly' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Pompiere' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Pontano+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Port+Lligat+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Port+Lligat+Slab' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Prata' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Preahvihear' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Princess+Sofia' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Prociono' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Prosto+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Puritan' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Quando' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Quantico' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Quattrocento' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Qwigley' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Racing+Sans+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Radley' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway+Dots' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Rammetto+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ranchers' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Rancho' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Rationale' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Redressed' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Reenie+Beanie' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Revalia' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ribeye' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ribeye+Marrow' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Rochester' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Rock+Salt' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Rokkitt' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Romanesco' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ropa+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Rosario' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Rosarivo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Rouge+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ruda' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ruge+Boogie' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ruluko' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ruslan+Display' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Russo+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ruthie' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Rye' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sail' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Salsa' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sanchez' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sancreek' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sansita+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sarina' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Scada' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Schoolbell' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Seaweed+Script' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sevillana' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Seymour+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light+Two' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Shanti' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Share' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Share+Tech' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Share+Tech+Mono' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Shojumaru' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Short+Stack' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Siemreap' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sigmar+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Signika' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Signika+Negative' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Simonetta' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sirin+Stencil' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Six+Caps' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Skranji' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Slackey' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Smokum' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Smythe' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sniglet' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Snippet' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sofadi+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sofia' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sonsie+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sorts+Mill+Goudy' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Source+Code+Pro' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Special+Elite' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Spicy+Rice' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Spinnaker' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Spirax' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Squada+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Stalinist+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Stardos+Stencil' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Stint+Ultra+Condensed' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Stint+Ultra+Expanded' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Stoke' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Strait' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sue+Ellen+Francisco' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Sunshiney' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Supermercado+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Suwannaphum' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Swanky+and+Moo+Moo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Syncopate' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Tangerine' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Taprom' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Telex' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Tenor+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=The+Girl+Next+Door' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Tienne' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Tinos' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Titan+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Trade+Winds' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Trocchi' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Trochut' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Trykker' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Tulpen+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ultra' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Uncial+Antiqua' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Underdog' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Unica+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=UnifrakturCook' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=UnifrakturMaguntia' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Unkempt' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Unlock' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Unna' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=VT323' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Varela' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Vast+Shadow' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Vibur' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Vidaloka' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Viga' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Voces' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Volkhov' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Voltaire' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Waiting+for+the+Sunrise' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Wallpoet' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Walter+Turncoat' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Warnes' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Wellfleet' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Wire+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Yellowtail' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Yeseva+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Yesteryear' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Zeyada' rel='stylesheet' type='text/css'>-->


<?php
 $theme = $this->getConfig();
// print_r($theme);
//exit;
?>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_main']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_title']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_price']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_footer_title']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_navigation']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_block_title']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_product_title']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_productdetails_price']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['fonts_product_name']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['contacts_title_font']) ?>' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(" ","+",$theme['contacts_content_font']) ?>' rel='stylesheet' type='text/css'>
<style>
.wrapper
{
	
	
	background-color:<?php echo $theme['general_main_color'] ?>;
}
.page-header
{
	
	height: <?php echo $theme['header_height']."px" ?>;	
	<?php if($theme['header_underline_color']): ?> border-bottom: 1px solid <?php echo $theme['header_underline_color'] ?>; <?php endif; ?>
}
.main-container
{
	margin-top:<?php echo ($theme['header_height']-2)."px" ?>;
}
.page-header-container
{
	height:<?php echo $theme['header_height']."px" ?>;
}
.product-name .h1,
{
	color:<?php echo $theme['general_title_color'] ?> !important;
	font-family:<?php echo "'".$theme['fonts_product_title']."'" ?> !important;
}
.product-name h1
{
	color:<?php echo $theme['general_title_color'] ?> !important;
	font-family:<?php echo "'".$theme['fonts_product_name']."'" ?> !important;
}
h1,
h2,
h3,
h4,
h5,
h6,
.page-title h1,
.page-title h2
{
	color:<?php echo $theme['general_title_color'] ?>;
	font-family:<?php echo "'".$theme['fonts_title']."'" ?>;
}
.price-box .price, .price
{
	font-family:<?php echo "'".$theme['fonts_price']."'" ?> !important;
}
.product-view .price-box .price,.product-view .price
{
	font-family:<?php echo "'".$theme['fonts_productdetails_price']."'" ?> !important;
}
.price-box .regular-price .price
{
	color:<?php echo $theme['general_price_color'] ?>;
}
.price-box .old-price .price
{
	color:<?php echo $theme['general_oldprice_color'] ?>;
}
.price-box .old-price .price-label, .price-box .special-price .price-label
{
	color:<?php echo $theme['general_pricetext_color'] ?>;
}
.price-box .special-price .price
{
	color:<?php echo $theme['general_onsaleprice_color'] ?>;
}
.main-container .buttons-set a,
.main-container .buttons-set a span,
.main-container .buttons-set button span,
button span span
{
	color:<?php echo $theme['buttons_text_color'] ?>;
}
.skip-cart,
.skip-account
{
	background-color:<?php echo $theme['header_topbar_background_color'] ?>;
	color:<?php echo $theme['header_topbar_text_color'] ?>;
}
.skip-search .label,
.skip-search:hover .label
{
	color:<?php echo $theme['header_topbar_text_color'] ?>;
}
.skip-cart:hover,
.skip-account:hover
{
	color:<?php echo $theme['header_topbar_texthover_color'] ?>;
	background-color:<?php echo $theme['header_topbar_texthover_background_color'] ?>;
}
.main-container .buttons-set a,
.main-container .buttons-set button,
button
{
	background-color:<?php echo $theme['buttons_background_color'] ?>;
}
.main-container .buttons-set a:hover,
button:hover span span,
.main-container .buttons-set a:hover span,
.main-container .buttons-set button:hover span
{
	color:<?php echo $theme['buttons_texthover_color'] ?>;
}
.main-container .buttons-set a:hover,
.main-container .buttons-set button:hover,
button:hover
{
	background-color:<?php echo $theme['buttons_bghover_color'] ?>;
}
.button.btn-cart span span,
.btn-checkout span span,
.button2 span,
.button2 span span
{
	color:<?php echo $theme['buttons_addto_text_color'] ?> !important;
}
.button.btn-cart:hover span span,.btn-checkout:hover span span
{
	color:<?php echo $theme['buttons_addto_texthover_color'] ?>;
}
.catalog-product-view .button.btn-cart,.btn-checkout
{
	background-color:<?php echo $theme['buttons_addto_background_color'] ?>;
}
.button.btn-cart:hover
{
	background-color:<?php echo $theme['buttons_addto_bghover_color'] ?>;
}
.checkout-cart-index .btn-proceed-checkout,
.checkout-cart-index button.button2,
.checkout-cart-index .btn-continue,
.checkout-cart-index .btn-update,
.checkout-cart-index .btn-empty{
 background-color:<?php echo $theme['buttons_shopping_background_color'] ?>;
 }
.checkout-cart-index .btn-proceed-checkout:hover,
.checkout-cart-index button.button2:hover,
.checkout-cart-index .btn-continue:hover,
.checkout-cart-index .btn-update:hover,
.checkout-cart-index .btn-empty:hover{
 background-color:<?php echo $theme['buttons_shopping_bghover_color'] ?>;
 }
.checkout-cart-index .main-container .main span, .main-container .main label, th, td
{
 color:<?php echo $theme['shopping_content_text_color'] ?>; 
}
.cart .page-title h1, .shipping h2
{
 color:<?php echo $theme['shopping_product_text_color'] ?>; 
}
.checkout-cart-index h2.product-name a,
.checkout-cart-index h3.product-name a,
.checkout-cart-index h4.product-name a,
.checkout-cart-index h5.product-name a,
.checkout-cart-index p.product-name a
{
 color:<?php echo $theme['shopping_product_name_color'] ?>; 
}
.cart-totals, .cart-forms .discount, .cart-forms .giftcard, .cart-forms .shipping
{
 background-color:<?php echo $theme['shopping_right_background_color'] ?>;
}
header
{
	background-color:<?php echo $theme['header_background_color'] ?>;
}
.logo
{
	background-color:<?php echo $theme['header_logo_background_color'] ?>;
}
.skip-search
{
	background-color:<?php echo $theme['header_search_background'] ?>;
}
#search
{
	color:<?php echo $theme['header_search_text_color'] ?>;
}
#search::-webkit-input-placeholder {
   color: <?php echo $theme['header_search_text_color'] ?>;
}
#search:-moz-placeholder {
   color: <?php echo $theme['header_search_text_color'] ?>;
}
#search::-moz-placeholder {
   color: <?php echo $theme['header_search_text_color'] ?>;
}
#search:-ms-input-placeholder {
   color: <?php echo $theme['header_search_text_color'] ?>;
}
.dropdowntoplink {
  margin-top: <?php echo $theme['header_dropdown_toplink_margintop']."px"; ?>;
  background: <?php echo $theme['header_topbar_background_color']; ?>;
}
.dropdowntoplink .links
{
	text-align: <?php echo $theme['header_dropdown_toplink_alignment']; ?>;
}
.dropdowntoplink .links li a
 {
  color: <?php echo $theme['header_topbar_text_color']; ?>;
  font-size: <?php echo $theme['header_dropdown_toplink_fontsize']."px"; ?>;
 }
 .dropdowntoplink .links li a:hover
 {
  color: <?php echo $theme['header_topbar_texthover_color']; ?>;
   background: <?php echo $theme['header_topbar_texthover_background_color']; ?>;
 }
<?php if($theme['header_dropdown_toplink_option']=="simple"): ?>
.search_main,
.button.search-button
{
	display: block !important;
}
#header-search
{
	top: 40px;
}
<?php endif; ?>
.header-minicart .skip-link .icon,
.skip-account .icon,
.skip-search .icon,
.skip-nav .icon
{
		background: url('<?php echo $this->getSkinUrl('images/icon_sprite_back_blue.png'); ?>');
}
.skip-nav .icon
{
	<?php if($theme['header_icon_color'] == "black"): ?>
		background-position: 0 5px;
	<?php else: ?> 
		background-position: 51px 5px;
	<?php endif; ?>
}
.header-minicart .skip-link .icon
{
	<?php if($theme['header_icon_color'] == "black"): ?>
		background-position: 0 -95px;
	<?php else: ?> 
		background-position: -51px -95px;
	<?php endif; ?>
}
.skip-account .icon
{
	<?php if($theme['header_icon_color'] == "black"): ?>
		background-position: 4px -44px;
	<?php else: ?> 
		background-position: -45px -44px;
	<?php endif; ?>
}
.skip-search .icon
{
	<?php if($theme['header_icon_color'] == "black"): ?>
		background-position: 4px -146px;
	<?php else: ?> 
		background-position: -45px -146px;
	<?php endif; ?>
}
.minicart-wrapper,.header-minicart .subtotal,#header-account.skip-active
{
	background-color:<?php echo $theme['header_dropdown_background_color'] ?>;
}
.minicart-wrapper:hover,
.minicart-wrapper:hover .subtotal,
#header-account.skip-active:hover
{
	background-color:<?php echo $theme['header_dropdown_background_hover'] ?>;
}	
.minicart-wrapper #cart-sidebar .item
{
	background-color:<?php echo $theme['header_dropdown_item_background_color'] ?>;
}
.minicart-wrapper #cart-sidebar .item .btn-edit,.minicart-wrapper #cart-sidebar .item .remove
{
	background-color:<?php echo $theme['header_dropdown_editremove_background'] ?>;
}
.minicart-wrapper #cart-sidebar span,
.minicart-wrapper #cart-sidebar label,
.minicart-wrapper #cart-sidebar th,
.minicart-wrapper #cart-sidebar td,
.minicart-wrapper #cart-sidebar a,
.header-minicart .subtotal .label,
.header-minicart .minicart-actions .cart-link,
.header-minicart #header-cart .block-subtitle,
.header-minicart #header-cart p,
#header-account.skip-active a
{
	color:<?php echo $theme['header_dropdown_text_color'] ?>;
}
#header-cart:hover .block-subtitle,
#header-cart:hover p,
#header-cart:hover .subtotal .label
{
	color:<?php echo $theme['header_dropdown_background_hover_text_color'] ?> !important;
}	
.minicart-wrapper #cart-sidebar a:hover,
#header-cart:hover .minicart-actions .cart-link:hover,	
#header-account.skip-active a:hover
{
	color:<?php echo $theme['header_dropdown_texthover_color'] ?>;
}
.nav-primary
{
	text-align: <?php echo $theme['navigation_menu_alignment'] ?>;
}	
.nav-primary li.level0 li.parent > a:after
{
	border-color:transparent -moz-use-text-color transparent <?php echo $theme['navigation_sub_icon_color'] ?>;
	border-left: 4px solid <?php echo $theme['navigation_sub_icon_color'] ?>;
}
<?php /* ?>
<?php if($theme['navigation_menu_spacing']): ?>
.nav-primary li.level0
{
	margin: 0 <?php echo $theme['navigation_menu_spacing']."px"; ?>;
}
.nav-primary li.level0:last-child
{
	margin-right: 0;
}
.nav-primary li.level0:first-child
{
	margin-left: 0;
}
<?php endif; ?>
<?php */ ?>
.nav-primary a.level0
{
	color:<?php echo $theme['navigation_top_color'] ?>;
	font-size:<?php echo $theme['navigation_top_font_size'].'px' ?>;
	font-family:<?php echo "'".$theme['fonts_navigation']."'" ?>;
}
.nav-primary a.level0:hover
{
		color:<?php echo $theme['navigation_top_hover_color'] ?>;
}
#header-nav
{
	background-color:<?php echo $theme['navigation_top_background_color'] ?>;
}
.nav-primary li.level0 ul
{
	background-color:<?php echo $theme['navigation_sub_container_background'] ?>;
	<?php if($theme['navigation_megamenu_border_color']): ?>
	border:1px solid <?php echo $theme['navigation_megamenu_border_color'] ?>;
	<?php endif; ?>
}
.nav-primary ul.level0 li.parent a
{
		color:<?php echo $theme['navigation_sub_text_color'] ?>;
		font-size: <?php echo $theme['navigation_menu_font_size']."px"; ?>;	
}
.nav-primary ul.level0 li:not(.parent) a
{
	font-size: <?php echo $theme['navigation_menu_font_size']."px"; ?>;
	color:<?php echo $theme['navigation_sub_link_color'] ?>;
}
.nav-primary ul.level0 li:hover
{
	background-color:<?php echo $theme['navigation_sub_link_hover_background'] ?>;
}
.nav-primary ul.level0 li a:hover
{
			color:<?php echo $theme['navigation_sub_link_hover_color'] ?>;
}
<?php if($theme['header_dropdown_toplink_option'] == "simple"): ?>
.skip-links
{
	display: none;
}
<?php else: ?>
.dropdowntoplink
{
	display: block
}
<?php endif; ?>
.footer-container
{
	background-color:<?php echo $theme['footer_background_color'] ?>;
}
.block-title
{
	font-family:<?php echo "'".$theme['fonts_block_title']."'" ?>;
}
.footer-container,.footer p, .footer ul li a,.footer .form-subscribe-header label
{
	color:<?php echo $theme['footer_text_color'] ?>;
}
.footer-container .footer .block-title
{
	border-bottom: 2px solid <?php echo $theme['footer_border_color'] ?>;
    border-top: 2px solid <?php echo $theme['footer_border_color'] ?>;
}
.footer .block-title strong
{
	color:<?php echo $theme['footer_title_color'] ?>;
	font-family:<?php echo "'".$theme['fonts_footer_title']."'" ?>;
}
.footer .links a
{
	color:<?php echo $theme['footer_link_color'] ?>;
}
.footer .links a:hover
{
	color:<?php echo $theme['footer_linkhover_color'] ?>;
	background-color:<?php echo $theme['footer_linkhover_background'] ?>;
}
.footer .lin-k
{
	background-color:<?php echo $theme['footer_newsletter_background'] ?>;
}
.footer button span span
{
	color:<?php echo $theme['footer_button_text_color'] ?>;
}
.footer button
{
	background-color:<?php echo $theme['footer_button_background'] ?> !important;	
}
.footer button:hover span span
{
	color:<?php echo $theme['footer_button_text_hover'] ?>;
}
.footer button:hover
{
	background-color:<?php echo $theme['footer_button_hover_background'] ?> !important;	
}
.footer-container .copyrights
{
	background-color:<?php echo $theme['footer_copyright_background_color'] ?>;
}
.footer-container .copyrights address
{
	color:<?php echo $theme['footer_copyright_text_color'] ?>;
}
.footer-container .copyrights address a
{
	color:<?php echo $theme['footer_copyright_link_color'] ?>;
}
.footer-container .copyrights address a:hover
{
	background-color:<?php echo $theme['footer_copyright_linkhover_background'] ?>;
	color:<?php echo $theme['footer_copyright_linkhover_color'] ?>;
}
.main-container .main
{
	background-color:<?php echo $theme['content_background_color'] ?>;
	border: 1px solid <?php echo $theme['content_border_color'] ?>;
} 
.main-container .main span,.main-container .main label,th,td
{
	color:<?php echo $theme['content_text_color'] ?>;
	font-family:<?php echo "'".$theme['fonts_main']."'" ?>;
}
.main-container .main a
{
	background-color:<?php echo $theme['content_link_background'] ?>;
	color:<?php echo $theme['content_link_col or'] ?>;
}
.main-container .main a:hover
{
	background-color:<?php echo $theme['content_linkhover_background'] ?>;
	color:<?php echo $theme['content_linkhover_color'] ?>;
}
.account-login 
{
	background-color:<?php echo $theme['login_background_color'] ?>;
	background-color:url(<?php echo $this->getSkinUrl('images/'.$theme['login_background_image']); ?>);
}
.home-info
{
	color:<?php echo $theme['homepage_textrow_fontcolor'] ?>;
	background-color:<?php echo $theme['homepage_textrow_background'] ?>;
	font-family:<?php echo "'".$theme['homepage_textrow_font']."'" ?>;
}
.std #accordion1 .slide_handle
{
	background: <?php echo $theme['de_tab_bg_color'] ?>;
	 border: 1px solid <?php echo $theme['de_tab_border_color'] ?>;
}
.std #accordion1 .slide_handle div
{
	color:<?php echo $theme['de_tab_title_color'] ?>;
}
.std #accordion1 .slide_content h3,.std #accordion1 .slide_content h4
{
	color:<?php echo $theme['de_tab_content_title_color'] ?>;
}	
.std #accordion1 .slide_content p
{
	color:<?php echo $theme['de_tab_content_color'] ?>;
}
.toolbar
{
	background-color:<?php echo $theme['toolbar_background_color'] ?>;
}
.toolbar, .pager,.sort-by label
{
	color:<?php echo $theme['toolbar_text_color'] ?> !important;
}
.sort-by > select {
  background-color:<?php echo $theme['toolbar_dropdown_background'] ?>;
  color:<?php echo $theme['toolbar_dropdown_textcolor'] ?>;
}
.pager .limiter > label {
	color:<?php echo $theme['toolbar_text_color'] ?> !important;
}
.pages ol li
{
	background-color:<?php echo $theme['toolbar_pages_links_background'] ?>;
}
.pages ol li:hover
{
	background-color:<?php echo $theme['toolbar_pages_links_hover_background'] ?>;
}
.pages ol li a
{
	color:<?php echo $theme['toolbar_pages_links_textcolor'] ?> !important;
}
.pages ol li a:hover
{
	color:<?php echo $theme['toolbar_pages_links_hover_text'] ?> !important;
}
.limiter select
{
	background-color:<?php echo $theme['toolbar_dropdown_background'] ?>;
	color:<?php echo $theme['toolbar_dropdown_textcolor'] ?>;
}
.wrapper .breadcrumbs
{
	background:<?php echo $theme['breadcrumbs_background_color'] ?>;	
}
.wrapper .breadcrumbs ul li
{
	line-height:<?php echo $theme['breadcrumbs_text_size']."px"; ?>; 
	font-size:<?php echo $theme['breadcrumbs_text_size']."px"; ?>;
}
.wrapper .breadcrumbs ul li a,
.wrapper .breadcrumbs ul li span
{
	color:<?php echo $theme['breadcrumbs_link_color'] ?>;
	font-size:<?php echo $theme['breadcrumbs_text_size']."px"; ?>;
}
.wrapper .breadcrumbs ul li a:hover
{
	color:<?php echo $theme['breadcrumbs_link_hover_color'] ?>;
}
.wrapper .breadcrumbs ul li strong
{
	color:<?php echo $theme['breadcrumbs_link_color'] ?>;
	font-size:<?php echo $theme['breadcrumbs_text_size']."px"; ?>;
}
.catalog-category-view .col-left
{
	<?php if($theme['productlist_block_topborder_color']): ?>
		border-top: 1px solid <?php echo $theme['productlist_block_topborder_color'] ?>;
	<?php endif; ?>
}
.catalog-category-view .col-left .block
{
	<?php if($theme['productlist_block_itemsborder_color']): ?>
		border: 1px solid <?php echo $theme['productlist_block_itemsborder_color'] ?>;
	<?php endif; ?>
	background:<?php echo $theme['productlist_block_background_color'] ?>;
}
.catalog-category-view .col-left .block .block-title span
{
	font-size: <?php echo $theme['productlist_block_title_fontsize']."px"; ?>;
	color:<?php echo $theme['productlist_block_title_color'] ?>;	
}
.catalog-category-view .col-left .block .block-content dt .filter-name
{
	color:<?php echo $theme['productlist_block_text_color'] ?>;
}
.catalog-category-view .col-left .block .block-content dd ol li a,
.catalog-category-view .col-left .block .block-content dd ol li .count,
.catalog-category-view .col-left .block .block-content dd ol li .price
{
	color:<?php echo $theme['productlist_block_link_color'] ?>;	
}
.catalog-category-view .col-left .block .block-content dd ol li a:hover,
.catalog-category-view .col-left .block .block-content dd ol li:hover .count,
.catalog-category-view .col-left .block .block-content dd ol li:hover .price
{
	color:<?php echo $theme['productlist_block_linkhover_color'] ?>;
	background-color:<?php echo $theme['productlist_block_linkhover_background'] ?> !important; 
}
.catalog-category-view .col-left .block .block-content .button span
{
	background: <?php echo $theme['productlist_block_button_background'] ?>;
	color:<?php echo $theme['productlist_block_button_textcolor'] ?>;
}
.catalog-category-view .col-left .block .block-content .button:hover span
{
	background: <?php echo $theme['productlist_block_button_background_hovercolor'] ?>;
	color:<?php echo $theme['productlist_block_button_text_hovercolor'] ?>;
}
.category-products h2.product-name a
{
	color:<?php echo $theme['productlist_product_name_color'] ?>;
	font-size: <?php echo $theme['productlist_product_name_fontsize']."px" ?>; 
}
.category-products .product-name a:hover
{
	color:<?php echo $theme['productlist_producttitle_hover_color'] ?>;
	background-color:<?php echo $theme['productlist_producttitle_hover_background'] ?>;
}
.category-products .price-box .price:hover
{
	color:<?php echo $theme['productlist_productprice_hover_color'] ?>;
}
.category-products .button,
.category-products .add-to-links a
{
	background-color:<?php echo $theme['productlist_grid_addto_background'] ?>;
		color:<?php echo $theme['productlist_addto_textcolor'] ?>;
}
.category-products .products-grid .add-to-links a:hover,
.category-products .products-grid .button:hover
{
	background-color:<?php echo $theme['productlist_grid_addto_hover_background'] ?>;
}
.category-products .button:hover span
{
	color:<?php echo $theme['productlist_addto_texthover'] ?> !important;
}
.category-products .products-list .button:hover
{
	background-color:<?php echo $theme['productlist_list_addto_hover_background'] ?>;
}
.products-list .desc.std:hover
{
	color:<?php echo $theme['productlist_description_texthover'] ?>;
}
.category-products .add-to-links a:hover
{
	color:<?php echo $theme['productlist_addto_texthover'] ?>;
}
.product-view .product-name .h1
{	
	color:<?php echo $theme['productdetails_title_color'] ?>;
}
.product-view .short-description .std,
.product-view .sharing-links li
{
	color:<?php echo $theme['productdetails_text_color'] ?>;
}
.product-view a,.product-view a.link-wishlist
{
	background-color:<?php echo $theme['productdetails_link_background_color'] ?> !important;
	color:<?php echo $theme['productdetails_link_color'] ?> !important;
}
.product-view a.link-wishlist
{
	background: url("<?php echo $this->getSkinUrl(); ?>images/wishlist.jpg") no-repeat scroll left rgba(0, 0, 0, 0);
}a
.product-view a:hover,
.product-view a.link-wishlist:hover
{
		background-color:<?php echo $theme['productdetails_linkhover_background'] ?> !important;
		color:<?php echo $theme['productdetails_linkhover_color'] ?> !important;
}
.product-view .price-box .price, .product-view .price
{
	color:<?php echo $theme['productdetails_price_color'] ?>;
}
.product-view .price-box .old-price .price, .product-view .old-price .price
{
	color:<?php echo $theme['productdetails_oldprice_color'] ?>;
}
.product-view .price-label
{
	color:<?php echo $theme['productdetails_price_textcolor'] ?> !important;
}
#product-attribute-specs-table tbody th
{
	<?php if($theme['productdetails_attribute_border_color']): ?>
		border-bottom: 1px solid <?php echo $theme['productdetails_attribute_border_color']; ?>;
    	border-right: 1px solid <?php echo $theme['productdetails_attribute_border_color']; ?>;
	<?php endif; ?>
}
#product-attribute-specs-table tbody td
{
	<?php if($theme['productdetails_attribute_border_color']): ?>
		border-bottom: 1px solid <?php echo $theme['productdetails_attribute_border_color']; ?>;
	<?php endif; ?>
}
#product-attribute-specs-table tbody th,
#product-attribute-specs-table tbody td
{
	font-size: <?php echo $theme['productdetails_attribute_fontsize']."px"; ?>;
}
#product-attribute-specs-table tbody tr.odd th,
#product-attribute-specs-table tbody tr.odd td
{
	background: <?php echo $theme['productdetails_attribute_odd_background_color']; ?>;
	color: <?php echo $theme['productdetails_attribute_odd_text_color']; ?>;	
}
#product-attribute-specs-table tbody tr.even th,
#product-attribute-specs-table tbody tr.even td
{
	background: <?php echo $theme['productdetails_attribute_even_background_color']; ?>;
	color: <?php echo $theme['productdetails_attribute_even_text_color']; ?>;	
}
.catalog-product-view .product-collateral .toggle-tabs
{
	background-color:<?php //echo $theme['productdetails_tabhead_background'] ?>;
}
#collateral-tabs .tab-content .std,
#collateral-tabs .tab-content .data-table th,
#collateral-tabs .tab-content .data-table td,
#collateral-tabs .data-table tbody td,
#collateral-tabs .data-table tfoot td
{
	font-family: <?php echo $theme['fonts_main'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li
{
	<?php if($theme['productdetails_tabhead_border_color']): ?>
		border: 1px solid <?php echo $theme['productdetails_tabhead_border_color']; ?>;
	<?php endif; ?>
	background-color:<?php echo $theme['productdetails_tabhead_background'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li:first-child
{
	<?php if($theme['productdetails_tabhead_border_color']): ?>
		border: 1px solid <?php echo $theme['productdetails_tabhead_border_color']; ?>;
	<?php endif; ?>
}
.catalog-product-view .product-collateral .toggle-tabs li:last-child
{
	<?php if($theme['productdetails_tabhead_border_color']): ?>
		border: 1px solid <?php echo $theme['productdetails_tabhead_border_color']; ?>;
	<?php endif; ?>
}
.catalog-product-view #collateral-tabs
{
	border: 1px solid <?php echo $theme['productdetails_tabcontent_border_color']; ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li
{
	background-color:<?php echo $theme['productdetails_tabhead_background'] ?>;	
}
.catalog-product-view .product-collateral .toggle-tabs li:hover
{
	background-color:<?php echo $theme['productdetails_tabhead_hover_background'] ?>;
}	
.catalog-product-view .product-collateral .toggle-tabs li > span
{
	color:<?php echo $theme['productdetails_tabhead_textcolor'] ?>;
	/*background: none;*/
}
.catalog-product-view .product-collateral .toggle-tabs li:hover span
{
	color:<?php echo $theme['productdetails_tabhead_texthover_color'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li:hover
{
	background-color:<?php echo $theme['productdetails_tab_hover_background'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li.current
{
	background-color:<?php echo $theme['productdetails_active_tabhead_background'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li.current span
{
	color:<?php echo $theme['productdetails_active_tabhead_text_color'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li.current:hover
{
	background-color:<?php echo $theme['productdetails_active_tabhead_hover_background'] ?>;
}
.catalog-product-view .product-collateral .toggle-tabs li.current:hover span
{
	color:<?php echo $theme['productdetails_active_tabhead_hover_text_color'] ?>;
}
.collateral-tabs,.collateral-tabs .data-table td,.collateral-tabs .data-table th
{
	background-color:<?php echo $theme['productdetails_tabcontent_background'] ?>;
	color:<?php echo $theme['productdetails_tabcontent_textcolor'] ?> !important;
}
.catalog-product-view .tab-content .data-table th
{
	background-color:<?php echo $theme['productdetails_attribute_table_heading_background'] ?>;
}
.catalog-product-view .tab-content a
{
	background-color:<?php echo $theme['productdetails_tabcontent_link_background'] ?> !important;
	color:<?php echo $theme['productdetails_tabcontent_link_color'] ?> !important;
}
.catalog-product-view .tab-content a:hover
{
	background-color:<?php echo $theme['productdetails_tabcontent_linkhover_background'] ?> !important;
	color:<?php echo $theme['productdetails_tabcontent_linkhover_color'] ?> !important;
}
.social_icons_theme1 .facebook
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll left top rgba(0, 0, 0, 0);
}
.social_icons_theme1 .twitter
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -41px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .pinterest
{
	background:  url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -82px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .instagram
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -244px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .foursquare
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll 0 -82px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .fancy
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -81px -123px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .polyvore
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -325px -82px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .yelp
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -243px -163px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .youtube
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll right top rgba(0, 0, 0, 0);
}
.social_icons_theme1 .gplus
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -123px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme1 .linkedin
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -203px 0 rgba(0, 0, 0, 0);
}
.social_icons_theme1 .tumbler
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme1.jpg' ?>") no-repeat scroll -123px -41px rgba(0, 0, 0, 0);
}

.social_icons_theme2 .facebook
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll left top rgba(0, 0, 0, 0);
}
.social_icons_theme2 .twitter
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -41px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .pinterest
{
	background:  url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -82px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .instagram
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -244px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .foursquare
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll 0 -82px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .fancy
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -81px -123px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .polyvore
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -325px -82px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .yelp
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -243px -163px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .youtube
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll right top rgba(0, 0, 0, 0);
}
.social_icons_theme2 .gplus
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -123px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme2 .linkedin
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -203px 0 rgba(0, 0, 0, 0);
}
.social_icons_theme2 .tumbler
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme2.jpg' ?>") no-repeat scroll -123px -41px rgba(0, 0, 0, 0);
}

.social_icons_theme3 .facebook
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -6px -8px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .twitter
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -56px -59px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .pinterest
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -259px -8px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .instagram
{
	background:url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -208px -8px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .foursquare
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .fancy
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .polyvore
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .yelp
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -208px -109px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .youtube
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -455px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .gplus
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?> ") no-repeat scroll -157px -8px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .linkedin
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -455px -103px rgba(0, 0, 0, 0);
}
.social_icons_theme3 .tumbler
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme3.png' ?>") no-repeat scroll -189px -103px rgba(0, 0, 0, 0);
}
	
.social_icons_theme4 .facebook
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll 0 -1px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .twitter
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -44px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .pinterest
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -88px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .instagram
{
	background:url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -221px -91px rgba(0, 0, 0, 0)
}
.social_icons_theme4 .foursquare
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -266px -45px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .fancy
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .polyvore
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .yelp
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -221px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .youtube
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -133px -46px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .gplus
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -133px -1px rgba(0, 0, 0, 0)
}
.social_icons_theme4 .linkedin
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll -177px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme4 .tumbler
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme4.png' ?>") no-repeat scroll right top rgba(0, 0, 0, 0);
}
	
.social_icons_theme5 .facebook
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll 0 -1px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .twitter
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -51px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .pinterest
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -103px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .instagram
{
	background:url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -258px -104px rgba(0, 0, 0, 0)
}
.social_icons_theme5 .foursquare
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -309px -53px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .fancy
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .polyvore
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -366px -192px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .yelp
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -258px -1px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .youtube
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -154px -53px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .gplus
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -154px -1px rgba(0, 0, 0, 0)
}
.social_icons_theme5 .linkedin
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll -206px 0px rgba(0, 0, 0, 0);
}
.social_icons_theme5 .tumbler
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme5.png' ?>") no-repeat scroll right top rgba(0, 0, 0, 0);
}

.social_icons_theme6 .facebook
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -55px -13px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .twitter
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -8px -13px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .pinterest
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -55px -129px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .instagram
{
	background:url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -9px -246px rgba(0, 0, 0, 0)
}
.social_icons_theme6 .foursquare
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -242px -244px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .fancy
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -102px -203px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .polyvore
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -100px -285px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .yelp
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -101px -51px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .youtube
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -147px -50px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .gplus
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -7px -130px rgba(0, 0, 0, 0)
}
.social_icons_theme6 .linkedin
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -101px -166px rgba(0, 0, 0, 0);
}
.social_icons_theme6 .tumbler
{
	background: url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'evolved/social/social_icons_theme6.png' ?>") no-repeat scroll -100px -129px rgba(0, 0, 0, 0);
}
		
.sidebar .block
{
	border-top:1px solid <?php echo $theme['sidebar_block_topborder_color'] ?>;
	background-color:<?php echo $theme['sidebar_block_background_color'] ?>;
}
.sidebar .block .block-title span
{
	color:<?php echo $theme['sidebar_block_title_color'] ?>;
	font-size:<?php echo $theme['sidebar_block_title_fontsize']."px" ?>;
}
.sidebar .block .item
{
	border:1px solid <?php echo $theme['sidebar_block_itemsborder_color'] ?>;
}
.sidebar .block a
{
	color:<?php echo $theme['sidebar_block_link_color'] ?>;
}
.sidebar .block a:hover,
.gan-list-checkbox a:hover span
{
	color:<?php echo $theme['sidebar_block_linkhover_color'] ?>;
	background-color:<?php echo $theme['sidebar_block_linkhover_background'] ?>;
}
.sidebar .block button.button
{
	background-color:<?php echo $theme['sidebar_button_background'] ?> !important;
}
.sidebar .block button.button span
{
		color:<?php echo $theme['sidebar_button_textcolor'] ?>;
}
.sidebar .block button.button:hover
{
	background-color:<?php echo $theme['sidebar_button_background_hovercolor'] ?> !important;
}
.sidebar .block button.button:hover span
{
	color:<?php echo $theme['sidebar_button_text_hovercolor'] ?>;
}
.sidebar .block #pollForm .block-subtitle
{
	background-color:<?php echo $theme['sidebar_poll_question_background'] ?>;
	color:<?php echo $theme['sidebar_poll_question_textcolor'] ?>;
}
#contactForm h2.legend
{
	font-family:<?php echo "'".$theme['contacts_title_font']."'" ?>;
	color:<?php echo $theme['contacts_title_fontcolor'] ?>;
}
.Contct_Addrress .cnt-addrs .cnt-adres-text,
.Contct_Addrress .cnt-addrs .cnt-title,
#contactForm .fieldset .fields label
{
		font-family:<?php echo "'".$theme['contacts_content_font']."'" ?>;
		color:<?php echo $theme['contacts_content_fontcolor'] ?>;
}
.inline2.cboxElement {
	background-color:<?php echo $theme['contacts_appointment_background'] ?>;
	font-family:<?php echo "'".$theme['contacts_appointment_font']."'" ?>;
    color: <?php echo $theme['contacts_appointment_fontcolor'] ?>;
}
.home-main.featured-tabs .toggle-tabs
{
	background: <?php echo $theme['general_main_color']; ?>
}
.logo {
	/*width: auto;
	min-height: 0;
	max-width: 100%;*/
	/*max-width: 170px;
    min-height: 0px;*/
	/*margin:<?php //if($theme['header_logo_placement']=="center"){ echo "0 38%"; } else { echo "8px 0 0 0"; } ?>*/
	margin-left:<?php if($theme['header_logo_placement']=="center"){ echo "36%"; } else { echo "0"; } ?>;
	margin-right:<?php if($theme['header_logo_placement']=="center"){ echo "38%"; } else { echo "0"; } ?>;
	margin-top:<?php echo $theme['margin_above_logo']."px" ?>;
}
.logo img {
	/*max-width: 100%;
    min-height: 65px;
    min-width: 170px;
    opacity: 1;
    width: 170px;*/
	float:<?php if($theme['header_logo_placement']=="center"){ echo "none"; } else { echo "left"; } ?>;
}
@media only screen and (max-width: 900px) and (min-width: 771px)
{
	.logo{
	/*	margin-left:32%;
		margin-right:22%;*/
		margin-top:<?php echo $theme['margin_above_logo']?>;
		margin-right: <?php if($theme['header_logo_placement']=="center"){ echo "22%"; } ?>
		margin-left: <?php if($theme['header_logo_placement']=="center"){ echo "32%"; } ?>
		
	}
}
@media only screen and (max-width: 770px)
{
	#nav .nav-primary li.parent.sub-menu-active > a:after, .nav-primary li.parent.menu-active > a:after
	{
		border-color: <?php echo $theme['navigation_sub_icon_color'] ?> transparent -moz-use-text-color;
		border-top: 5px solid <?php echo $theme['navigation_sub_icon_color'] ?>;
		border-left: 5px solid Transparent;
	}
	#nav .nav-primary li.level0.parent.sub-menu-active > a:after, .nav-primary li.level0.parent.menu-active > a:after
	{
		content: none;
	}	
	<?php if($theme['header_responsive_logo_placement'] == "center"): ?>
	.logo img
	{
		float:none;
	}
	<?php else: ?>
	.logo img
	{
		float:left;
	}
	<?php endif; ?>
	.nav-primary ul.level0 li a:hover
	{
		background: <?php echo $theme['navigation_sub_link_hover_background']; ?>;
	}
	.skip-search
	{
		background: <?php echo $theme['header_topbar_background_color']; ?>;
	}
	.skip-search:hover
	{
		background: <?php echo $theme['header_topbar_texthover_background_color']; ?>;
	}
	<?php if($theme['header_dropdown_toplink_option'] == "simple"): ?>
	.skip-links
	{
		display: block;
	}
	.skip-account,
	.skip-cart
	{
		display: none;
	}
	.skip-nav {
		width: 75%;
		text-align: left;
		padding-left: 22px;
	}
	.dropdowntoplink
	{
		z-index: 1111;
		display: block;
		position: fixed;
	}
	.cms-index-index header
	{
		margin-top: 37px;
	}
	#header-search
	{
		z-index: 1111;
	}
	<?php else: ?>
	.dropdowntoplink
	{
		display: none;
	}
	<?php endif; ?>
}
@media only screen and (max-width: 499px)
{
	<?php if($theme['header_dropdown_toplink_option'] == "simple"): ?>
	.skip-links
	{
		display: block;
	}
	.skip-account,
	.skip-cart
	{
		display: none;
	}
	.skip-nav {
		width: 80%;
	}
	<?php else: ?>
	.dropdowntoplink
	{
		display: none;
	}
	<?php endif; ?>
}
</style>