<?php
/**
 * Magic Logix Gallery
 *
 * Provides an image gallery extension for Magento
 *
 * @category		MLogix
 * @package		Gallery
 * @author		Brady Matthews
 * @copyright		Copyright (c) 2008 - 2010, Magic Logix, Inc.
 * @license		http://creativecommons.org/licenses/by-nc-sa/3.0/us/
 * @link		http://www.magiclogix.com
 * @link		http://www.magentoadvisor.com
 * @since		Version 1.0
 *
 * Please feel free to modify or distribute this as you like,
 * so long as it's for noncommercial purposes and any
 * copies or modifications keep this comment block intact
 *
 * If you would like to use this for commercial purposes,
 * please contact me at brady@magiclogix.com
 *
 * For any feedback, comments, or questions, please post
 * it on my blog at http://www.magentoadvisor.com/plugins/gallery/
 *
 */
?><?php
$items = $this->getGallery();

$cat_thumbWidth = 160;
$cat_thumbHeight = 120;

$thumbWidth = 107;
$thumbHeight = 80;

$numItems = 0;
?>
<div class="gallery_wrapper">



	<div class="categories">
<?php


if(count($items))
foreach($items as $item)
{

	if($item->hasChildren())
	{
?>	
<div class="category">	
	<a href="<?=$this->getViewUrl($item->getId())?>"><img width="<?=$cat_thumbWidth?>" height="<?=$cat_thumbHeight?>" src="<?=$item->getThumbnail($cat_thumbWidth,$cat_thumbHeight)?>" title="<?=$item->getTitle()?>" alt="<?=$item->getAlt()?>"/></a>
	<div class="title"><?=$item->getTitle()?></div>
</div>

<?php
	}
	else $numItems++;
}
?>
		<div class="clearfix"></div>
	</div>
<?php if($numItems) { ?>
	<div class="items">

		<div class="navigation-container">
			<div id="thumbs" class="navigation">
				<a class="pageLink prev" style="visibility: hidden;" href="#" title="Previous Page"></a>
				<ul class="thumbs noscript">

<?php
if(count($items))
foreach($items as $item)
{

	if(!$item->hasChildren())
	{
?>	
			        <li>
			            <a class="thumb" href="<?=$item->getImageUrl()?>" title="<?=$item->getTitle()?>">
							<img src="<?=$item->getThumbnail($thumbWidth,$thumbHeight)?>" title="<?=$item->getTitle()?>" alt="<?=$item->getAlt()?>"/>		            		                
			            </a>
			            <div class="caption">
			            	<div class="image-title"><?=$item->getTitle()?></div>
			                <div class="image-desc"><?=$item->getDescription()?></div>
			                <div class="download">
			                	<a href="<?=$item->getImageUrl()?>">Download Original</a>
			                </div>
			            </div>
			        </li>
<?php
	}
}
?>
				</ul>
				<a class="pageLink next" style="visibility: hidden;" href="#" title="Next Page"></a>
			</div>
		</div>	
	
		<div class="content">
			<div class="slideshow-container">
				<div id="controls" class="controls"></div>
				<div id="loading" class="loader"></div>
				<div id="slideshow" class="slideshow"></div>
			</div>
			<div id="caption" class="caption-container">

				<div class="photo-index"></div>
			</div>
		</div>
						
		<div style="clear: both;"></div>
	</div>
	
	

<script type="text/javascript">
			jQuery(document).ready(function($) {
				// We only want these styles applied when javascript is enabled
				$('div.content').css('display', 'block');

				// Initially set opacity on thumbs and add
				// additional styling for hover effect on thumbs
				var onMouseOutOpacity = 0.67;
				$('#thumbs ul.thumbs li, div.navigation a.pageLink').opacityrollover({
					mouseOutOpacity:   onMouseOutOpacity,
					mouseOverOpacity:  1.0,
					fadeSpeed:         'fast',
					exemptionSelector: '.selected'
				});
				
				// Initialize Advanced Galleriffic Gallery
				var gallery = $('#thumbs').galleriffic({
					forceWidth:                500,
					delay:                     2500,
					numThumbs:                 7,
					preloadAhead:              10,
					enableTopPager:            false,
					enableBottomPager:         false,
					imageContainerSel:         '#slideshow',
					controlsContainerSel:      '#controls',
					captionContainerSel:       '#caption',
					loadingContainerSel:       '#loading',
					renderSSControls:          true,
					renderNavControls:         true,
					playLinkText:              'Play Slideshow',
					pauseLinkText:             'Pause Slideshow',
					prevLinkText:              '&lsaquo; Previous Photo',
					nextLinkText:              'Next Photo &rsaquo;',
					nextPageLinkText:          'Next &rsaquo;',
					prevPageLinkText:          '&lsaquo; Prev',
					enableHistory:             false,
					autoStart:                 false,
					syncTransitions:           true,
					defaultTransitionDuration: 900,
					onSlideChange:             function(prevIndex, nextIndex) {
						// 'this' refers to the gallery, which is an extension of $('#thumbs')
						this.find('ul.thumbs').children()
							.eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
							.eq(nextIndex).fadeTo('fast', 1.0);

						// Update the photo index display
						this.$captionContainer.find('div.photo-index')
							.html('Photo '+ (nextIndex+1) +' of '+ this.data.length);
					},
					onPageTransitionOut:       function(callback) {
						this.fadeTo('fast', 0.0, callback);
					},
					onPageTransitionIn:        function() {
						var prevPageLink = this.find('a.prev').css('visibility', 'hidden');
						var nextPageLink = this.find('a.next').css('visibility', 'hidden');
						
						// Show appropriate next / prev page links
						if (this.displayedPage > 0)
							prevPageLink.css('visibility', 'visible');

						var lastPage = this.getNumPages() - 1;
						if (this.displayedPage < lastPage)
							nextPageLink.css('visibility', 'visible');

						this.fadeTo('fast', 1.0);
					}
				});

				/**************** Event handlers for custom next / prev page links **********************/

				gallery.find('a.prev').click(function(e) {
					gallery.previousPage();
					e.preventDefault();
				});

				gallery.find('a.next').click(function(e) {
					gallery.nextPage();
					e.preventDefault();
				});


			});

</script>
	
	
	
<?php } ?>
</div>
<?php

/*
Lightbox method

<a title="<?=$item->getDescription()?>" href="<?=$item->getImageUrl()?>" rel="prettyPhoto[<?=$this->getCurrentGallery()->getId()?>]">
<img width="<?=$thumbWidth?>" height="<?=$thumbHeight?>" src="<?=$item->getThumbnail($thumbWidth,$thumbHeight)?>" title="<?=$item->getTitle()?>" alt="<?=$item->getAlt()?>"/>
</a>
*/