<?php
/*
 * Copyright 2013-2015 Price Waiter, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
?>
<?php
$enabled = $this->getIsEnabled();
$ctEnabled = $this->getIsConversionToolsEnabled();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">PriceWaiter Widget</h4>
    </div>
    <div class="fieldset fieldset-wide" id="group_pricewaiter">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>

                <tr>
                    <td class="label"><label for="group_pricewaiter_enabled">Enabled</label></td>
                    <td class="value">
                        <select id="group_pricewaiter_enabled" name="pricewaiter[enabled]" class=" select">
                            <option value="1" <?php if ($enabled): ?>selected="selected"<?php endif; ?>>Yes</option>
                            <option value="0" <?php if (!$enabled): ?>selected="selected"<?php endif; ?>>No</option>
                        </select>
                    </td>
                    <td class="scope-label">
                        <span class="nobr">[STORE VIEW]</span>
                    </td>
                </tr>

                <tr>
                    <td class="label"><label for="group_pricewaiter_conversion_tools_enabled">Conversion Tools Enabled</label></td>
                    <td class="value">
                        <select id="group_pricewaiter_conversion_tools_enabled" name="pricewaiter[ct_enabled]" class=" select">
                            <option value="1" <?php if ($ctEnabled): ?>selected="selected"<?php endif; ?>>Yes</option>
                            <option value="0" <?php if (!$ctEnabled): ?>selected="selected"<?php endif; ?>>No</option>
                        </select>
                    </td>
                    <td class="scope-label">
                        <span class="nobr">[STORE VIEW]</span>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>
