<?php 
$resource = Mage::getConfig()->getNode('global/resources')->asArray();
$magento_db = $resource['default_setup']['connection']['host'];
$mdb_user = $resource['default_setup']['connection']['username'];
$mdb_passwd = $resource['default_setup']['connection']['password'];
$mdb_name = $resource['default_setup']['connection']['dbname'];

//developm_magento
$magento_connection = @mysql_connect($magento_db, $mdb_user, $mdb_passwd);
if (!$magento_connection)
{
	die('Unable to connect to the database');
}
@mysql_select_db($mdb_name, $magento_connection) or die ("Database not found.");

$table = Mage::getSingleton('core/resource')->getTableName('uploadtool_settings');
$query = "SELECT * FROM `$table` where `field` = 'polygon_id' LIMIT 1";

$result = @mysql_db_query($mdb_name, $query) or die("Failed Query of ".$query);

$PolygonId = "";
$row = mysql_fetch_array($result);
$PolygonId = $row['value'];

?>
<div class="entry-edit">
    <div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend">Import From Polygon FTP</h4>
	    <div class="form-buttons"></div>
	</div>
	<div id="polygon" class="fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
				        <td class="label"><label for="polygon_id">Polygon User ID:</label></td>
				    	<td class="value" colspan="2">
				    		<ul>
				    			<li>
				        			<input type="text" class="input-text" value="<?php echo $PolygonId; ?>" name="settings[polygon_id]" id="polygon_id">
				        		</li>
					        	<li>
				         			<button style="" onclick="editForm.submit()" class="scalable save" type="button" title="Save">
				         				<span><span><span>Save</span></span></span>
				         			</button>
			         			</li>
			         		</ul>            
				        </td>
				    </tr>
				    <tr>
				    	<td class="label" colspan="3">&nbsp;</td>
					</tr>
					<tr>
		        		<td class="label">
			        		<button onclick="setLocation('<?php echo $this->getUrl("uploadtool/adminhtml_uploadtool/importPolygon"); ?>')" class="scalable go" type="button" title="<?php echo $this->__("Update RapNet Diamonds") ?>">
			        			<span><span><span><?php echo $this->__("Import Polygon") ?></span></span></span>
			        		</button>
		        		</td>
					
						<td class="label">
			        		<button onclick="setLocation('<?php echo $this->getUrl("uploadtool/adminhtml_uploadtool/deleteDiamonds",array('source'=>'polygon')); ?>')" class="scalable delete" type="button" title="<?php echo $this->__("Delete Polygon Diamonds") ?>"><span><span><span><?php echo $this->__("Delete Polygon Diamonds") ?></span></span></span></button>
		        		</td>
					
						<?php 
						$path = Mage::getBaseDir("var") . DS ."import" . DS . "polygon" . DS;
						
						if($PolygonId && file_exists($path.$PolygonId.".csv")): ?>
							<td class="label">
				        		<button onclick="setLocation('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'var/import/polygon/'.$PolygonId.'.csv'; ?>')" class="scalable go" type="button" title="<?php echo $this->__("Download Polygon CSV") ?>"><span><span><span><?php echo $this->__("Download Polygon CSV") ?></span></span></span></button>
			        		</td>
						<?php endif; ?>
					</tr>
				</tbody>
			</table>
	    </div>
	</div>
</div>
