<?php 
$resource = Mage::getConfig()->getNode('global/resources')->asArray();
$magento_db = $resource['default_setup']['connection']['host'];
$mdb_user = $resource['default_setup']['connection']['username'];
$mdb_passwd = $resource['default_setup']['connection']['password'];
$mdb_name = $resource['default_setup']['connection']['dbname'];

//developm_magento
$magento_connection = @mysql_connect($magento_db, $mdb_user, $mdb_passwd);
if (!$magento_connection)
{
	die('Unable to connect to the database');
}
@mysql_select_db($mdb_name, $magento_connection) or die ("Database not found.");

$table = Mage::getSingleton('core/resource')->getTableName('uploadtool_settings');
$query = "SELECT * FROM `$table`";

$result = @mysql_db_query($mdb_name, $query) or die("Failed Query of ".$query);

$currentTheme = "";

while($row = mysql_fetch_array($result))
{
	if($row['field'] == 'jewelerslink_diamondsearch_theme') {
		$currentTheme = $row['value'];
	}
	if($row['field'] == 'jewelerslink_diamondsearch_slidercolor') {
		$sliderColor = $row['value'];
	}
}
?>
<div class="entry-edit">
    <div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend">Diamond Search Settings</h4>
	    <div class="form-buttons"></div>
	</div>
	<div id="uploadtool_settings" class="fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
			<tbody>
			    <tr>
			        <td class="label"><label for="jewelerslink_diamondsearch_theme">Diamond Search Theme:</label></td>
			    	<td class="value">
			        	<?php $themes = Mage::getModel('uploadtool/system_themes')->toOptionArray(); ?>
			        	<select name="settings[jewelerslink_diamondsearch_theme]" id="jewelerslink_diamondsearch_theme">
			        		<?php foreach($themes as $theme): ?>
			        			<option value="<?php echo $theme ?>" <?php if($theme == $currentTheme): ?> selected="selected" <?php endif; ?>><?php echo $theme ?></option>
			        		<?php endforeach; ?>
			        	</select>            
			        </td>
			    </tr>
			    <tr>
			        <td class="label"><label for="jewelerslink_diamondsearch_theme">Diamond Search Slider Color:</label></td>
			    	<td class="value">
			        	<input type="text" class="color" name="settings[jewelerslink_diamondsearch_slidercolor]" id="jewelerslink_diamondsearch_slidercolor" value="<?php echo $sliderColor; ?>">     
			        </td>
			    </tr>
			</tbody>
			</table>
	    </div>
	</div>
</div>