<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>evolved/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>evolved/jquery.noconflict.js"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>evolved/jquery.mColorPicker.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>evolved/colorScroll/jquery-ui.js"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>evolved/evolved_setting.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('evolved/evolvedadmin.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->getJsUrl() ?>evolved/colorScroll/jquery-ui.css" />