<?php
/**
 * TurnkeyE Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0).
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to obtain it through the world-wide-web, please send
 * an email to info@turnkeye.com so we can send you a copy immediately.
 *
 * @category   Turnkeye
 * @package    Turnkeye_All
 * @copyright  Copyright (c) 2010-2012 TurnkeyE Co. (http://turnkeye.com)
 * @license    here license
 */

/**
 * template of about tab
 *
 * @category   Turnkeye
 * @package    Turnkeye_All
 * @author     Viacheslav Fedorenko <v.fedorenko@turnkeye.com>
 *
 * @var $this Turnkeye_All_Block_System_Config_Form_Fieldset_About_Fields
 */
?>
<div class="turnkeye-about-logo">
    <img src="<?php echo $this->getSkinUrl('turnkeye/all/images/turnkeye_logo.png') ?>">
</div>
<div class="turnkeye-about-info">
    <?php echo $this->__($this->helper('turnkeye_all')->getAboutText()); ?>
    <br /><br/>
    <img src="<?php echo $this->getSkinUrl('turnkeye/all/images/turnkeye_about.png') ?>">
</div>