<?php
/**
 * TurnkeyE Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0).
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to obtain it through the world-wide-web, please send
 * an email to info@turnkeye.com so we can send you a copy immediately.
 *
 * @category   Turnkeye
 * @package    Turnkeye_All
 * @copyright  Copyright (c) 2010-2012 TurnkeyE Co. (http://turnkeye.com)
 * @license    here license
 */

/**
 * template of installed company's extension
 *
 * @category   Turnkeye
 * @package    Turnkeye_All
 * @author     Viacheslav Fedorenko <v.fedorenko@turnkeye.com>
 *
 * @var $this Turnkeye_All_Block_System_Config_Form_Fieldset_Modules_Fields
 */
?>

<?php $extensions = $this->getExtensions(); ?>
<?php if (count($extensions)): ?>
    <table class="turnkeye-extensions">
        <?php foreach ($extensions as $e): ?>
        <tr>
            <td class="extension-name"><?php echo $e['label']; ?></td>
            <td class="extension-version"><?php echo $e['version']; ?></td>
            <td class="extension-action"><?php if ($e['checkurl']): ?><a href="<?php echo $e['checkurl']; ?>" target="_blank"><?php echo $this->__('Check Updates'); ?></a><?php else: ?>&nbsp;<?php endif; ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <?php echo $this->__('No Extensions found'); ?>
<?php endif; ?>