<?php
    
    $helper = Mage::helper('ranvi_feed');
	
?>
<div style="" id="ranvi_feed_tabs_import_section_content"><div class="entry-edit">
    <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $helper->__('Import Mapping');?></h4>
    <div class="form-buttons"></div>
</div>
    <div id="main_fieldset" class="fieldset ">
    <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
            <tbody>
                <tr>
        <td class="label"><label for="mappingfile"><?php echo $helper->__('Mapping File');?><span class="required">*</span></label></td>
    <td class="value" style="width:230px">
        <input type="file" class=" required-entry" title="<?php echo $helper->__('Mapping File');?>" value="" name="mappingfile" id="mappingfile">
    </td>
    <td  class="value"><span id="continue_button"><button style="" onclick="editForm.submit();return false;" class="scalable save" type="submit" id="id_944658684ee4dd3285bd2f1c924b3fc9"><span><?php echo $helper->__('Import');?></span></button></span></td>
    </tr>
            </tbody>
        </table>
            </div>
        </div>
</div>
</div>