<table cellspacing="0" class="form-list">
    <tr>
        <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Name') ?></label></td>
        <td class="value">
            <?php if ($this->customer_view_url) : ?>
                <a href="<?php echo $this->customer_view_url ?>" target="_blank"><strong><?php echo $this->htmlEscape($this->order->getCustomerName()) ?></strong></a>
            <?php else: ?>
                <strong><?php echo $this->htmlEscape($this->order->getCustomerName()) ?></strong>
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <td class="label"><label><?php echo Mage::helper('sales')->__('Email') ?></label></td>
        <td class="value"><a href="mailto:<?php echo $this->order->getCustomerEmail() ?>"><strong><?php echo $this->order->getCustomerEmail() ?></strong></a></td>
    </tr>
    <?php if ($this->group_name) : ?>
        <tr>
            <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Group') ?></label></td>
            <td class="value"><strong><?php echo $this->group_name; ?></strong></td>
        </tr>
    <?php endif; ?>
    <?php foreach ($this->customer_account_data as $data):?>
        <tr>
            <td class="label"><label><?php echo $data['label'] ?></label></td>
            <td class="value"><strong><?php echo $data['value'] ?></strong></td>
        </tr>
    <?php endforeach;?>
</table>
