<?php $theme = Ideal_Evolved_Block_Evolved::getConfig(); ?>
<?php if($theme['homepage_element_1_special_enabled'] == 1): ?>
<script>
(function($) {
    $(function() {
        var jcarousel = $('.specialtab .jcarousel');

        jcarousel
            .on('jcarousel:reload jcarousel:create', function () {
                var width = jcarousel.innerWidth();

                if (width >= 600) {
                    width = width / 4;
                } else if (width >= 350) {
                    width = width / 2;
                }

                jcarousel.jcarousel('items').css('width', width + 'px');
            })
            .jcarousel({
                wrap: 'circular'
            });

        $('.specialtab .jcarousel-control-prev')
            .jcarouselControl({
                target: '-=1'
            });

        $('.specialtab .jcarousel-control-next')
            .jcarouselControl({
                target: '+=1'
            });

        $('.specialtab .jcarousel-pagination')
            .on('.specialtab jcarouselpagination:active', 'a', function() {
                $(this).addClass('active');
            })
            .on('jcarouselpagination:inactive', 'a', function() {
                $(this).removeClass('active');
            })
            .on('click', function(e) {
                e.preventDefault();
            })
            .jcarouselPagination({
                perPage: 1,
                item: function(page) {
                    return '<a href="#' + page + '">' + page + '</a>';
                }
            });
    });
})(jQuery);
</script> 
<?php
$_productCollection = Mage::getModel('catalog/product')->getCollection();
$_productCollection->addAttributeToSelect(array(
                                   'image',
                                   'name',
                                   'short_description'
                   ))
                   ->addFieldToFilter('visibility', array(
                               Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
                               Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                   )) //showing just products visible in catalog or both search and catalog
                   ->addFinalPrice()
//                        ->addAttributeToSort('price', 'asc') //in case we would like to sort products by price
                   ->getSelect()
                   ->where('price_index.final_price < price_index.price')
//                        ->limit(30) //we can specify how many products we want to show on this page
//                        ->order(new Zend_Db_Expr('RAND()')) //in case we would like to sort products randomly
                   ;
//echo count($_productCollection);
?>
<?php //if (($_productCollection = $this->getProductCollection()) && $_productCollection->getSize()): ?>
<?php if(count($_productCollection) != 0): ?>
<div class="specialtab">
<div class="jcarousel-wrapper">
       <div class="jcarousel">
            <ul>
            	<?php foreach ($_productCollection as $_product): ?>
    			<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
	                <li>
	                	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
			                <?php $_imgwidth = 150; 
			                ?>
			                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
			                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgwidth); ?>"
			                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			            </a>
			              <a href="<?php echo $_product->getProductUrl() ?>"><span class="product-name"><?php echo $_product->getName(); ?></span></a>
			              <?php $currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();  
			               		$currency_symbol = Mage::app()->getLocale()->currency( $currency_code )->getSymbol(); ?>
  			            <span class="product-price"><?php echo $currency_symbol.number_format($_product->getFinalPrice(),2); ?></span>
			         </li>
		        <?php endforeach; ?>
           </ul>
       </div>
	       <a href="#" class="jcarousel-control-prev"><!-- &lsaquo;  --></a>
	       <a href="#" class="jcarousel-control-next"><!-- &rsaquo;  --></a>
	       <p class="jcarousel-pagination"></p>
</div>
</div>
<?php endif; ?>
<?php endif; ?>