<?php

	$feed = $this->getFeed();

	$type=$this->getRequest()->getParam('type');
	
	if($data = $this->getFeed()->getContent()){
		
		$data = json_decode($data, true);
		
	}else if($type == 'amazon'){

		$data = Mage::helper('ranvi_feed')->getAmazonContentJson();
		$data =json_decode($data, true);

	}else if($type == 'google'){

		$data = Mage::helper('ranvi_feed')->getGoogleContentJson();
		$data =json_decode($data, true);

	}else{

		$data = array();

	}
	
	if(empty($data)){
		$rows_count = 5;
	}else{
		$rows_count = count($data);
	}
	
?>
<?php for($i=0;$i<$rows_count;$i++):?>
    <tr>
    	<td><div style="padding:0 2px;border-color:#AAAAAA #C8C8C8 #C8C8C8 #AAAAAA;border-style:solid;border-width:1px;"><input style="width:100%;border:0;padding:0;" type="text" class="input-text" name="field[<?php echo $i;?>][order]" value="<?php echo @$data[$i]['order'];?>" /></div></td>
    	 <td ><div style="padding:0 2px;border-color:#AAAAAA #C8C8C8 #C8C8C8 #AAAAAA;border-style:solid;border-width:1px;"><input style="width:100%;border:0;padding:0;" type="text" class="input-text" name="field[<?php echo $i;?>][name]" value="<?php echo @$data[$i]['name'];?>" /></div></td>
    	<td>
    		<input style="width:98%;display:<?php echo isset($data[$i]['type']) && $data[$i]['type'] == 'static' ? 'block' : 'none';?>;"  id="mapping-<?php echo $i;?>-static-value" type="text" class="input-text" name="field[<?php echo $i;?>][static_value]" value="<?php echo @$data[$i]['static_value'] ?>" />
    		<?php echo Ranvi_Feed_Block_Adminhtml_Items_Edit_Tab_Content_Csv::getAttributeSelect($i, @$data[$i]['attribute_value'], (isset($data[$i]['type']) && $data[$i]['type'] == 'attribute' || !isset($data[$i]['type'])))?>
        </td>
    	<td><button onclick="removeMappingRow(this);return false;" class="button"><span><span><?php echo $this->__('Remove')?></span></span></button></td>
    </tr>
<?php endfor;?>