<?php
$this->setCustomShippingPrice(Mage::getSingleton('core/session')->getCustomshippriceAmount());
$this->setCustomTitle(Mage::getSingleton('core/session')->getCustomshippriceDescription());
?>
<?php if($_shippingRateGroups = $this->getShippingRates()): ?>
    <div id="order-shipping-method-choose" style="display:none">
    <dl class="shipment-methods">
    <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
        <?php if ($code == 'customshipprice'): ?>
        <dt><strong><?php echo $this->getCarrierName($code) ?></strong></dt>
        <dd style="margin-top:1em">
            <ul>
            <?php foreach ($_rates as $_rate): ?>
                <?php $_code=$_rate->getCode() ?>
                <li>
                   <?php if ($_rate->getErrorMessage()): ?>
                        <ul class="messages">
                            <li class="error-msg"><?php echo $_rate->getErrorMessage() ?></li>
                        </ul>
                   <?php else: ?>
                        
						<span style="font-size:18px;font-weight:bold;float:left;margin-top:2px;">*</span>
						<label class="normal" for="s_method_<?php echo $_code ?>">
                            
                            <div style="float:left;">&nbsp;&nbsp;&nbsp;&nbsp;<strong><?php echo $this->__('Title:'); ?></strong>&nbsp;&nbsp;&nbsp;<input id="custom-shipping-title" type="text" style="width: 100px;" value="<?php echo $this->getCustomTitle() ?>" /></div>
							
							<div style="float:left;">&nbsp;&nbsp;&nbsp;&nbsp;<strong><?php echo $this->__('Rate:'); ?></strong>&nbsp;&nbsp;<input id="custom-shipping-rate" type="text" class="" style="width:80px;" value="<?php if ($this->getCustomShippingPrice()): echo sprintf("%.2f", $this->getCustomShippingPrice()); endif; ?>" />
							&nbsp;&nbsp;<button id="custom-shipping-button" type="button" class="scalable " onclick="order.setCustomShippingValues(document.getElementById('custom-shipping-rate').value,document.getElementById('custom-shipping-title').value,'customshipprice_customshipprice');return false"><span><?php echo $this->__('Update'); ?></span></button></div>
						 </label>
						 <br/>
						 
                   <?php endif; ?>
                </li>
            <?php endforeach; ?>
            </ul>
           
            <script type="text/javascript">
                //<![CDATA[
                AdminOrder.addMethods({
                    setCustomShippingValues : function(amount, description, method){
                        var data = {};
                        data['order[shipping_method]'] = method;
                        data['order[shipping_amount]'] = amount;
                        data['order[base_shipping_amount]'] = amount;
                        data['order[shipping_description]'] = description;
                        data['collect_shipping_rates'] = 1;
                        this.loadArea(['shipping_method', 'totals', 'billing_method'], true, data);
                    },

                    submit : function()
                    {
                        if (this.orderItemChanged) {
                            if (confirm('You have item changes')) {
                                if (editForm.submit()) {
                                    disableElements('save');
                                }
                            } else {
                                this.itemsUpdate();
                            }
                        } else {
 							<?php  if(Mage::app()->getRequest()->getControllerName() == 'order_edit'){ ?>
								  stopCCValidation();
							<?php } ?>

                            if (editForm.submit()) {
                                disableElements('save');
                            }
                        }
                    }
                });
                //]]>
            </script>
        </dd>
        <?php else: ?>
        <dt><strong><?php echo $this->getCarrierName($code) ?></strong></dt>
        <dd>
            <ul>
            <?php foreach ($_rates as $_rate): ?>
                <?php $_radioProperty = 'name="order[shipping_method]" type="radio" onclick="order.setShippingMethod(this.value)"' ?>
                <?php $_code=$_rate->getCode() ?>
                <li>
                   <?php if ($_rate->getErrorMessage()): ?>
                        <ul class="messages">
                            <li class="error-msg"><?php echo $_rate->getErrorMessage() ?></li>
                        </ul>
                   <?php else: ?>
                        <?php $_checked = $this->isMethodActive($_code) ? 'checked="checked"' : '' ?>
                        <input <?php echo $_radioProperty ?> value="<?php echo $_code ?>" id="s_method_<?php echo $_code ?>" <?php echo $_checked ?>/>
                        <label class="normal" for="s_method_<?php echo $_code ?>">
                            <?php echo $_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription()?> -
                            <strong>
                                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                                <?php echo $_excl; ?>
                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif; ?>
                            </strong>
                        </label>
                   <?php endif ?>
                </li>
            <?php endforeach; ?>
            </ul>
        </dd>
        <?php endif; ?>
    <?php endforeach; ?>
    </dl>
    </div>
    <?php if ($_rate = $this->getActiveMethodRate()): ?>
        <div id="order-shipping-method-info">
            <strong><?php echo $this->getCarrierName($_rate->getCarrier()) ?></strong><br/>
            <?php if (($_rate->getCode() == 'customshipprice_customshipprice') && ($this->getCustomTitle())): ?>
                <?php if ($this->getCustomTitle()): echo $this->getCustomTitle(); endif; ?> -
            <?php else: ?>
                <?php echo $_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription() ?> -
            <?php endif; ?>
            <strong>
                <?php if (($_rate->getCode() == 'customshipprice_customshipprice') && ($this->getCustomShippingPrice())): ?>
                    <?php $_excl = $this->getShippingPrice($this->getCustomShippingPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                    <?php $_incl = $this->getShippingPrice($this->getCustomShippingPrice(), true); ?>
                <?php else: ?>
                    <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                <?php endif; ?>
                <?php echo $_excl; ?>
                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                <?php endif; ?>
            </strong>
            <br/>
            <a href="#" onclick="$('order-shipping-method-info').hide();$('order-shipping-method-choose').show();return false">
                <?php echo Mage::helper('sales')->__('Click to change shipping method') ?>
            </a>
			&nbsp;&nbsp;Or&nbsp;&nbsp;
	 <a style="cursor:pointer;" href="#" onclick="$('order-shipping-method-info').hide();$('order-shipping-method-choose').show();return false"><input type="checkbox" name="newcsprice" value=""/></a>&nbsp; <a style="cursor:pointer;" href="#" onclick="$('order-shipping-method-info').hide();$('order-shipping-method-choose').show();return false"><span style="text-decoration:underline;"><?php echo Mage::helper('sales')->__('Change Custom Price and/or Method'); ?></span></a>
			
			<br/>
			 <a href="#" onclick="order.loadShippingRates();$('order-shipping-method-choose').show();return false">
            	<?php echo Mage::helper('sales')->__('Load live shipping rates') ?>
        	</a>
		
        </div>
    <?php else: ?>
        <script type="text/javascript">$('order-shipping-method-choose').show();</script>
    <?php endif; ?>
<?php elseif($this->getIsRateRequest()): ?>
    <strong><?php echo Mage::helper('sales')->__('Sorry, no quotes are available for this order at this time.') ?></strong>
<?php else: ?>
    <div id="order-shipping-method-summary">
        <a href="#" onclick="order.loadShippingRates();return false">
            <?php echo Mage::helper('sales')->__('Get shipping methods and rates') ?>
        </a>
        <input type="hidden" name="order[has_shipping]" value="" class="required-entry">
    </div>
<?php endif; ?>
<div style="display:none;" id="shipping-method-overlay" class="overlay"><span><?php echo $this->__('Shipping method selection is not applicable') ?></span></div>
<script type="text/javascript">
order.overlay('shipping-method-overlay', <?php if ($this->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);
order.overlay('address-shipping-overlay', <?php if ($this->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);
</script>


<?php
  
 if(Mage::app()->getRequest()->getControllerName() == 'order_edit')
{
	$payment = $this->_getSession()->getOrder()->getPayment();
	$currentPaymentMethod = $this->_getSession()->getOrder()->getPayment()->getMethod();
	$array = array('acimpro','ccsave','authorizenet','direct','paypal_direct','verisign');
 	
	$activePaymentMethods = Mage::getSingleton('payment/config')->getActiveMethods();
	$payMethods = array();
	$i = 0 ;$paymentArray = ''; 
	$count = count($activePaymentMethods) ;
	
	foreach ($activePaymentMethods as $paymentCode=>$paymentModel) 
	{
		//$paymentTitle = Mage::getStoreConfig('payment/'.$paymentCode.'/title');
		//$payMethods[$paymentCode] = $paymentTitle;
		if($i <= $count){
			$paymentArray .= '"'  .  $paymentCode  .'"' ; 
			
			if($i < $count){ $paymentArray = $paymentArray . ",";}
		}
	}
?>
	<script>
	  function stopCCValidation()
	  {			
	  		var jsCurrentPaymentMethod = '<?php echo $this->_getSession()->getOrder()->getPayment()->getMethod(); ?>' ;

			//var paymentArray = ["paypal_billing_agreement","checkmo","acimpro","ccsave","authorizenet","direct","paypal_direct","verisign"];
			
			<?php
			if($paymentArray != "") 
			{
			?>
				var paymentArray = <?php echo "[" . $paymentArray . "]"; ?>;
			<?php }else{ ?>
				var paymentArray = ["paypal_billing_agreement","checkmo","acimpro","ccsave","authorizenet","direct","paypal_direct","verisign"];
			<?php }	?>
			
			var arrayLength = paymentArray.length;
			for (var i = 0; i < arrayLength; i++)
			{
				if ($('p_method_'+paymentArray[i]) && $('p_method_'+paymentArray[i]).checked && $('payment_form_'+paymentArray[i]))
				{
					$('payment_form_'+paymentArray[i]).hide();
					 //payment.switchMethod('');
				}
				else
				{
					if(jsCurrentPaymentMethod == 'paypal_express')
					{
						//payment.switchMethod = order.switchPaymentMethod.bind(order);
						if($('p_method_'+paymentArray[i]))
						{
							$('p_method_'+paymentArray[i]).checked = true ;
							payment.switchMethod('');
							break;
						}
					}
				}
			}
 	   }
	</script>
	
	<script>
		var jsCurrentPaymentMethodAuto = '<?php echo $this->_getSession()->getOrder()->getPayment()->getMethod(); ?>' ;
		
		if ($('p_method_'+jsCurrentPaymentMethodAuto) && $('p_method_'+jsCurrentPaymentMethodAuto).checked && $('payment_form_'+jsCurrentPaymentMethodAuto))
			{
				$('payment_form_'+jsCurrentPaymentMethodAuto).hide();
				// setTimeout('stopCCValidation()', 100);  
				setTimeout('reHidePaymentForm()', 100);  
			}
		
		function reHidePaymentForm()
		{
			$('payment_form_'+jsCurrentPaymentMethodAuto).hide();
		}
		
	</script>
	
<?php } else{ ?>
				<script>	</script>
<?php } ?>