<?php $statuses = Mage::getModel('sales/order_status')->getResourceCollection(); ?>

<div id="order_history_block">
    <?php if ($this->canAddComment()): ?>
        <div id="history_form" class="order-history-form">
            <div><?php echo Mage::helper('sales')->__('Add Order Comments') ?></div>
        <span class="field-row">
            <label class="normal" for="history_status"><?php echo Mage::helper('sales')->__('Status') ?></label><br/>
            <select name="history[status]" class="select" id="history_status">
                <?php foreach ($statuses as $status): ?>
                    <?php $_code = $status->getStatus(); $_label = $status->getLabel(); ?>
                    <option value="<?php echo $_code ?>"<?php if ($_code == $this->getOrder()->getStatus()): ?> selected="selected"<?php endif; ?>><?php echo $_label ?></option>
                <?php endforeach; ?>
            </select>
        </span>
        <span class="field-row">
            <label class="normal" for="history_comment"><?php echo Mage::helper('sales')->__('Comment') ?></label>
            <textarea name="history[comment]" rows="3" cols="5" style="height:6em; width:99%;"
                      id="history_comment"></textarea>
        </span>
            <div class="f-left">
                <?php if ($this->canSendCommentEmail()): ?>
                    <input name="history[is_customer_notified]" type="checkbox" id="history_notify" value="1"/>
                    <label class="normal" for="history_notify"> <?php echo Mage::helper('sales')->__('Notify Customer by Email') ?></label>
                    <br/>
                <?php endif; ?>
                <input name="history[is_visible_on_front]" type="checkbox" id="history_visible" value="1"/>
                <label class="normal" for="history_visible"> <?php echo Mage::helper('sales')->__('Visible on Frontend') ?></label>
            </div>
            <div class="f-right">
                <?php echo $this->getChildHtml('submit_button') ?>
            </div>
            <div class="clear"></div>
        </div>
        <div class="divider"></div>
    <?php endif; ?>
    <ul class="note-list">
        <?php foreach ($this->getOrder()->getStatusHistoryCollection(true) as $_item): ?>
            <li>
                <?php $is_allow_delete = Mage::getSingleton('admin/session')->isAllowed('iwd_ordermanager/order/actions/delete_comment'); ?>
                <?php if($is_allow_delete): ?>
                    <div id="delete_history_<?php echo $_item->getEntityId(); ?>" class="delete_history_icon"><i class="fa fa-trash" aria-hidden="true"></i></div>
                <?php endif; ?>
                <?php $is_allow_edit = Mage::getSingleton('admin/session')->isAllowed('iwd_ordermanager/order/actions/edit_comment'); ?>
                <?php if($is_allow_edit): ?>
                    <div id="update_history_<?php echo $_item->getEntityId(); ?>" class="update_history_icon"><i class="fa fa-pencil" aria-hidden="true"></i></div>
                <?php endif; ?>

                <strong><?php echo $this->helper('core')->formatDate($_item->getCreatedAtDate(), 'medium') ?></strong>
                <?php echo $this->helper('core')->formatTime($_item->getCreatedAtDate(), 'medium') ?><span
                    class="separator">|</span><strong><?php echo $_item->getStatusLabel() ?></strong><br/>
                <small><?php echo $this->helper('sales')->__('Customer') ?>
                    <strong class="subdue">
                        <?php if ($this->isCustomerNotificationNotApplicable($_item)): ?>
                            <?php echo $this->helper('sales')->__('Notification Not Applicable') ?>
                        <?php elseif ($_item->getIsCustomerNotified()): ?>
                            <?php echo $this->helper('sales')->__('Notified') ?>
                            <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16"
                                 alt=""/>
                        <?php
                        else: ?>
                            <?php echo $this->helper('sales')->__('Not Notified') ?>
                        <?php endif; ?>
                    </strong>
                </small>
                <div id="comment_text_<?php echo $_item->getEntityId(); ?>">
                    <?php if ($_item->getComment()): ?>
                        <?php echo $this->escapeHtml($_item->getComment(), array('a', 'b', 'br', 'strong', 'i', 'u')) ?>
                    <?php endif; ?>
                </div>

                <?php
                    $adminId = $_item->getAdminId();
                    $adminEmail = $_item->getAdminEmail();
                    $adminUsername = '';
                    if (!empty($adminId)) {
                        $user = Mage::getModel('admin/user')->load($adminId);
                        $adminUsername = ucfirst($user->getFirstname()) . ' ' . ucfirst($user->getLastname());
                    }
                ?>
                <?php if(!empty($adminEmail)): ?>
                    <div class="admin-name"><small><?php echo $this->helper('iwd_ordermanager')->__('by') ?> <?php echo $adminUsername ?> (<?php echo $adminEmail ?>)</small></div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <script type="text/javascript">
        if ($("order_status")){
            $("order_status").update("<?php echo $this->getOrder()->getStatusLabel() ?>");
        }
        if(typeof(jQueryIWD) == "undefined"){if(typeof(jQuery) != "undefined") {jQueryIWD = jQuery;}} $ji = jQueryIWD;
        $ji(document).ready(function () {
            IWD.OrderManager.Comments.init('order');
        });
    </script>
</div>
