<?php
$evolvedmethod = new Ideal_Evolved_Block_Evolved();
if(method_exists($evolvedmethod, 'getBlockConfig'))
{
	if($evolvedmethod->getBlockConfig('evolved_form_footerbar')['footer_footerbar_htmlblock'])
	{
		$content = $evolvedmethod->getBlockConfig('evolved_form_footerbar')['footer_footerbar_htmlblock'];
	}
	else 
	{
		$theme = Mage::helper('evolved')->getThemeConfig();	
		$content = $theme['footer_footerbar_htmlblock'];
	}
}
else
{
	$theme = Mage::helper('evolved')->getThemeConfig();
	$content = $theme['footer_footerbar_htmlblock'];
}

$helper = Mage::helper('cms');
$processor = $helper->getPageTemplateProcessor();
?>
<div class="subscribe_and_social_media">
	<div class="center"><?php echo $processor->filter($content); ?></div>
	<div class="center subscribe_only"><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('page/html/footerbar/subscribe.phtml')->toHtml(); ?></div>
	<div class="center social_media_icon">
		<?php echo $this->getLayout()->createBlock('evolved/evolved')->setTemplate('page/html/footerbar/social_media_only.phtml')->toHtml(); ?>
	</div>
</div>